<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
the_post(); $post_id = get_the_ID(); $archive_url = GE_WTP_Knowledge_Base::archive_url(); $shop_url = function_exists( 'graphexpress_shop_url' ) ? graphexpress_shop_url() : home_url( '/shop/' ); $portal_url = home_url( '/cliente-markcom/' ); $terms = get_the_terms( $post_id, GE_WTP_Knowledge_Base::TAXONOMY ); $topic = $terms && ! is_wp_error( $terms ) ? $terms[0] : null; $whatsapp = 'https://wa.me/5491151393899?text=' . rawurlencode( 'Hola Graph Express, tengo una consulta sobre: ' . get_the_title() );
$related = get_posts( array( 'post_type' => GE_WTP_Knowledge_Base::POST_TYPE, 'post_status' => 'publish', 'numberposts' => 3, 'post__not_in' => array( $post_id ) ) );
?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo( 'charset' ); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head><body <?php body_class( 'gx-home ge-knowledge-page ge-guide-single' ); ?>><?php wp_body_open(); ?>
<a class="gx-skip-link" href="#articulo">Ir al artículo</a><div class="gx-announcement"><div class="gx-wrap"><span><b>Guías Graph Express</b> Información clara para imprimir mejor.</span><a href="tel:+5491151393899">+54 9 11 5139-3899</a></div></div>
<header class="gx-header"><div class="gx-wrap gx-header-inner"><a class="gx-logo" href="<?php echo esc_url( home_url( '/' ) ); ?>"><span class="gx-logo-mark">GE</span><span><strong>GRAPH EXPRESS</strong><small>Impresión que comunica</small></span></a><button class="gx-menu-toggle" type="button" aria-expanded="false" aria-controls="gx-navigation"><span></span><span></span><span></span><span class="screen-reader-text">Abrir menú</span></button><nav class="gx-nav" id="gx-navigation" aria-label="Navegación principal"><a href="<?php echo esc_url( $shop_url ); ?>">Tienda</a><a class="is-active" href="<?php echo esc_url( $archive_url ); ?>">Guías</a><a href="<?php echo esc_url( home_url( '/#servicios' ) ); ?>">Servicios</a><a href="<?php echo esc_url( home_url( '/#trabajos' ) ); ?>">Trabajos</a><a href="<?php echo esc_url( home_url( '/#contacto' ) ); ?>">Contacto</a><a class="gx-nav-mobile-action is-portal" href="<?php echo esc_url( $portal_url ); ?>">Portal clientes</a><a class="gx-nav-mobile-action is-consult" href="<?php echo esc_url( $whatsapp ); ?>" target="_blank" rel="noopener">Consultar por WhatsApp</a></nav><div class="gx-header-actions"><a class="gx-portal-link" href="<?php echo esc_url( $portal_url ); ?>">Portal clientes</a><a class="gx-button gx-button-small gx-button-dark" href="<?php echo esc_url( $whatsapp ); ?>" target="_blank" rel="noopener">Consultar</a></div></div></header>
<main id="articulo"><header class="ge-article-hero is-<?php echo esc_attr( GE_WTP_Knowledge_Base::color( $post_id ) ); ?>"><div class="gx-wrap"><div class="ge-breadcrumbs"><a href="<?php echo esc_url( $archive_url ); ?>">Guías</a><span>→</span><?php if ( $topic ) : ?><a href="<?php echo esc_url( get_term_link( $topic ) ); ?>"><?php echo esc_html( $topic->name ); ?></a><?php endif; ?></div><div class="ge-article-hero-grid"><div><span class="ge-article-topic"><?php echo esc_html( $topic ? $topic->name : 'Guía de impresión' ); ?></span><h1><?php the_title(); ?></h1><p><?php echo esc_html( get_the_excerpt() ); ?></p><small><?php echo esc_html( GE_WTP_Knowledge_Base::reading_time( $post_id ) ); ?> minutos de lectura · Actualizado <?php echo esc_html( get_the_modified_date( 'd/m/Y' ) ); ?></small></div><b><?php echo esc_html( GE_WTP_Knowledge_Base::icon( $post_id ) ); ?></b></div></div></header>
<div class="ge-article-layout gx-wrap"><article class="ge-article-content"><?php the_content(); ?></article><aside class="ge-article-aside"><div><span>¿Estás preparando un archivo?</span><h3>Podemos revisarlo antes de imprimir.</h3><p>Contanos qué producto necesitás y te indicamos la configuración correcta.</p><a target="_blank" rel="noopener" href="<?php echo esc_url( $whatsapp ); ?>">Consultar ahora →</a></div><a class="ge-all-guides" href="<?php echo esc_url( $archive_url ); ?>">← Ver todas las guías</a></aside></div>
<?php if ( $related ) : ?><section class="ge-related-guides"><div class="gx-wrap"><div class="ge-guide-heading"><div><span>Seguí aprendiendo</span><h2>También puede servirte</h2></div></div><div class="ge-related-grid"><?php foreach ( $related as $item ) : ?><a href="<?php echo esc_url( get_permalink( $item ) ); ?>"><b><?php echo esc_html( GE_WTP_Knowledge_Base::icon( $item->ID ) ); ?></b><span><strong><?php echo esc_html( get_the_title( $item ) ); ?></strong><small>Leer guía →</small></span></a><?php endforeach; ?></div></div></section><?php endif; ?></main>
<footer class="gx-footer"><div class="gx-wrap gx-footer-bottom"><span>© <?php echo esc_html( wp_date( 'Y' ) ); ?> Graph Express</span><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Volver al inicio</a></div></footer><?php wp_footer(); ?></body></html>
