<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$archive_url = GE_WTP_Knowledge_Base::archive_url();
$shop_url = function_exists( 'graphexpress_shop_url' ) ? graphexpress_shop_url() : home_url( '/shop/' );
$portal_url = home_url( '/cliente-markcom/' );
$whatsapp = 'https://wa.me/5491151393899?text=' . rawurlencode( 'Hola Graph Express, necesito ayuda para preparar un archivo.' );
$topics = get_terms( array( 'taxonomy' => GE_WTP_Knowledge_Base::TAXONOMY, 'hide_empty' => false ) );
$current = is_tax( GE_WTP_Knowledge_Base::TAXONOMY ) ? get_queried_object() : null;
?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo( 'charset' ); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head><body <?php body_class( 'gx-home ge-knowledge-page' ); ?>><?php wp_body_open(); ?>
<a class="gx-skip-link" href="#guias">Ir a las guías</a><div class="gx-announcement"><div class="gx-wrap"><span><b>Guías Graph Express</b> Información clara para imprimir mejor.</span><a href="tel:+5491151393899">+54 9 11 5139-3899</a></div></div>
<header class="gx-header"><div class="gx-wrap gx-header-inner"><a class="gx-logo" href="<?php echo esc_url( home_url( '/' ) ); ?>"><span class="gx-logo-mark">GE</span><span><strong>GRAPH EXPRESS</strong><small>Impresión que comunica</small></span></a><button class="gx-menu-toggle" type="button" aria-expanded="false" aria-controls="gx-navigation"><span></span><span></span><span></span><span class="screen-reader-text">Abrir menú</span></button><nav class="gx-nav" id="gx-navigation" aria-label="Navegación principal"><a href="<?php echo esc_url( $shop_url ); ?>">Tienda</a><a class="is-active" href="<?php echo esc_url( $archive_url ); ?>">Guías</a><a href="<?php echo esc_url( home_url( '/#servicios' ) ); ?>">Servicios</a><a href="<?php echo esc_url( home_url( '/#trabajos' ) ); ?>">Trabajos</a><a href="<?php echo esc_url( home_url( '/#contacto' ) ); ?>">Contacto</a></nav><div class="gx-header-actions"><a class="gx-portal-link" href="<?php echo esc_url( $portal_url ); ?>">Portal clientes</a><a class="gx-button gx-button-small gx-button-dark" href="<?php echo esc_url( $whatsapp ); ?>" target="_blank" rel="noopener">Consultar</a></div></div></header>
<main id="guias"><section class="ge-knowledge-hero"><div class="gx-wrap"><span class="gx-kicker"><i></i> Centro de ayuda</span><h1>Todo lo que necesitás saber <em>antes de imprimir.</em></h1><p>Guías simples sobre archivos, papeles, terminaciones y procesos para que cada trabajo salga como lo imaginaste.</p><form role="search" method="get" action="<?php echo esc_url( home_url( '/' ) ); ?>"><span>⌕</span><input type="search" name="s" value="<?php echo esc_attr( get_search_query() ); ?>" placeholder="Buscar sangrado, papeles, encuadernación…"><input type="hidden" name="post_type" value="<?php echo esc_attr( GE_WTP_Knowledge_Base::POST_TYPE ); ?>"><button type="submit">Buscar</button></form></div></section>
<section class="ge-knowledge-content"><div class="gx-wrap"><nav class="ge-topic-filter" aria-label="Temas"><a class="<?php echo $current ? '' : 'is-active'; ?>" href="<?php echo esc_url( $archive_url ); ?>">Todas las guías</a><?php foreach ( $topics as $topic ) : ?><a class="<?php echo $current && $current->term_id === $topic->term_id ? 'is-active' : ''; ?>" href="<?php echo esc_url( get_term_link( $topic ) ); ?>"><?php echo esc_html( $topic->name ); ?></a><?php endforeach; ?></nav><div class="ge-guide-heading"><div><span><?php echo $current ? 'Tema' : 'Aprendé con nosotros'; ?></span><h2><?php echo esc_html( $current ? $current->name : 'Guías destacadas' ); ?></h2></div><b><?php echo esc_html( $GLOBALS['wp_query']->found_posts ); ?> publicaciones</b></div>
<?php if ( have_posts() ) : ?><div class="ge-guide-grid"><?php while ( have_posts() ) : the_post(); $terms = get_the_terms( get_the_ID(), GE_WTP_Knowledge_Base::TAXONOMY ); ?><article class="ge-guide-card is-<?php echo esc_attr( GE_WTP_Knowledge_Base::color( get_the_ID() ) ); ?>"><a href="<?php the_permalink(); ?>"><div class="ge-guide-card-visual"><span><?php echo esc_html( GE_WTP_Knowledge_Base::icon( get_the_ID() ) ); ?></span><small><?php echo esc_html( $terms && ! is_wp_error( $terms ) ? $terms[0]->name : 'Guía de impresión' ); ?></small></div><div class="ge-guide-card-body"><span><?php echo esc_html( GE_WTP_Knowledge_Base::reading_time( get_the_ID() ) ); ?> min de lectura</span><h2><?php the_title(); ?></h2><p><?php echo esc_html( get_the_excerpt() ); ?></p><b>Leer guía <i>→</i></b></div></a></article><?php endwhile; ?></div><?php else : ?><div class="ge-guide-empty"><h2>No encontramos esa guía.</h2><p>Probá con otro término o consultanos y te ayudamos.</p></div><?php endif; ?></div></section>
<section class="ge-knowledge-cta"><div class="gx-wrap"><div><span>¿Te quedó alguna duda?</span><h2>Revisamos tu proyecto antes de producir.</h2></div><a class="gx-button gx-button-primary" target="_blank" rel="noopener" href="<?php echo esc_url( $whatsapp ); ?>">Consultar por WhatsApp ↗</a></div></section></main>
<footer class="gx-footer"><div class="gx-wrap gx-footer-bottom"><span>© <?php echo esc_html( wp_date( 'Y' ) ); ?> Graph Express</span><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Volver al inicio</a></div></footer><?php wp_footer(); ?></body></html>
