[graphex]
user = apache
group = webusers
listen = /opt/php7-4/var/run/php-fpm/graphex.sock
listen.owner = apache
listen.group = webusers
listen.mode = 0660
catch_workers_output = yes
pm = ondemand
pm.max_children = 4
pm.max_requests = 100
pm.process_idle_timeout = 10s
request_terminate_timeout = 180s
security.limit_extensions = .php .phtml
php_admin_flag[display_errors] = Off
php_admin_flag[display_startup_errors] = Off
php_admin_flag[log_errors] = On
php_admin_value[error_log] = /opt/php7-4/var/log/graphex-php.log
php_admin_value[post_max_size] = 128M
php_admin_value[upload_max_filesize] = 127M
php_admin_value[memory_limit] = 256M
php_admin_value[max_execution_time] = 60
php_admin_value[max_input_time] = 120
