<?php
defined('ABSPATH') || exit;

/** Cost data is a projection of Supplier Workspace, Stock and explicit internal rates. */
final class GE_WTP_Cost_Engine {
    const VERSION='1.0.1';
    const LIST_META='_ge_price_normalized';
    const SOURCE='ge_cost_source';
    const CHANGE='ge_cost_change';
    private static $catalog_cache=null;
    public static function init() {
        add_action('init',array(__CLASS__,'types'),9);
        add_action('rest_api_init',array(__CLASS__,'routes'));
        add_filter('pre_get_document_title',static function($title){if(function_exists('is_product')&&is_product()){$custom=get_post_meta(get_queried_object_id(),'_ge_seo_title',true);if($custom)return $custom;}return $title;});
        add_action('wp_head',static function(){if(function_exists('is_product')&&is_product()){$description=get_post_meta(get_queried_object_id(),'_ge_seo_description',true);if($description)echo '<meta name="description" content="'.esc_attr($description).'">';}},3);
    }
    public static function types() {
        foreach(array(self::SOURCE,self::CHANGE) as $type) register_post_type($type,array('public'=>false,'show_ui'=>false,'supports'=>array('title')));
    }
    public static function enabled() { return GE_WTP_Operations::enabled() && get_option('ge_cost_engine_enabled')==='yes'; }
    public static function permission($write=false) {
        if(class_exists('GE_Organization_Runtime'))GE_Organization_Runtime::require_permission('cost_engine',$write);
        if(!self::enabled() || !is_user_logged_in() || (!current_user_can('manage_options')&&!current_user_can($write?'ge_manage_costs':'ge_view_costs'))) throw new RuntimeException('Sin permiso de costos.');
    }
    public static function install() {
        if(!current_user_can('manage_options')) throw new RuntimeException('Sólo un administrador puede instalar el módulo.');
        global $wpdb; $table=GE_WTP_Operations::table('recipes');
        if(!$wpdb->get_var($wpdb->prepare('SHOW COLUMNS FROM '.$table.' LIKE %s','cost_json'))) {
            if(false===$wpdb->query('ALTER TABLE '.$table.' ADD COLUMN cost_json longtext NULL')) throw new RuntimeException('No se pudo extender la receta existente.');
        }
        foreach(array('administrator',GE_WTP_Staff_Portal::ROLE) as $name) { $role=get_role($name); if($role) foreach(array('ge_view_costs','ge_manage_costs','ge_manage_products','upload_files') as $cap) $role->add_cap($cap); }
        update_option('ge_cost_engine_schema',self::VERSION,false);
    }
    public static function put($id,$key,$data) {
        update_post_meta($id,$key,wp_slash($data));
        $stored=get_post_meta($id,$key,true);
        // Global File Analyzer enriches the same workspace record synchronously.
        if($key===GE_WTP_Supplier_Workspace::META && is_array($stored) && is_array($data)){foreach(array('analysis','file_analysis_ref','analysis_status') as $field){unset($stored[$field],$data[$field]);}}
        if(is_array($data)?$stored!==$data:(string)$stored!==(string)$data) throw new RuntimeException('No se pudo guardar el registro.');
    }
    public static function audit($event,$ref,$before,$after) { GE_WTP_Operations::audit('cost_'.$event,$ref,array('before'=>$before,'after'=>$after)); }
    public static function hash($data) { return hash('sha256',wp_json_encode($data)); }
    public static function lock($key,$fn) {
        global $wpdb; $name='ge_cost_'.substr(hash('sha256',$key),0,40);
        if((int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,5)',$name))!==1) throw new RuntimeException('Otra operación está en curso; reintentá.');
        try { return $fn(); } finally { $wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$name)); }
    }
    public static function lists($supplier='') {
        self::permission(); $args=array('post_type'=>GE_WTP_Supplier_Workspace::ENTRY,'post_status'=>'private','numberposts'=>500,'fields'=>'ids','orderby'=>'ID','order'=>'DESC');
        if($supplier) { $args['meta_key']='_ge_supplier_key'; $args['meta_value']=$supplier; }
        $out=array(); foreach(get_posts($args) as $id) { $r=get_post_meta($id,GE_WTP_Supplier_Workspace::META,true); if(($r['type']??'')!=='price_list') continue; $n=get_post_meta($id,self::LIST_META,true); $out[]=array('id'=>(int)$id,'supplier_id'=>get_post_meta($id,'_ge_supplier_key',true),'title'=>$r['title']??get_the_title($id),'effective_date'=>$r['valid_from']??'','uploaded_at'=>$r['created_at']??'','currency'=>strtoupper($r['currency']??'ARS'),'file_name'=>$r['file_name']??'','checksum'=>$r['file_hash']??'','status'=>$n['status']??(!empty($r['active'])?'legacy_active':'draft'),'active'=>!empty($r['active']),'notes'=>$r['notes']??'','count'=>count($n['items']??array())); }
        return $out;
    }
    public static function list_get($id) {
        self::permission(); $r=get_post_meta($id,GE_WTP_Supplier_Workspace::META,true); $supplier=get_post_meta($id,'_ge_supplier_key',true);
        if(get_post_type($id)!==GE_WTP_Supplier_Workspace::ENTRY || ($r['type']??'')!=='price_list' || !GE_WTP_Supplier_Workspace::supplier($supplier)) throw new RuntimeException('Lista inexistente.');
        return array('id'=>(int)$id,'supplier_id'=>$supplier,'workspace'=>$r,'normalized'=>get_post_meta($id,self::LIST_META,true)?:array('status'=>'draft','items'=>array()));
    }
    public static function normalize($items,$list) {
        if(!is_array($items)||!$items||count($items)>5000) throw new InvalidArgumentException('La lista requiere entre 1 y 5000 ítems.');
        $out=array(); $seen=array();
        foreach($items as $row) {
            $sku=sanitize_text_field($row['supplier_sku']??''); $name=sanitize_text_field($row['description']??''); $unit=sanitize_key($row['unit']??'');
            if(!$sku || strlen($sku)>120 || isset($seen[$sku]) || !$name || !in_array($unit,array('unit','m2','m','roll','ream','thousand','sheet','lot','kg','l','hour','click','box','kit','ml','cartridge','ribbon'),true)) throw new InvalidArgumentException('Referencia duplicada, descripción o unidad inválida.');
            $seen[$sku]=true; $currency=strtoupper($row['currency']??$list['workspace']['currency']??'ARS');
            if(!in_array($currency,array('ARS','USD','EUR'),true)) throw new InvalidArgumentException('Moneda inválida.');
            $tax=$row['tax_treatment']??'unknown'; if(!in_array($tax,array('unknown','excluded','included_recoverable','included_nonrecoverable','exempt'),true)) throw new InvalidArgumentException('Tratamiento impositivo inválido.');
            $mode=$row['pricing_mode']??'unit'; if(!in_array($mode,array('unit','lot','formula'),true)) throw new InvalidArgumentException('Modelo de costo inválido.');
            $r=array('supplier_id'=>$list['supplier_id'],'supplier_sku'=>$sku,'description'=>$name,'category'=>sanitize_text_field($row['category']??''),'unit'=>$unit,'min_qty'=>GE_WTP_Cost_Math::number($row['min_qty']??0,'mínimo'),'base_cost'=>GE_WTP_Cost_Math::number($row['base_cost']??null,'costo'),'currency'=>$currency,'tax_treatment'=>$tax,'tax_percent'=>GE_WTP_Cost_Math::number($row['tax_percent']??0,'IVA',0,100),'pricing_mode'=>$mode,'effective_from'=>$list['workspace']['valid_from']??'','source_list_id'=>$list['id'],'tiers'=>array(),'attributes'=>array(),'formula_note'=>sanitize_textarea_field($row['formula_note']??''));
            foreach((array)($row['attributes']??array()) as $key=>$value) $r['attributes'][sanitize_key($key)]=sanitize_text_field($value);
            $last=-1; foreach((array)($row['tiers']??array()) as $tier) { $q=GE_WTP_Cost_Math::number($tier['min_qty']??null,'escala',0); if($q<=$last) throw new InvalidArgumentException('Escalas deben ser únicas y ascendentes.'); $last=$q; $m=$tier['mode']??$mode; if(!in_array($m,array('unit','lot'),true)) throw new InvalidArgumentException('Modo de escala inválido.'); $r['tiers'][]=array('min_qty'=>$q,'cost'=>GE_WTP_Cost_Math::number($tier['cost']??null,'costo de escala'),'mode'=>$m); }
            $out[]=$r;
        }
        return $out;
    }
    public static function parse($a) {
        self::permission(true); $list=self::list_get(absint($a['list_id']??0));
        if(!in_array($list['normalized']['status'],array('draft','parsed'),true)) throw new RuntimeException('La versión revisada es inmutable; cargá otra lista.');
        $r=$list['workspace']; $base=realpath(WP_CONTENT_DIR.'/ge-private/supplier-workspace/'.$list['supplier_id']); $path=$base?realpath($base.'/'.($r['stored_name']??'')):false;
        if(!$path||strpos($path,$base.DIRECTORY_SEPARATOR)!==0||!is_file($path)||!hash_equals($r['file_hash']??'',hash_file('sha256',$path))) throw new RuntimeException('Archivo privado no disponible o checksum distinto.');
        $python=defined('GE_FILE_ANALYZER_PYTHON')?GE_FILE_ANALYZER_PYTHON:'/opt/ge-file-analyzer/runtime/bin/python3';
        $proc=@proc_open(array($python,GE_WTP_PLUGIN_DIR.'bin/supplier-price-parser.py',$path,sanitize_text_field($a['sheet']??'')),array(array('pipe','r'),array('pipe','w'),array('pipe','w')),$pipes,null,array('PATH'=>dirname($python).':/usr/bin:/bin','LC_ALL'=>'C'));
        if(!is_resource($proc)) throw new RuntimeException('Parser no disponible.'); fclose($pipes[0]); stream_set_blocking($pipes[1],false); stream_set_blocking($pipes[2],false); $raw='';$start=microtime(true);
        do { $raw.=stream_get_contents($pipes[1]); stream_get_contents($pipes[2]); $status=proc_get_status($proc); if(strlen($raw)>4194304||microtime(true)-$start>25) { proc_terminate($proc,9); fclose($pipes[1]);fclose($pipes[2]);proc_close($proc);throw new RuntimeException('El parser excedió el límite; dividí el archivo.'); } if($status['running']) usleep(20000); } while($status['running']);
        $raw.=stream_get_contents($pipes[1]);fclose($pipes[1]);fclose($pipes[2]);proc_close($proc);$extracted=json_decode($raw,true);
        if(!is_array($extracted)||!isset($extracted['rows'])) throw new RuntimeException('Respuesta inválida del parser.');
        return self::lock('list:'.$list['id'],function()use($list,$extracted){return GE_WTP_Operations::transaction(function()use($list,$extracted){$fresh=self::list_get($list['id']);if(self::hash($fresh)!==self::hash($list))throw new RuntimeException('La lista cambió; reintentá.');$next=array('status'=>'parsed','items'=>array(),'extraction'=>$extracted,'parsed_at'=>gmdate('c'),'parser_version'=>self::VERSION);self::put($list['id'],self::LIST_META,$next);self::audit('list_parsed',$list['id'],$list['normalized'],$next);return $next;});});
    }
    public static function review($a) {
        self::permission(true); $id=absint($a['list_id']??0); return self::lock('list:'.$id,function()use($a,$id){ return GE_WTP_Operations::transaction(function()use($a,$id){$list=self::list_get($id);if(!in_array($list['normalized']['status'],array('draft','parsed'),true)||!empty($list['workspace']['active']))throw new RuntimeException('La lista vigente/revisada es inmutable; cargá una nueva versión.');$items=self::normalize($a['items']??array(),$list);$next=$list['normalized'];$next['status']='reviewed';$next['items']=$items;$next['reviewed_at']=gmdate('c');$next['reviewed_by']=get_current_user_id();$next['review_hash']=self::hash($items);self::put($id,self::LIST_META,$next);self::audit('list_reviewed',$id,$list['normalized'],$next);return $next;});});
    }
    public static function compare($a) {
        $list=self::list_get(absint($a['list_id']??0));$old=array();$old_id=0;
        foreach(self::lists($list['supplier_id']) as $prior) if($prior['active']&&$prior['id']!==$list['id']){$old=self::list_get($prior['id'])['normalized']['items']??array();$old_id=$prior['id'];break;}
        return array('previous_list_id'=>$old_id,'list_id'=>$list['id'],'legacy_unstructured'=>$old_id&&!$old)+GE_WTP_Cost_Math::compare($old,$list['normalized']['items']??array());
    }
    public static function activate($a) {
        self::permission(true);self::invalidate();$list=self::list_get(absint($a['list_id']??0));
        return self::lock('supplier:'.$list['supplier_id'],function()use($list,$a){return GE_WTP_Operations::transaction(function()use($list,$a){$selected=self::list_get($list['id']);$n=$selected['normalized'];if($n['status']!=='reviewed'||($a['review_hash']??'')!==($n['review_hash']??'')||($selected['workspace']['valid_from']??'9999')>wp_date('Y-m-d'))throw new RuntimeException('Revisá la lista y su vigencia antes de activarla.');foreach(self::lists($list['supplier_id']) as $row){if(!$row['active']&&$row['id']!==$list['id'])continue;$r=self::list_get($row['id']);$w=$r['workspace'];$w['active']=$row['id']===$list['id'];self::put($row['id'],GE_WTP_Supplier_Workspace::META,$w);$nn=$r['normalized'];if($row['id']===$list['id']){$nn['status']='active';$nn['activated_at']=gmdate('c');}elseif(!empty($nn['items']))$nn['status']='archived';self::put($row['id'],self::LIST_META,$nn);self::audit('list_activation',$row['id'],$r,array('workspace'=>$w,'normalized'=>$nn));}return self::list_get($list['id']);});});
    }
    public static function catalog($a=array()) {
        self::permission(); if(self::$catalog_cache!==null){$out=self::$catalog_cache;return self::filter_catalog($out,$a);} $out=array();
        foreach(self::lists() as $list) if($list['active']) foreach(self::list_get($list['id'])['normalized']['items']??array() as $r){$r['ref']='supplier/'.$list['supplier_id'].'/'.rawurlencode($r['supplier_sku']);$r['source']='supplier_price_list';$r['status']='active';$out[]=$r;}
        {
            foreach(GE_WTP_Operations_Stock::items() as $r) foreach($r['costs']['by_currency']??array() as $currency=>$costs) foreach(array('latest'=>'last_unit_cost','average'=>'average_unit_cost') as $basis=>$key){$cost=$costs[$key];$meta=json_decode($r['metadata']??'',true)?:array();$out[]=array('ref'=>'stock/'.$r['id'].'/'.$basis.'/'.$currency,'description'=>$r['name'].' · '.($basis==='latest'?'última compra':'promedio'),'unit'=>$r['unit'],'base_cost'=>$cost===null?null:(float)$cost,'currency'=>$currency,'tax_treatment'=>$meta['cost_tax_treatment']??'unknown','tax_percent'=>$meta['cost_tax_percent']??0,'effective_from'=>self::stock_date($r['id'],$currency),'source'=>'stock_receipts','stock_item_id'=>(int)$r['id'],'status'=>$cost===null?'incomplete':'active','min_qty'=>0,'pricing_mode'=>'unit','tiers'=>array(),'provenance'=>$r['costs']['basis']);}
            foreach(get_posts(array('post_type'=>self::SOURCE,'post_status'=>'private','numberposts'=>500,'fields'=>'ids','orderby'=>'ID','order'=>'DESC')) as $id){$r=get_post_meta($id,'_ge_cost_rate',true);if($r&&($r['status']??'')==='active')$out[]=$r+array('ref'=>'internal/'.$id);}
        }
        $out=array_merge($out,GE_WTP_Cost_Legacy::catalog());self::$catalog_cache=$out;return self::filter_catalog($out,$a);
    }
    private static function filter_catalog($out,$a){$q=strtolower($a['query']??'');return array_values(array_filter($out,function($r)use($a,$q){return (empty($a['supplier_id'])||($r['supplier_id']??'')===$a['supplier_id'])&&(!$q||strpos(strtolower($r['description'].' '.$r['ref']),$q)!==false);}));}
    public static function invalidate(){self::$catalog_cache=null;}
    public static function upload($a){
        self::permission(true);$supplier=sanitize_key($a['supplier_id']??'');if(!GE_WTP_Supplier_Workspace::supplier($supplier))throw new RuntimeException('Proveedor inexistente.');$name=sanitize_file_name($a['file_name']??'');$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));$allowed=array('csv','xlsx','xls','pdf','jpg','jpeg','png');if(!in_array($ext,$allowed,true))throw new RuntimeException('Formato de archivo inválido.');$encoded=$a['file_base64']??'';if(!is_string($encoded)||strlen($encoded)>2800000)throw new RuntimeException('Máximo 2 MB por Action; para archivos mayores usá la carga de Gestión.');$bytes=base64_decode($encoded,true);if($bytes===false||!$bytes)throw new RuntimeException('Contenido de archivo inválido.');$mime=(new finfo(FILEINFO_MIME_TYPE))->buffer($bytes);$mimes=array('pdf'=>array('application/pdf'),'jpg'=>array('image/jpeg'),'jpeg'=>array('image/jpeg'),'png'=>array('image/png'),'xlsx'=>array('application/zip','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'),'xls'=>array('application/vnd.ms-excel','application/x-ole-storage','application/CDFV2'),'csv'=>array('text/plain','text/csv','application/csv'));if(!in_array($mime,$mimes[$ext],true))throw new RuntimeException('El contenido no coincide con el formato declarado.');$date=$a['effective_date']??'';if(!preg_match('/^\d{4}-\d{2}-\d{2}$/D',$date)||!checkdate((int)substr($date,5,2),(int)substr($date,8,2),(int)substr($date,0,4)))throw new RuntimeException('Fecha de vigencia inválida.');$currency=strtoupper($a['currency']??'ARS');if(!in_array($currency,array('ARS','USD','EUR'),true))throw new RuntimeException('Moneda inválida.');$title=sanitize_text_field($a['title']??$name);if(!$title)throw new RuntimeException('Título requerido.');
        $root=WP_CONTENT_DIR.'/ge-private/supplier-workspace';$dir=$root.'/'.$supplier;if(!wp_mkdir_p($dir))throw new RuntimeException('Storage privado no disponible.');foreach(array($root,$dir) as $base){if(!is_file($base.'/.htaccess')&&file_put_contents($base.'/.htaccess',"Require all denied\n")===false)throw new RuntimeException('No se pudo proteger el archivo.');if(!is_file($base.'/index.php'))file_put_contents($base.'/index.php',"<?php http_response_code(404);exit;\n");}$stored=wp_generate_uuid4().'.'.$ext;$path=$dir.'/'.$stored;if(file_put_contents($path,$bytes,LOCK_EX)!==strlen($bytes))throw new RuntimeException('No se pudo guardar el archivo.');chmod($path,0640);
        $id=wp_insert_post(array('post_type'=>GE_WTP_Supplier_Workspace::ENTRY,'post_status'=>'private','post_title'=>$title),true);if(is_wp_error($id)||!$id)throw new RuntimeException('No se pudo registrar lista.');self::put($id,'_ge_supplier_key',$supplier);$row=array('type'=>'price_list','title'=>$title,'valid_from'=>$date,'currency'=>$currency,'active'=>false,'notes'=>sanitize_textarea_field($a['notes']??''),'file_name'=>$name,'stored_name'=>$stored,'file_hash'=>hash('sha256',$bytes),'file_size'=>strlen($bytes),'created_at'=>current_time('mysql'),'created_by'=>get_current_user_id());self::put($id,GE_WTP_Supplier_Workspace::META,$row);self::put($id,self::LIST_META,array('status'=>'draft','items'=>array()));self::audit('list_uploaded',$id,null,array('supplier_id'=>$supplier,'checksum'=>$row['file_hash'],'title'=>$title));return self::list_get($id);
    }
    private static function stock_date($id,$currency){global $wpdb;return $wpdb->get_var($wpdb->prepare('SELECT MAX(created_at) FROM '.GE_WTP_Operations::table('stock_moves')." WHERE item_id=%d AND currency=%s AND movement_type='receipt'",$id,$currency));}
    public static function source($ref) { foreach(self::catalog() as $r) if($r['ref']===$ref)return $r; throw new RuntimeException('Fuente de costo no disponible: '.$ref); }
    public static function rate_save($a) {
        self::permission(true);self::invalidate();$name=sanitize_text_field($a['description']??'');$source=$a['source']??'manual_internal';
        if(!$name||!in_array($source,array('manual_internal','equipment_process','labor','logistics','outsourced_manual'),true))throw new RuntimeException('Nombre y fuente requeridos.');
        $fake=array('id'=>0,'supplier_id'=>'internal','workspace'=>array('valid_from'=>sanitize_text_field($a['effective_date']??wp_date('Y-m-d'))));
        $date=$fake['workspace']['valid_from'];if(!preg_match('/^\d{4}-\d{2}-\d{2}$/D',$date)||!checkdate((int)substr($date,5,2),(int)substr($date,8,2),(int)substr($date,0,4))||$date>wp_date('Y-m-d'))throw new RuntimeException('Fecha de costo inválida o futura.');
        $r=self::normalize(array($a+array('supplier_sku'=>'internal','description'=>$name)),$fake)[0];unset($r['supplier_id'],$r['supplier_sku'],$r['source_list_id']);$r['source']=$source;$r['status']='active';$r['notes']=sanitize_textarea_field($a['notes']??'');
        $parent=absint($a['parent_id']??0);$old=$parent?get_post_meta($parent,'_ge_cost_rate',true):null;$root=$old['root_id']??$parent;
        return self::lock('rate:'.($root?:wp_generate_uuid4()),function()use($parent,$name,$r,$root){return GE_WTP_Operations::transaction(function()use($parent,$name,$r,$root){$old=$parent?get_post_meta($parent,'_ge_cost_rate',true):null;if($parent&&(get_post_type($parent)!==self::SOURCE||($old['status']??'')!=='active'))throw new RuntimeException('La versión previa no es el costo vigente.');$id=wp_insert_post(array('post_type'=>self::SOURCE,'post_status'=>'private','post_title'=>$name),true);if(is_wp_error($id)||!$id)throw new RuntimeException('No se pudo guardar costo.');$r['parent_id']=$parent;$r['root_id']=$root?:$id;$r['id']=$id;$r['ref']='internal/'.$r['root_id'];$r['actor_id']=get_current_user_id();$r['created_at']=gmdate('c');if($parent){$old['status']='archived';self::put($parent,'_ge_cost_rate',$old);}self::put($id,'_ge_cost_rate',$r);self::audit('rate_created',$id,$old,$r);return $r;});});
    }
    public static function legacy_map($a){return GE_WTP_Cost_Legacy::map($a);}
    public static function stock_tax($a){self::permission(true);self::invalidate();GE_WTP_Operations::permission('stock');$id=absint($a['item_id']??0);$tax=$a['tax_treatment']??'';if(!in_array($tax,array('excluded','included_recoverable','included_nonrecoverable','exempt'),true))throw new RuntimeException('Tratamiento impositivo requerido.');$percent=GE_WTP_Cost_Math::number($a['tax_percent']??0,'IVA',0,100);return self::lock('stock:'.$id,function()use($id,$tax,$percent){return GE_WTP_Operations::transaction(function()use($id,$tax,$percent){global $wpdb;$table=GE_WTP_Operations::table('stock_items');$item=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id=%d FOR UPDATE",$id),ARRAY_A);if(!$item)throw new RuntimeException('Insumo inexistente.');$meta=json_decode($item['metadata']??'',true)?:array();$before=$meta;$meta['cost_tax_treatment']=$tax;$meta['cost_tax_percent']=$percent;if(false===$wpdb->update($table,array('metadata'=>wp_json_encode($meta)),array('id'=>$id)))throw new RuntimeException('No se pudo guardar impuestos.');self::audit('stock_tax',$id,$before,$meta);return array('item_id'=>$id,'tax_treatment'=>$tax,'tax_percent'=>$percent);});});}
    public static function recipes() { self::permission();global $wpdb; $rows=$wpdb->get_results('SELECT * FROM '.GE_WTP_Operations::table('recipes').' ORDER BY id DESC LIMIT 500',ARRAY_A);foreach($rows as &$row)$row['cost']=json_decode($row['cost_json']??'',true);return $rows; }
    public static function recipe($id){foreach(self::recipes() as $r)if((int)$r['id']===(int)$id)return $r;throw new RuntimeException('Receta inexistente.');}
    public static function recipe_save($a) {
        self::permission(true);$name=sanitize_text_field($a['name']??'');$lines=$a['lines']??array();if(!$name||!is_array($lines)||!$lines||count($lines)>50)throw new RuntimeException('Receta incompleta.');$clean=array();
        foreach($lines as $line){$source=self::source($line['source_ref']??'');$basis=$line['basis']??'output';if(!in_array($basis,array('output','job','sheet','area','meter','click','hours'),true))throw new RuntimeException('Base de receta inválida.');$units=array('sheet'=>'sheet','area'=>'m2','meter'=>'m','click'=>'click','hours'=>'hour');if(isset($units[$basis])&&$source['unit']!==$units[$basis])throw new RuntimeException('Unidad de receta distinta al insumo; agregá conversión explícita.');$group=$line['group']??'materials';if(!in_array($group,array('materials','process','supplier','labor','finishing','logistics','other'),true))throw new RuntimeException('Componente inválido.');$clean[]=array('source_ref'=>$source['ref'],'basis'=>$basis,'factor'=>GE_WTP_Cost_Math::number($line['factor']??1,'factor',0.000001),'outputs_per_sheet'=>GE_WTP_Cost_Math::number($line['outputs_per_sheet']??1,'rendimiento',0.000001),'group'=>$group,'waste'=>!empty($line['waste']),'optional_key'=>sanitize_key($line['optional_key']??''));}
        $defaults=$a['defaults']??array('currency'=>'ARS','quantity'=>1,'waste_percent'=>0);$rule=$a['price_rule']??array('mode'=>'markup','value'=>0);GE_WTP_Cost_Math::price(1,$rule);
        return GE_WTP_Operations::transaction(function()use($a,$name,$clean,$defaults,$rule){global $wpdb;$parent=absint($a['id']??0);if($parent)self::recipe($parent);$cost=array('lines'=>$clean,'defaults'=>$defaults,'price_rule'=>$rule,'actor_id'=>get_current_user_id(),'version_at'=>gmdate('c'));$legacy=$parent?self::recipe($parent)['lines_json']:'[]';if(false===$wpdb->insert(GE_WTP_Operations::table('recipes'),array('name'=>$name,'parent_id'=>$parent?:null,'lines_json'=>$legacy,'cost_json'=>wp_json_encode($cost),'updated_at'=>current_time('mysql',true))))throw new RuntimeException('No se pudo guardar receta.');$id=(int)$wpdb->insert_id;self::audit('recipe_version',$id,$parent?self::recipe($parent):null,$cost);return self::recipe($id);});
    }
    public static function calculate($a) {
        self::permission();$recipe=!empty($a['recipe_id'])?self::recipe(absint($a['recipe_id'])):null;$cost=$recipe['cost']??null;
        $input=array_merge($cost['defaults']??array(),$a['input']??array());$input+=array('quantity'=>1,'currency'=>'ARS','waste_percent'=>0,'faces'=>1);$qty=GE_WTP_Cost_Math::number($input['quantity'],'cantidad',0.000001,1000000);$waste=GE_WTP_Cost_Math::number($input['waste_percent'],'merma',0,1000);$lines=$cost['lines']??($a['lines']??array());$catalog=self::catalog();$sources=array_column($catalog,null,'ref');$parts=array();$missing=array();$groups=array_fill_keys(array('materials','process','supplier','labor','finishing','logistics','other','waste'),0);$total=0;
        if(!$lines&&$recipe){$estimate=GE_WTP_Operations_Equipment::recipe_estimate($recipe['id'],$qty,$input['faces'],(string)(1+$waste/100));foreach($estimate['lines'] as $r)$lines[]=array('source_ref'=>'stock/'.$r['material_id'].'/latest/'.$input['currency'],'basis'=>'job','factor'=>$r['quantity'],'group'=>'materials','waste'=>false);}
        if(!$lines||count($lines)>50)$missing[]='Faltan componentes de costo.';
        foreach($lines as $line){if(!empty($line['optional_key'])&&empty($input[$line['optional_key']]))continue;$ref=$line['source_ref']??'';$source=$sources[$ref]??null;$group=$line['group']??'materials';try{if(!$source)throw new RuntimeException('Fuente no disponible.');if(!isset($groups[$group])||$group==='waste')throw new RuntimeException('Componente inválido.');$units=array('sheet'=>'sheet','area'=>'m2','meter'=>'m','click'=>'click','hours'=>'hour');$basis=$line['basis']??'output';if(isset($units[$basis])&&$source['unit']!==$units[$basis])throw new RuntimeException('La base de cálculo no coincide con la unidad del costo.');$base=GE_WTP_Cost_Math::quantity($line,$input);$amount=GE_WTP_Cost_Math::line($source,$base,$input);$extra=!empty($line['waste'])?$amount*$waste/100:0;$total+=$amount+$extra;$groups[$group]+=$amount;$groups['waste']+=$extra;$parts[]=array('source'=>$source,'quantity'=>$base,'group'=>$group,'subtotal'=>$amount,'waste'=>round($extra,4));}catch(Throwable $e){$missing[]=$ref.': '.$e->getMessage();}}
        if(!$parts)$missing[]='No hay componentes activos para este cálculo.';if(!is_finite($total)||$total>1000000000000)throw new RuntimeException('Costo calculado fuera de rango.');
        $rule=$a['price_rule']??($cost['price_rule']??array('mode'=>'markup','value'=>0));$price=GE_WTP_Cost_Math::price($total,$rule);$complete=!$missing;
        return array('recipe_id'=>$recipe?(int)$recipe['id']:null,'recipe_hash'=>$recipe?self::hash($recipe):null,'input'=>$input,'components'=>$parts,'breakdown'=>$groups,'total_cost'=>round($total,4),'unit_cost'=>round($total/$qty,4),'currency'=>$input['currency'],'complete'=>$complete,'missing'=>$missing,'pricing'=>$complete?$price:null,'calculated_at'=>gmdate('c'),'fingerprint'=>self::hash(array($recipe,$input,$lines,$rule,$parts)));
    }
    public static function quote_snapshot($a){
        self::permission(true);$calculation=self::calculate($a['calculation']??array());if(!$calculation['complete']||$calculation['currency']!=='ARS')throw new RuntimeException('El presupuesto requiere costo completo en ARS.');
        $id=wp_insert_post(array('post_type'=>self::CHANGE,'post_status'=>'private','post_title'=>'Costo privado para presupuesto'),true);if(is_wp_error($id)||!$id)throw new RuntimeException('No se pudo guardar snapshot.');$data=array('kind'=>'quote_cost','calculation'=>$calculation,'created_by'=>get_current_user_id(),'created_at'=>gmdate('c'));self::put($id,'_ge_cost_change',$data);self::audit('quote_snapshot',$id,null,$data);return array('id'=>(int)$id,'calculation'=>$calculation);
    }
    public static function quote_costs($lines,$quote_id=0){self::permission();$allowed=array();if($quote_id){$quote=GE_WTP_Commercial_Quotes::get($quote_id,get_current_user_id());if(is_wp_error($quote))throw new RuntimeException('Presupuesto no autorizado.');foreach((array)get_post_meta($quote_id,'_ge_cost_quote_version_'.$quote['version'],true) as $entry)$allowed[]=absint($entry['snapshot_id']??0);}$out=array();foreach($lines as $index=>$line){$id=absint($line['cost_snapshot_id']??0);if(!$id)continue;$data=GE_WTP_Cost_Products::change($id);if(($data['kind']??'')!=='quote_cost'||((int)$data['created_by']!==get_current_user_id()&&!in_array($id,$allowed,true))||($line['source_type']??'')!=='custom'||(float)$data['calculation']['input']['quantity']!==(float)$line['quantity'])throw new RuntimeException('El costo privado no coincide con el ítem personalizado; recalculá.');$out[$index]=array('snapshot_id'=>$id,'calculation'=>$data['calculation']);}return $out;}
    public static function assist_packet($a){$list=self::list_get(absint($a['list_id']??0));$catalog=self::catalog(array('supplier_id'=>$list['supplier_id']));return array('project'=>'graph-express','specialists'=>array('finance','commercial'),'objective'=>'Interpretar lista de proveedor y proponer ítems/matches; nunca activar ni aplicar precios.','list_id'=>$list['id'],'checksum'=>$list['workspace']['file_hash']??'','extraction'=>$list['normalized']['extraction']??null,'items'=>$list['normalized']['items']??array(),'current_costs'=>$catalog,'comparison'=>self::compare($a),'data_is_untrusted'=>true,'allowed_effects'=>array('proposals_only'),'human_review_required'=>true);}
    public static function propose($a){self::permission(true);$id=absint($a['list_id']??0);return self::lock('list:'.$id,function()use($a,$id){$list=self::list_get($id);if(!in_array($list['normalized']['status'],array('draft','parsed'),true)||!empty($list['workspace']['active']))throw new RuntimeException('La lista vigente o revisada no admite propuestas.');$items=self::normalize($a['items']??array(),$list);$next=$list['normalized'];$next['status']='parsed';$next['proposal']=array('items'=>$items,'source'=>'ai-grupo','task_ref'=>sanitize_text_field($a['task_ref']??''),'created_at'=>gmdate('c'),'notes'=>sanitize_textarea_field($a['notes']??''));self::put($id,self::LIST_META,$next);self::audit('ai_proposal',$id,$list['normalized'],$next);return array('list_id'=>$id,'review_required'=>true,'review_url'=>GE_WTP_Cost_UI::url('lists',array('list_id'=>$id)));});}
    public static function actions() {return array('graph.supplier.price_list.parse'=>'parse','graph.supplier.price_list.compare'=>'compare','graph.supplier.price_list.review'=>'review','graph.supplier.price_list.activate'=>'activate','graph.cost.calculate'=>'calculate','graph.cost.recipe.create'=>'recipe_save','graph.cost.recipe.update'=>'recipe_save','graph.cost.catalog.get'=>'catalog','graph.cost.rate.create'=>'rate_save','graph.cost.stock_tax.update'=>'stock_tax','graph.cost.legacy_mapping.update'=>'legacy_map','graph.cost.quote_snapshot.create'=>'quote_snapshot','graph.cost.assist.get'=>'assist_packet','graph.supplier.price_list.propose'=>'propose');}
    public static function execute($action,$a) {
        self::permission();$writes=array_merge(array_keys(self::actions()),array('graph.supplier.price_list.upload','graph.product.create','graph.product.update','graph.product.cost_link','graph.product.price_preview','graph.product.bulk_preview','graph.product.rollback_preview','graph.cost.assist.request','graph.cost.assist.result'));$writes=array_diff($writes,array('graph.cost.calculate','graph.cost.catalog.get','graph.cost.assist.get','graph.supplier.price_list.compare'));
        if(in_array($action,$writes,true)&&!empty($a['idempotency_key'])){self::permission(true);$key=$a['idempotency_key'];if(!is_string($key)||!preg_match('/^[A-Za-z0-9:_-]{8,128}$/D',$key))throw new RuntimeException('Clave de idempotencia inválida.');$hash=self::hash(array($action,$a));return self::lock('action:'.$key,function()use($key,$hash,$action,$a){return GE_WTP_Operations::transaction(function()use($key,$hash,$action,$a){$prior=get_posts(array('post_type'=>self::CHANGE,'post_status'=>'private','fields'=>'ids','numberposts'=>1,'meta_key'=>'_ge_cost_action_key','meta_value'=>$key));if($prior){$r=get_post_meta($prior[0],'_ge_cost_action_result',true);if(($r['hash']??'')!==$hash)throw new RuntimeException('Clave reutilizada con otro contenido.');return $r['result'];}$result=self::dispatch($action,$a);$id=wp_insert_post(array('post_type'=>self::CHANGE,'post_status'=>'private','post_title'=>'Idempotency '.$action),true);if(is_wp_error($id)||!$id)throw new RuntimeException('No se pudo registrar idempotencia.');self::put($id,'_ge_cost_action_key',$key);self::put($id,'_ge_cost_action_result',array('hash'=>$hash,'result'=>$result,'actor_id'=>get_current_user_id()));return $result;});});}
        return self::dispatch($action,$a);
    }
    private static function dispatch($action,$a){if(strpos($action,'graph.cost.assist.')===0){$map=array('graph.cost.assist.request'=>'request','graph.cost.assist.pending'=>'pending','graph.cost.assist.get'=>'packet','graph.cost.assist.result'=>'result');if(isset($map[$action]))return call_user_func(array('GE_WTP_Cost_Assist',$map[$action]),$a);}if($action==='graph.cost.recipe.get')return self::recipe(absint($a['id']??0));if($action==='graph.supplier.price_list.upload')return self::upload($a);if($action==='graph.supplier.price_list.get')return self::list_get(absint($a['list_id']??0));if($action==='graph.supplier.price_list.find')return self::lists($a['supplier_id']??'');$map=self::actions();if(isset($map[$action]))return call_user_func(array(__CLASS__,$map[$action]),$a);return GE_WTP_Cost_Products::execute($action,$a);}
    public static function routes() { register_rest_route('ge/v1','/costs/(?P<action>[a-z_.]+)',array('methods'=>'POST','permission_callback'=>function(){return self::enabled()&&is_user_logged_in()&&(current_user_can('manage_options')||current_user_can('ge_view_costs'));},'callback'=>function($r){try{return rest_ensure_response(self::execute($r['action'],$r->get_json_params()?:array()));}catch(Throwable $e){return new WP_Error('ge_cost_error',$e->getMessage(),array('status'=>400));}})); }
}
