<?php
/** Operations finance: immutable accrual ledger and separately recorded cash. */
class GE_WTP_Operations_Finance {
    private static function eligible($o) { return !((class_exists('GE_WTP_Production') && !GE_WTP_Production::is_production_order($o)) || (class_exists('GE_WTP_Customer_Quotes') && GE_WTP_Customer_Quotes::is_quote_order($o)) || $o->get_meta('_ge_commercial_payment_order')==='yes' || in_array($o->get_status(),array('cancelled','failed','pending','draft','checkout-draft','ge-quote','quote','refunded'),true) || $o->get_meta('_ge_is_quote')==='yes' || $o->get_meta('_ge_quote_only')==='yes' || $o->get_meta('_ge_payment_order')==='yes'); }
    private static function supplier_spend($where,array $f) { global $wpdb; $totals=array();foreach(array('expense'=>'expenses','payable'=>'payables') as $type=>$table) { $rows=$wpdb->get_results('SELECT e.currency,e.amount_minor,cost.supplier_id,cost.order_id FROM '.self::t('finance_entries').' e LEFT JOIN '.self::t('finance_entries').' original ON original.id=e.reverses_id INNER JOIN '.self::t($table).' cost ON cost.id=COALESCE(original.source_id,e.source_id) WHERE COALESCE(original.entry_type,e.entry_type)='."'".$type."'".' AND '.$where,ARRAY_A);if($wpdb->last_error) self::fail('database_error','Supplier spend read failed.');foreach($rows as $r) { if(isset($f['customer_id'])) { $o=$r['order_id']&&function_exists('wc_get_order')?wc_get_order($r['order_id']):false;if(!$o||(int)$o->get_customer_id()!==absint($f['customer_id'])) continue; } $key=$r['currency'].'|'.$r['supplier_id'];if(!isset($totals[$key])) $totals[$key]=array('supplier_id'=>(int)$r['supplier_id'],'currency'=>$r['currency'],'purchases_minor'=>0,'expenses_minor'=>0,'total_minor'=>0);$field=$type==='expense'?'expenses_minor':'purchases_minor';$totals[$key][$field]+=(int)$r['amount_minor'];$totals[$key]['total_minor']+=(int)$r['amount_minor']; } } return array_values($totals); }
    public static function report(array $f=array()) {
        GE_WTP_Operations::permission('finance'); global $wpdb; list($from,$to)=self::period($f);
        $where=$wpdb->prepare('e.entry_date BETWEEN %s AND %s',$from,$to);
        foreach(array('supplier_id','order_id') as $field) if(isset($f[$field])) $where.=$wpdb->prepare(' AND cost.'.$field.'=%d',absint($f[$field]));
        if(!empty($f['category'])) $where.=$wpdb->prepare(' AND cost.category=%s',sanitize_key($f['category']));
        $rows=$wpdb->get_results('SELECT e.currency,e.amount_minor,e.entry_date,cost.category,cost.supplier_id,cost.order_id FROM '.self::t('finance_entries').' e LEFT JOIN '.self::t('finance_entries').' original ON original.id=e.reverses_id INNER JOIN '.self::t('expenses')." cost ON cost.id=COALESCE(original.source_id,e.source_id) WHERE COALESCE(original.entry_type,e.entry_type)='expense' AND ".$where,ARRAY_A);
        if($wpdb->last_error) self::fail('database_error','Expense report read failed.'); $groups=array('category'=>array(),'supplier'=>array(),'month'=>array());$overhead=array();
        foreach($rows as $r) { if(isset($f['customer_id'])) { $o=$r['order_id']&&function_exists('wc_get_order')?wc_get_order($r['order_id']):false; if(!$o || (int)$o->get_customer_id()!==absint($f['customer_id'])) continue; } foreach(array('category'=>$r['category'],'supplier'=>(string)$r['supplier_id'],'month'=>substr($r['entry_date'],0,7)) as $dim=>$value) { $key=$r['currency'].'|'.$value; if(!isset($groups[$dim][$key])) $groups[$dim][$key]=array('currency'=>$r['currency'],'group'=>$value,'amount_minor'=>0,'entry_count'=>0);$groups[$dim][$key]['amount_minor']+=(int)$r['amount_minor'];$groups[$dim][$key]['entry_count']++; } if(!(int)$r['order_id']) $overhead[$r['currency']]=($overhead[$r['currency']]??0)+(int)$r['amount_minor']; }
        foreach($groups as &$g) $g=array_values($g);unset($g);$currencies=array();$order_count=0;
        if(function_exists('wc_get_orders')) { $page=1; do { $args=array('type'=>'shop_order','date_created'=>$from.'...'.$to,'limit'=>100,'page'=>$page,'paginate'=>true,'orderby'=>'ID','order'=>'ASC');if(isset($f['customer_id'])) $args['customer_id']=absint($f['customer_id']);if(isset($f['order_id'])) $args['include']=array(absint($f['order_id']));$batch=wc_get_orders($args); foreach($batch->orders as $o) { if(!self::eligible($o)) continue; if(isset($f['order_id']) && $o->get_id()!==absint($f['order_id'])) continue; if(isset($f['customer_id']) && (int)$o->get_customer_id()!==absint($f['customer_id'])) continue; if(isset($f['supplier_id'])||!empty($f['category'])) { $match=$wpdb->prepare('order_id=%d',$o->get_id());if(isset($f['supplier_id'])) $match.=$wpdb->prepare(' AND supplier_id=%d',absint($f['supplier_id']));if(!empty($f['category'])) $match.=$wpdb->prepare(' AND category=%s',sanitize_key($f['category']));if(!$wpdb->get_var('SELECT id FROM '.self::t('expenses').' WHERE '.$match.' LIMIT 1') && !$wpdb->get_var('SELECT id FROM '.self::t('payables').' WHERE '.$match.' LIMIT 1')) continue; } $c=self::currency($o->get_currency()); if(!isset($currencies[$c])) $currencies[$c]=array('currency'=>$c,'sold_minor'=>0,'complete_count'=>0,'incomplete_count'=>0,'complete_margin_minor'=>null,'known_order_costs_minor'=>0);$r=&$currencies[$c];$order_count++;$refund=0;foreach($o->get_refunds() as $refund_order) $refund+=self::decimal_minor($refund_order->get_amount());$r['sold_minor']+=self::decimal_minor($o->get_total())-$refund;$m=self::order_margin($o->get_id());$known=0;foreach($m['recorded_costs'] as $cost) if($cost['currency']===$c) $known+=(int)$cost['costs_minor'];if($m['stock_material_costs']['movement_count']) $known+=$m['stock_material_costs']['known_minor']-$m['manual_materials_minor'];$known+=$m['legacy_supplier_costs']['known_minor'];$r['known_order_costs_minor']+=$known;if($m['margin_minor']===null) $r['incomplete_count']++;else { $r['complete_count']++;$r['complete_margin_minor']=($r['complete_margin_minor']??0)+$m['margin_minor']; } unset($r); }$page++; }while($page<=(int)$batch->max_num_pages); }
        foreach($overhead as $c=>$amount) if(!isset($currencies[$c])) $currencies[$c]=array('currency'=>$c,'sold_minor'=>0,'complete_count'=>0,'incomplete_count'=>0,'complete_margin_minor'=>null,'known_order_costs_minor'=>0);
        foreach($currencies as &$r) { $r['overhead_minor']=$overhead[$r['currency']]??0;$r['operating_estimate_minor']=$r['incomplete_count']>0?null:($r['sold_minor']-$r['known_order_costs_minor']-$r['overhead_minor']); }unset($r);
        return array('from'=>$from,'to'=>$to,'filters'=>$f,'expense_groups'=>$groups,'supplier_spend'=>self::supplier_spend($where,$f),'supplier_spend_basis'=>'Net payable acquisition recognition plus expense recognition, including dated reversals; currencies remain separate; purchases are not automatically overhead','expense_basis'=>'Immutable expense recognition and reversal dates; excludes acquisition obligations','margins'=>array('currencies'=>array_values($currencies),'order_count'=>$order_count,'basis'=>'Eligible orders created in period; supplier/category select order cohort, margin uses full order costs'),'operating_estimate'=>array('status'=>'partial_cost_coverage','label'=>'Estimación operativa con cobertura parcial de costos','basis'=>'Only complete order cohorts: net sold minus known same-currency order costs and period overhead; unavailable while any order cost is incomplete; not reconciled profit'),'accounts_receivable'=>array('status'=>'unknown','outstanding_minor'=>null,'source'=>'GE_WTP_Payments','reason'=>'Current source stores latest confirmed snapshot, not authoritative cumulative payments or outstanding balance'));
    }
    private static function decimal_minor($value) { $s=(string)$value; if(!preg_match('/^(-?)([0-9]{1,13})(?:\.([0-9]{0,2}))?$/D',$s,$m)) self::fail('unsupported_precision','Money must have at most two decimal places.'); return ($m[1]==='-'?-1:1)*((int)$m[2]*100+(int)str_pad($m[3]??'',2,'0')); }
    private static function sold($from,$to) {
        if(!function_exists('wc_get_orders')) return array('status'=>'unavailable','currencies'=>array());
        $totals=array(); $page=1;
        do { $batch=wc_get_orders(array('type'=>'shop_order','date_created'=>$from.'...'.$to,'limit'=>100,'page'=>$page,'paginate'=>true,'orderby'=>'ID','order'=>'ASC')); foreach($batch->orders as $o) {
            if(!self::eligible($o)) continue;
            $c=self::currency($o->get_currency()); if(!isset($totals[$c])) $totals[$c]=array('currency'=>$c,'sold_minor'=>0,'order_count'=>0);
            $refund=0; foreach($o->get_refunds() as $r) $refund+=self::decimal_minor($r->get_amount());
            $totals[$c]['sold_minor']+=self::decimal_minor($o->get_total())-$refund; $totals[$c]['order_count']++;
        } $page++; } while($page<=(int)$batch->max_num_pages);
        return array('status'=>'available','label'=>'Vendido neto de devoluciones','basis'=>'order_created_date','currencies'=>array_values($totals));
    }
    private static function collected($from,$to) { if(!function_exists('wc_get_orders')) return array('status'=>'unavailable','currencies'=>array()); $totals=array(); $page=1; do { $batch=wc_get_orders(array('type'=>'shop_order','limit'=>100,'page'=>$page,'paginate'=>true,'orderby'=>'ID','order'=>'ASC')); foreach($batch->orders as $o) { $at=(string)$o->get_meta('_ge_payment_confirmed_at'); $amount=$o->get_meta('_ge_payment_confirmed_total'); if(!$at || $amount==='' || substr($at,0,10)<$from || substr($at,0,10)>$to) continue; $c=self::currency($o->get_currency()); if(!isset($totals[$c])) $totals[$c]=array('currency'=>$c,'confirmed_minor'=>0,'record_count'=>0); $totals[$c]['confirmed_minor']+=self::decimal_minor($amount); $totals[$c]['record_count']++; } $page++; } while($page<=(int)$batch->max_num_pages); return array('status'=>$totals?'recorded_partial':'unavailable','source'=>'GE_WTP_Payments confirmed_at + confirmed_total','coverage'=>'Latest confirmed snapshot only; historical installments and refund cash unavailable','currencies'=>array_values($totals)); }
    public static function costs_complete(array $a) { GE_WTP_Operations::permission('finance_write'); $id=absint($a['order_id']??0); $o=function_exists('wc_get_order')?wc_get_order($id):false; if(!$o) self::fail('not_found','Order not found.'); $reason=sanitize_textarea_field($a['reason']??''); if(!$reason) self::fail('reason_required','Cost verification reason required.'); $complete=($a['complete']??false)===true; return GE_WTP_Operations::transaction(function() use($id,$o,$reason,$complete) { $o->update_meta_data('_ge_operations_costs_complete',$complete?'yes':'no'); $o->update_meta_data('_ge_operations_costs_verified_by',get_current_user_id()); $o->update_meta_data('_ge_operations_costs_verified_at',current_time('mysql',true)); if(!$o->save()) self::fail('database_error','Cost verification save failed.'); GE_WTP_Operations::audit('costs_verified',$id,array('complete'=>$complete,'reason'=>$reason,'actor_id'=>get_current_user_id())); return array('order_id'=>$id,'costs_complete'=>$complete); }); }
    public static function order_cost_save(array $a) { GE_WTP_Operations::permission('finance_write'); $id=absint($a['order_id']??0); if(!$id || !function_exists('wc_get_order') || !wc_get_order($id)) self::fail('not_found','Order not found.'); $a['category']=$a['category']??'job_cost'; return self::expense_create($a); }
    public static function supplier_work_cost_create(array $a) { GE_WTP_Operations::permission('finance_write');$order=absint($a['order_id']??0);$supplier=absint($a['supplier_id']??0);$o=function_exists('wc_get_order')?wc_get_order($order):false;if(!$o||!self::eligible($o)) self::fail('invalid_order','A real eligible order is required.');if(!$supplier||!GE_WTP_Operations::supplier_exists($supplier)) self::fail('invalid_supplier','Supplier does not exist.');$key=trim((string)($a['idempotency_key']??''));if(!$key||strlen($key)>120) self::fail('invalid_idempotency','Supplier work key required.');$data=array('order_id'=>$order,'supplier_id'=>$supplier,'amount_minor'=>self::money($a['amount_minor']??null),'currency'=>self::currency($a['currency']??''),'incurred_on'=>self::day($a['incurred_on']??''),'due_on'=>empty($a['due_on']??($a['due_date']??null))?null:self::day($a['due_on']??$a['due_date']),'description'=>sanitize_textarea_field($a['description']??'Trabajo de proveedor'),'category'=>'supplier_work','source_type'=>'supplier_work','source_ref'=>'order:'.$order.':supplier:'.$supplier,'attachments'=>array_map('absint',$a['attachments']??array()));$fp=hash('sha256',wp_json_encode($data));return GE_WTP_Operations::transaction(function() use($data,$key,$fp){global $wpdb;self::claim('supplier_work',$key,$fp);self::claim('supplier_source',$data['source_ref'],$fp);$existing=$wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::t('payables')." WHERE source_type='supplier_work' AND source_ref=%s FOR UPDATE",$data['source_ref']));if($existing)return array('id'=>(int)$existing,'replayed'=>true);$r=self::payable_create($data);$r['replayed']=false;return $r;}); }
    private static function legacy_costs($order) { global $wpdb;$details=array();$sum=0;$unknown=false;$ambiguous=false;$stored=$order->get_meta('_ge_supplier_payables',true);if($stored===''||$stored===null||$stored===false) $stored=array();if(!is_array($stored)) return array('details'=>array(),'known_minor'=>0,'currency'=>$order->get_currency(),'status'=>'unknown_legacy_cost','complete'=>false);foreach($stored as $key=>$record) { $amount=null;$currency=strtoupper((string)($record['currency']??'ARS'));try { if(!isset($record['amount'])||$record['amount']==='') throw new RuntimeException('Unknown legacy cost');$amount=self::decimal_minor($record['amount']);if($amount<0||!preg_match('/^[A-Z]{3}$/D',$currency)) throw new RuntimeException('Invalid legacy cost'); }catch(Throwable $e){$amount=null;$unknown=true;}$supplier=(int)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::t('supplier_refs').' WHERE supplier_key=%s',(string)$key));$overlap=false;if($amount!==null && $amount>0) { $expense_ids=$wpdb->get_col($wpdb->prepare('SELECT id FROM '.self::t('expenses')." WHERE order_id=%d AND (category IN ('job_cost','supplier_work','outsourcing') OR (%d>0 AND supplier_id=%d))",$order->get_id(),$supplier,$supplier));foreach($expense_ids as $id) if(self::net_source('expense',$id)>0)$overlap=true;$payable_ids=$wpdb->get_col($wpdb->prepare('SELECT id FROM '.self::t('payables')." WHERE order_id=%d AND expense_id IS NULL AND (source_type='legacy_supplier_cost' OR (%d>0 AND supplier_id=%d))",$order->get_id(),$supplier,$supplier));foreach($payable_ids as $id) if(self::obligation($id)>0)$overlap=true; }$ambiguous=$ambiguous||$overlap;if($currency!==$order->get_currency())$unknown=true;if($amount!==null&&!$overlap&&$currency===$order->get_currency())$sum+=$amount;$details[]=array('supplier_key'=>(string)$key,'supplier_id'=>$supplier,'amount_minor'=>$amount,'currency'=>$currency,'overlap'=>$overlap,'source'=>'WooCommerce _ge_supplier_payables read only');}return array('details'=>$details,'known_minor'=>$sum,'currency'=>$order->get_currency(),'status'=>$ambiguous?'ambiguous_overlap':($unknown?'unknown_legacy_cost':($details?'known_readonly':'none')),'complete'=>!$unknown&&!$ambiguous); }
    private static function t($key) { return GE_WTP_Operations::table($key); }
    private static function scale4($value) { if(!preg_match('/^([0-9]{1,10})(?:\.([0-9]{0,4}))?$/D',(string)$value,$m)) return null; return (int)$m[1]*10000+(int)str_pad($m[2]??'',4,'0'); }
    private static function manual_materials($order) { global $wpdb; return (int)$wpdb->get_var($wpdb->prepare('SELECT COALESCE(SUM(e.amount_minor),0) FROM '.self::t('finance_entries').' e LEFT JOIN '.self::t('finance_entries').' x ON x.id=e.reverses_id INNER JOIN '.self::t('expenses')." cost ON cost.id=COALESCE(x.source_id,e.source_id) AND cost.category='materials' WHERE e.order_id=%d AND e.currency=%s AND COALESCE(x.entry_type,e.entry_type)='expense'",$order->get_id(),$order->get_currency())); }
    private static function material_costs($order) { global $wpdb; $rows=$wpdb->get_results($wpdb->prepare('SELECT id,movement_type,quantity,unit_cost,currency FROM '.self::t('stock_moves')." WHERE order_id=%d AND movement_type IN ('consumption','consume_reserved','waste','writeoff','return_in')",$order->get_id()),ARRAY_A); if($wpdb->last_error) self::fail('database_error','Material cost read failed.'); $sum=0;$unknown=array(); foreach($rows as $r) { $q=self::scale4($r['quantity']);$c=self::scale4($r['unit_cost']); if($q===null||$c===null||$r['currency']!==$order->get_currency()||($q>0 && $c>intdiv(PHP_INT_MAX-500000,$q))) { $unknown[]=(int)$r['id']; continue; } $sum+=($r['movement_type']==='return_in'?-1:1)*intdiv($q*$c+500000,1000000); } return array('movement_count'=>count($rows),'known_minor'=>$sum,'currency'=>$order->get_currency(),'complete'=>!$unknown,'unknown_movement_ids'=>$unknown); }
    public static function income_record(array $a) { GE_WTP_Operations::permission('finance_write'); $amount=self::money($a['amount_minor']??null);$currency=self::currency($a['currency']??'');$date=self::day($a['received_on']??($a['entry_date']??''));$key=trim((string)($a['idempotency_key']??''));$type=$a['type']??'income'; if(!$key||strlen($key)>120||!in_array($type,array('income','refund'),true)) self::fail('invalid_income','Income type and idempotency key required.'); $data=array('amount_minor'=>$amount,'currency'=>$currency,'received_on'=>$date,'entry_type'=>$type,'order_id'=>absint($a['order_id']??0),'customer_ref'=>sanitize_text_field($a['customer_ref']??''),'method'=>sanitize_key($a['method']??''),'reference'=>sanitize_text_field($a['reference']??''),'attachments'=>wp_json_encode(array('ids'=>array_map('absint',$a['attachments']??array()),'private_ref'=>sanitize_text_field($a['attachment_ref']??'')))); if($data['order_id'] && (!function_exists('wc_get_order')||!wc_get_order($data['order_id']))) self::fail('not_found','Order not found.'); $fp=hash('sha256',wp_json_encode($data));return GE_WTP_Operations::transaction(function() use($data,$fp,$key,$type,$amount,$currency,$date) { global $wpdb;self::claim('income',$key,$fp);$existing=$wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::t('finance_income').' WHERE idempotency_key=%s FOR UPDATE',$key)); if($existing) return array('id'=>(int)$existing,'replayed'=>true);$id=self::insert('finance_income',array_merge($data,array('idempotency_key'=>$key,'fingerprint'=>$fp,'created_at'=>current_time('mysql',true))));self::ledger($type,$id,$type==='refund'?-$amount:$amount,$currency,$date,$data['order_id']);GE_WTP_Operations::audit('income_recorded',$id,array('type'=>$type,'amount_minor'=>$amount,'currency'=>$currency,'order_id'=>$data['order_id']));return array('id'=>$id,'replayed'=>false); }); }
    private static function claim($scope,$key,$fingerprint) { global $wpdb; if(false===$wpdb->query($wpdb->prepare('INSERT IGNORE INTO '.self::t('finance_idempotency').' (request_key,fingerprint) VALUES (%s,%s)',$scope.':'.$key,$fingerprint))) self::fail('database_error','Idempotency lock failed.'); $row=$wpdb->get_row($wpdb->prepare('SELECT fingerprint FROM '.self::t('finance_idempotency').' WHERE request_key=%s FOR UPDATE',$scope.':'.$key),ARRAY_A); if(!$row) self::fail('database_error','Idempotency lock unavailable.'); if($row['fingerprint']!==$fingerprint) self::fail('idempotency_conflict','Key already used with a different request.'); }
    private static function obligation($id) { global $wpdb; $expense=(int)$wpdb->get_var($wpdb->prepare('SELECT expense_id FROM '.self::t('payables').' WHERE id=%d',$id)); return $expense?self::net_source('expense',$expense):self::net_source('payable',$id); }
    private static function expense_obligation($id,$a,$amount,$currency,$date) { $state=$a['payment_state']??'unpaid'; if(!in_array($state,array('unpaid','paid'),true)) self::fail('invalid_state','Expense payment state must be unpaid or paid.'); $pid=self::insert('payables',array('expense_id'=>$id,'supplier_id'=>absint($a['supplier_id']??0),'source_type'=>'expense','source_ref'=>'expense:'.$id,'order_id'=>absint($a['order_id']??0),'amount_minor'=>$amount,'currency'=>$currency,'incurred_on'=>$date,'due_on'=>empty($a['due_date'])?null:self::day($a['due_date']),'description'=>sanitize_textarea_field($a['description']??''),'category'=>sanitize_key($a['category']??''),'attachments'=>wp_json_encode(array('ids'=>array_map('absint',$a['attachments']??array()),'private_ref'=>sanitize_text_field($a['attachment_ref']??''))),'created_at'=>current_time('mysql',true))); if($state==='paid') self::payment_record(array('payable_id'=>$pid,'amount_minor'=>$amount,'currency'=>$currency,'paid_on'=>self::day($a['paid_on']??$date),'method'=>$a['method']??'','reference'=>$a['reference']??'','idempotency_key'=>'expense-paid:'.$id)); return $pid; }
    private static function margin_value($order,$costs) { $materials=self::material_costs($order); $legacy=self::legacy_costs($order); if(!$materials['complete']||!$legacy['complete']) return null; if($order->get_meta('_ge_operations_costs_complete')!=='yes') return null; $sum=0; foreach($costs as $c) { if($c['currency']!==$order->get_currency()) return null; $sum+=(int)$c['costs_minor']; } $refund=0; foreach($order->get_refunds() as $r) $refund+=self::decimal_minor($r->get_amount()); if($materials['movement_count']) $sum+=$materials['known_minor']-self::manual_materials($order); $sum+=$legacy['known_minor']; return self::decimal_minor($order->get_total())-$refund-$sum; }
    private static function fail($code, $message) { GE_WTP_Operations::error($code, $message); }
    private static function money($value) {
        if (!(is_int($value) || (is_string($value) && preg_match('/^[0-9]+$/D', $value))) || strlen((string)$value) > 15 || (int)$value < 1) self::fail('invalid_amount', 'Amount must be positive integer minor units.');
        return (int)$value;
    }
    private static function currency($value) { $value = strtoupper((string)$value); if (!preg_match('/^[A-Z]{3}$/D', $value)) self::fail('invalid_currency', 'Use a three-letter currency.'); return $value; }
    private static function day($value) { $d = DateTimeImmutable::createFromFormat('!Y-m-d', (string)$value); if (!$d || $d->format('Y-m-d') !== $value) self::fail('invalid_date', 'Use a valid YYYY-MM-DD date.'); return $value; }
    private static function insert($table, $data) { global $wpdb; if ($wpdb->insert(self::t($table), $data) === false) self::fail('database_error', 'Finance write failed.'); return (int)$wpdb->insert_id; }
    private static function ledger($type, $id, $amount, $currency, $date, $order = 0, $reverse = null) { if($order && in_array($type,array('expense','payable','reversal'),true) && function_exists('wc_get_order')) { $o=wc_get_order($order); if($o) { $o->update_meta_data('_ge_operations_costs_complete','no'); if(!$o->save()) self::fail('database_error','Cost completeness invalidation failed.'); } } return self::insert('finance_entries', array('entry_type'=>$type,'source_id'=>$id,'amount_minor'=>$amount,'currency'=>$currency,'entry_date'=>$date,'order_id'=>$order,'reverses_id'=>$reverse,'created_at'=>current_time('mysql', true))); }
    public static function schema() {
        global $wpdb; $c = $wpdb->get_charset_collate(); $sql = array();
        $sql[]='CREATE TABLE '.self::t('finance_idempotency')." (request_key varchar(150) NOT NULL, fingerprint char(64) NOT NULL, PRIMARY KEY  (request_key)) ENGINE=InnoDB $c;";
        $sql[]='CREATE TABLE '.self::t('finance_income')." (id bigint unsigned NOT NULL AUTO_INCREMENT, amount_minor bigint NOT NULL, currency char(3) NOT NULL, received_on date NOT NULL, entry_type varchar(20) NOT NULL, order_id bigint unsigned NOT NULL DEFAULT 0, customer_ref varchar(190) NOT NULL, method varchar(60) NOT NULL, reference varchar(190) NOT NULL, attachments longtext DEFAULT NULL, idempotency_key varchar(120) NOT NULL, fingerprint char(64) NOT NULL, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key)) ENGINE=InnoDB $c;";
        $sql[] = 'CREATE TABLE '.self::t('payables')." (id bigint unsigned NOT NULL AUTO_INCREMENT, supplier_id bigint unsigned NOT NULL, expense_id bigint unsigned DEFAULT NULL, source_type varchar(40) NOT NULL, source_ref varchar(120) NOT NULL, order_id bigint unsigned NOT NULL DEFAULT 0, amount_minor bigint NOT NULL, currency char(3) NOT NULL, incurred_on date NOT NULL, due_on date DEFAULT NULL, description text NOT NULL, category varchar(60) NOT NULL DEFAULT '', attachments longtext DEFAULT NULL, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY source (source_type,source_ref), UNIQUE KEY expense_id (expense_id), KEY order_id (order_id)) ENGINE=InnoDB $c;";
        $sql[] = 'CREATE TABLE '.self::t('expenses')." (id bigint unsigned NOT NULL AUTO_INCREMENT, description text NOT NULL, amount_minor bigint NOT NULL, currency char(3) NOT NULL, incurred_on date NOT NULL, order_id bigint unsigned NOT NULL DEFAULT 0, recurrence varchar(20) DEFAULT NULL, supplier_id bigint unsigned NOT NULL DEFAULT 0, due_on date DEFAULT NULL, category varchar(60) NOT NULL DEFAULT '', attachments longtext DEFAULT NULL, idempotency_key varchar(120) DEFAULT NULL, fingerprint char(64) DEFAULT NULL, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key)) ENGINE=InnoDB $c;";
        $sql[] = 'CREATE TABLE '.self::t('finance_payments')." (id bigint unsigned NOT NULL AUTO_INCREMENT, payable_id bigint unsigned NOT NULL, amount_minor bigint NOT NULL, currency char(3) NOT NULL, paid_on date NOT NULL, reference varchar(190) NOT NULL, method varchar(60) NOT NULL DEFAULT '', attachments longtext DEFAULT NULL, idempotency_key varchar(120) NOT NULL, fingerprint char(64) NOT NULL, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY payable_id (payable_id)) ENGINE=InnoDB $c;";
        $sql[] = 'CREATE TABLE '.self::t('finance_entries')." (id bigint unsigned NOT NULL AUTO_INCREMENT, entry_type varchar(30) NOT NULL, source_id bigint unsigned NOT NULL, amount_minor bigint NOT NULL, currency char(3) NOT NULL, entry_date date NOT NULL, order_id bigint unsigned NOT NULL DEFAULT 0, reverses_id bigint unsigned DEFAULT NULL, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY reverses_id (reverses_id), KEY period (currency,entry_date), KEY order_id (order_id), KEY source (entry_type,source_id)) ENGINE=InnoDB $c;";
        return $sql;
    }
    public static function expense_create(array $a) {
        GE_WTP_Operations::permission('finance_write'); $amount=self::money($a['amount_minor']??null); $currency=self::currency($a['currency']??''); $date=self::day($a['incurred_on']??''); $rec=empty($a['recurrence'])?null:$a['recurrence']; if(!isset($a['due_date']) && isset($a['due_on'])) $a['due_date']=$a['due_on']; if(!empty($a['supplier_id']) && !GE_WTP_Operations::supplier_exists(absint($a['supplier_id']))) self::fail('invalid_supplier','Supplier does not exist.');
        if ($rec !== null && !in_array($rec,array('weekly','monthly','yearly'),true)) self::fail('invalid_recurrence','Invalid recurrence.');
        return GE_WTP_Operations::transaction(function() use($a,$amount,$currency,$date,$rec) { global $wpdb; $key=isset($a['idempotency_key'])?trim((string)$a['idempotency_key']):null; if($key!==null && (!$key || strlen($key)>120)) self::fail('invalid_idempotency','Invalid expense key.'); $fingerprint=hash('sha256',wp_json_encode(array($amount,$currency,$date,$rec,sanitize_textarea_field($a['description']??''),absint($a['order_id']??0),absint($a['supplier_id']??0),sanitize_key($a['category']??''),$a['due_date']??null,$a['attachments']??array(),$a['attachment_ref']??'',$a['payment_state']??'unpaid',$a['paid_on']??null,$a['method']??'',$a['reference']??''))); if($key!==null) { self::claim('expense',$key,$fingerprint); $existing=$wpdb->get_row($wpdb->prepare('SELECT id,fingerprint FROM '.self::t('expenses').' WHERE idempotency_key=%s FOR UPDATE',$key),ARRAY_A); if($existing) { if($existing['fingerprint']!==$fingerprint) self::fail('idempotency_conflict','Expense key payload differs.'); return array('id'=>(int)$existing['id'],'payable_id'=>(int)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::t('payables').' WHERE expense_id=%d',$existing['id'])),'replayed'=>true); } } $id=self::insert('expenses',array('idempotency_key'=>$key,'fingerprint'=>$fingerprint,'description'=>sanitize_textarea_field($a['description']??''),'category'=>sanitize_key($a['category']??''),'supplier_id'=>absint($a['supplier_id']??0),'due_on'=>empty($a['due_date'])?null:self::day($a['due_date']),'attachments'=>wp_json_encode(array_map('absint',$a['attachments']??array())),'amount_minor'=>$amount,'currency'=>$currency,'incurred_on'=>$date,'order_id'=>absint($a['order_id']??0),'recurrence'=>$rec,'created_at'=>current_time('mysql',true))); self::ledger('expense',$id,$amount,$currency,$date,absint($a['order_id']??0)); $payable=self::expense_obligation($id,$a,$amount,$currency,$date); GE_WTP_Operations::audit('expense_created',$id,array('amount_minor'=>$amount,'currency'=>$currency,'payable_id'=>$payable)); return array('id'=>$id,'payable_id'=>$payable,'replayed'=>false); });
    }
    public static function payable_create(array $a) {
        // Receipt service aliases; source_ref remains the canonical deduplication key.
        if (!isset($a['amount_minor']) && isset($a['total_minor'])) $a['amount_minor']=$a['total_minor'];
        if (!isset($a['source_ref']) && isset($a['source_id'])) $a['source_ref']=$a['source_id'];
        if (!isset($a['due_on']) && isset($a['due_date'])) $a['due_on']=$a['due_date'];
        if (!isset($a['incurred_on']) && isset($a['received_on'])) $a['incurred_on']=$a['received_on'];
        GE_WTP_Operations::permission('finance_write'); $amount=self::money($a['amount_minor']??null); $currency=self::currency($a['currency']??''); $date=self::day($a['incurred_on']??''); $due=empty($a['due_on'])?null:self::day($a['due_on']); $supplier=absint($a['supplier_id']??0);
        if (!$supplier || !GE_WTP_Operations::supplier_exists($supplier)) self::fail('invalid_supplier','Supplier does not exist.');
        $type=sanitize_key($a['source_type']??''); $ref=trim((string)($a['source_ref']??'')); if (!$type || strlen($type)>40 || !$ref || strlen($ref)>120) self::fail('invalid_source','A valid unique source is required.');
        return GE_WTP_Operations::transaction(function() use($a,$amount,$currency,$date,$due,$supplier,$type,$ref) { $id=self::insert('payables',array('supplier_id'=>$supplier,'source_type'=>$type,'source_ref'=>$ref,'order_id'=>absint($a['order_id']??0),'amount_minor'=>$amount,'currency'=>$currency,'incurred_on'=>$date,'due_on'=>$due,'description'=>sanitize_textarea_field($a['description']??''),'category'=>sanitize_key($a['category']??''),'attachments'=>wp_json_encode(array_map('absint',$a['attachments']??array())),'created_at'=>current_time('mysql',true))); self::ledger('payable',$id,$amount,$currency,$date,absint($a['order_id']??0)); GE_WTP_Operations::audit('payable_created',$id,array('source_type'=>$type,'source_ref'=>$ref)); return array('id'=>$id); });
    }
    public static function payment_record(array $a) {
        GE_WTP_Operations::permission('finance_write'); $amount=self::money($a['amount_minor']??null); $currency=self::currency($a['currency']??''); $date=self::day($a['paid_on']??''); $pid=absint($a['payable_id']??0); $key=trim((string)($a['idempotency_key']??'')); $ref=sanitize_text_field($a['reference']??'');
        if (!$pid || !$key || strlen($key)>120 || strlen($ref)>190) self::fail('invalid_payment','Payable and idempotency key are required.');
        $method=sanitize_key($a['method']??''); $attachments=wp_json_encode(array_map('absint',$a['attachments']??array())); $fp=hash('sha256',wp_json_encode(array($pid,$amount,$currency,$date,$ref,$method,$attachments)));
        return GE_WTP_Operations::transaction(function() use($pid,$amount,$currency,$date,$key,$ref,$fp,$method,$attachments) { global $wpdb; $p=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::t('payables').' WHERE id=%d FOR UPDATE',$pid),ARRAY_A); if (!$p) self::fail('not_found','Payable not found.'); self::claim('payment',$key,$fp); $existing=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::t('finance_payments').' WHERE idempotency_key=%s FOR UPDATE',$key),ARRAY_A); if ($existing) { if ($existing['fingerprint']!==$fp) self::fail('idempotency_conflict','Key already used with a different payment.'); return array('id'=>(int)$existing['id'],'replayed'=>true); } if ($p['currency']!==$currency) self::fail('currency_mismatch','Payment currency differs from obligation.'); $recognized=self::obligation($pid); $paid=self::paid($pid); if ($recognized<=0 || $amount>$recognized-$paid) self::fail('overpayment','Payment exceeds outstanding amount.'); $id=self::insert('finance_payments',array('payable_id'=>$pid,'amount_minor'=>$amount,'currency'=>$currency,'paid_on'=>$date,'reference'=>$ref,'method'=>$method,'attachments'=>$attachments,'idempotency_key'=>$key,'fingerprint'=>$fp,'created_at'=>current_time('mysql',true))); self::ledger('payment',$id,$amount,$currency,$date,(int)$p['order_id']); GE_WTP_Operations::audit('payment_recorded',$id,array('payable_id'=>$pid,'amount_minor'=>$amount,'currency'=>$currency)); return array('id'=>$id,'replayed'=>false); });
    }
    private static function net_source($type,$id) { global $wpdb; $amounts=$wpdb->get_col($wpdb->prepare('SELECT e.amount_minor FROM '.self::t('finance_entries').' e LEFT JOIN '.self::t('finance_entries').' original ON original.id=e.reverses_id WHERE (e.entry_type=%s AND e.source_id=%d) OR (original.entry_type=%s AND original.source_id=%d) FOR UPDATE',$type,$id,$type,$id)); if($wpdb->last_error) self::fail('database_error','Ledger balance read failed.'); return array_sum(array_map('intval',$amounts)); }
    private static function paid($pid) { global $wpdb; $ids=$wpdb->get_col($wpdb->prepare('SELECT id FROM '.self::t('finance_payments').' WHERE payable_id=%d FOR UPDATE',$pid)); $total=0; foreach($ids as $id) $total+=self::net_source('payment',$id); return $total; }
    private static function period(array $f) { $now=current_time('Y-m-d'); if(isset($f['year']) && !isset($f['month'])) { $from=self::day(sprintf('%04d-01-01',(int)$f['year'])); $to=self::day(sprintf('%04d-12-31',(int)$f['year'])); } elseif(isset($f['month'])||isset($f['year'])) { $y=(int)($f['year']??substr($now,0,4)); $m=(int)($f['month']??substr($now,5,2)); $from=self::day(sprintf('%04d-%02d-01',$y,$m)); $to=(new DateTimeImmutable($from))->format('Y-m-t'); } else { $from=self::day($f['from']??substr($now,0,7).'-01'); $to=self::day($f['to']??$now); } if($from>$to) self::fail('invalid_period','Start must precede end.'); return array($from,$to); }
    private static function list_where(array $f,$date,$default_period=true) { global $wpdb; $where='1=1'; if($default_period || array_intersect(array('from','to','month','year'),array_keys($f))) { list($from,$to)=self::period($f); $where.=$wpdb->prepare(' AND '.$date.' BETWEEN %s AND %s',$from,$to); } foreach(array('supplier_id','order_id') as $key) if(isset($f[$key])) $where.=$wpdb->prepare(' AND '.$key.'=%d',absint($f[$key])); if(!empty($f['category'])) $where.=$wpdb->prepare(' AND category=%s',sanitize_key($f['category'])); if(!empty($f['due_from'])) $where.=$wpdb->prepare(' AND due_on >= %s',self::day($f['due_from'])); if(!empty($f['due_to'])) $where.=$wpdb->prepare(' AND due_on <= %s',self::day($f['due_to'])); return $where; }
    public static function expense_list(array $f=array()) { GE_WTP_Operations::permission('finance'); global $wpdb; $rows=$wpdb->get_results('SELECT * FROM '.self::t('expenses').' WHERE '.self::list_where($f,'incurred_on').' ORDER BY incurred_on DESC,id DESC',ARRAY_A); $out=array(); foreach($rows as $r) { $pid=(int)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::t('payables').' WHERE expense_id=%d',$r['id'])); $r['payable_id']=$pid; $r['recognized_minor']=self::net_source('expense',$r['id']); $r['paid_minor']=$pid?self::paid($pid):0; $r['outstanding_minor']=$r['recognized_minor']-$r['paid_minor']; $r['status']=$r['recognized_minor']===0?'reversed':($r['outstanding_minor']===0?'paid':($r['paid_minor']>0?'partial':'unpaid')); if(!isset($f['status']) || $f['status']==='all' || $f['status']===$r['status'] || ($f['status']==='unpaid' && $r['outstanding_minor']>0)) $out[]=$r; } return $out; }
    public static function payables(array $f=array()) { GE_WTP_Operations::permission('finance'); global $wpdb; $rows=$wpdb->get_results('SELECT * FROM '.self::t('payables').' WHERE '.self::list_where($f,'incurred_on',false).' ORDER BY due_on,id',ARRAY_A); $out=array(); $status=$f['status']??'unpaid'; if(!in_array($status,array('all','unpaid','partial','paid','reversed'),true)) self::fail('invalid_status','Invalid payable status.'); foreach($rows as $r) { $r['recognized_minor']=self::obligation($r['id']); $r['paid_minor']=self::paid($r['id']); $r['outstanding_minor']=$r['recognized_minor']-$r['paid_minor']; $r['status']=$r['recognized_minor']===0?'reversed':($r['outstanding_minor']===0?'paid':($r['paid_minor']>0?'partial':'unpaid')); if($status==='all' || ($status==='unpaid' && $r['outstanding_minor']>0) || $status===$r['status']) $out[]=$r; } return $out; }
    private static function totals($from,$to) { global $wpdb; return $wpdb->get_results($wpdb->prepare('SELECT e.currency, SUM(CASE WHEN COALESCE(x.entry_type,e.entry_type) IN (\'expense\',\'payable\') THEN e.amount_minor ELSE 0 END) AS costs_minor, SUM(CASE WHEN COALESCE(x.entry_type,e.entry_type)=\'payment\' THEN e.amount_minor ELSE 0 END) AS cash_out_minor, SUM(CASE WHEN COALESCE(x.entry_type,e.entry_type) IN (\'income\',\'refund\') THEN e.amount_minor ELSE 0 END) AS cash_in_minor FROM '.self::t('finance_entries').' e LEFT JOIN '.self::t('finance_entries').' x ON x.id=e.reverses_id WHERE e.entry_date BETWEEN %s AND %s GROUP BY e.currency',$from,$to),ARRAY_A); }
    public static function summary(array $f=array()) { GE_WTP_Operations::permission('finance'); list($from,$to)=self::period($f); $start=new DateTimeImmutable($from); $end=new DateTimeImmutable($to); $days=$start->diff($end)->days+1; $prevEnd=$start->modify('-1 day'); $prevStart=$prevEnd->modify('-'.($days-1).' days'); if(isset($f['month'])) { $prevStart=$start->modify('first day of previous month'); $prevEnd=$prevStart->modify('last day of this month'); } elseif(isset($f['year'])) { $prevStart=$start->modify('-1 year'); $prevEnd=$prevStart->modify('last day of December'); } return array('from'=>$from,'to'=>$to,'currencies'=>self::totals($from,$to),'previous'=>array('from'=>$prevStart->format('Y-m-d'),'to'=>$prevEnd->format('Y-m-d'),'currencies'=>self::totals($prevStart->format('Y-m-d'),$prevEnd->format('Y-m-d'))),'collected_minor'=>null,'collection_status'=>'partial_or_unknown','collections'=>self::collected($from,$to),'previous_collections'=>self::collected($prevStart->format('Y-m-d'),$prevEnd->format('Y-m-d')),'sales'=>self::sold($from,$to),'previous_sales'=>self::sold($prevStart->format('Y-m-d'),$prevEnd->format('Y-m-d'))); }
    public static function order_margin($id) { GE_WTP_Operations::permission('finance'); $id=absint($id); $order=function_exists('wc_get_order')?wc_get_order($id):false; if(!$order) self::fail('not_found','Order not found.'); global $wpdb; $costs=$wpdb->get_results($wpdb->prepare('SELECT e.currency,SUM(e.amount_minor) AS costs_minor FROM '.self::t('finance_entries').' e LEFT JOIN '.self::t('finance_entries').' x ON x.id=e.reverses_id WHERE e.order_id=%d AND COALESCE(x.entry_type,e.entry_type) IN (\'expense\',\'payable\') GROUP BY e.currency',$id),ARRAY_A); return array('order_id'=>$id,'sold_total_decimal'=>(string)$order->get_total(),'currency'=>$order->get_currency(),'recorded_costs'=>$costs,'legacy_supplier_costs'=>self::legacy_costs($order),'stock_material_costs'=>self::material_costs($order),'manual_materials_minor'=>self::manual_materials($order),'material_cost_basis'=>self::material_costs($order)['movement_count']?'stock_consumption':'manual','collected_minor'=>null,'collection_status'=>'unavailable','margin_minor'=>self::margin_value($order,$costs),'costs_complete'=>$order->get_meta('_ge_operations_costs_complete')==='yes','margin_status'=>self::margin_value($order,$costs)===null?'incomplete_costs':'complete'); }
    public static function reverse(array $a) { GE_WTP_Operations::permission('finance_write'); $id=absint($a['entry_id']??0); $date=self::day($a['date']??''); $reason=sanitize_textarea_field($a['reason']??''); if(!$id || !$reason) self::fail('invalid_reversal','Entry and reason required.'); return GE_WTP_Operations::transaction(function() use($id,$date,$reason) { global $wpdb; $seed=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::t('finance_entries').' WHERE id=%d',$id),ARRAY_A); if(!$seed || $seed['reverses_id']) self::fail('invalid_reversal','Only original entries can be reversed.'); $pid=$seed['entry_type']==='payable'?(int)$seed['source_id']:0; if($seed['entry_type']==='expense') $pid=(int)$wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::t('payables').' WHERE expense_id=%d',$seed['source_id'])); if($seed['entry_type']==='payment') $pid=(int)$wpdb->get_var($wpdb->prepare('SELECT payable_id FROM '.self::t('finance_payments').' WHERE id=%d',$seed['source_id'])); if($pid) $wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::t('payables').' WHERE id=%d FOR UPDATE',$pid)); $entry=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::t('finance_entries').' WHERE id=%d FOR UPDATE',$id),ARRAY_A); if($wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::t('finance_entries').' WHERE reverses_id=%d',$id))) self::fail('already_reversed','Entry already reversed.'); if(in_array($entry['entry_type'],array('payable','expense'),true) && $pid && self::paid($pid)>0) self::fail('paid_obligation','Reverse payments before reversing this obligation.'); $rid=self::ledger('reversal',$entry['source_id'],-(int)$entry['amount_minor'],$entry['currency'],$date,(int)$entry['order_id'],$id); GE_WTP_Operations::audit('finance_reversed',$rid,array('entry_id'=>$id,'reason'=>$reason)); return array('id'=>$rid); }); }
}

