<?php
defined('ABSPATH') || exit;

final class GE_WTP_Cost_UI {
    public static function init(){add_action('admin_post_ge_costs',array(__CLASS__,'handle'));}
    public static function url($tab='calculator',$args=array()){return GE_WTP_Staff_Portal::portal_url('costs',array_merge(array('cost_tab'=>$tab),$args));}
    private static function e($v){return esc_html((string)$v);}
    private static function money($v,$currency='ARS'){return $v===null?'Sin dato':self::e($currency.' '.number_format_i18n((float)$v,2));}
    private static function field($label,$name,$value='',$type='text',$attrs=''){echo '<label>'.self::e($label).'<input type="'.esc_attr($type).'" name="'.esc_attr($name).'" value="'.esc_attr($value).'" '.$attrs.'></label>';}
    private static function select($label,$name,$options,$selected=''){echo '<label>'.self::e($label).'<select name="'.esc_attr($name).'">';foreach($options as $key=>$name)echo '<option value="'.esc_attr($key).'"'.selected((string)$selected,(string)$key,false).'>'.self::e($name).'</option>';echo '</select></label>';}
    private static function start($op,$tab,$args=array()){echo '<form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'" class="ge-ce-form"><input type="hidden" name="action" value="ge_costs"><input type="hidden" name="op" value="'.esc_attr($op).'"><input type="hidden" name="return_tab" value="'.esc_attr($tab).'">';echo '<input type="hidden" name="idempotency_key" value="'.esc_attr(wp_generate_uuid4()).'">';wp_nonce_field('ge_costs');foreach($args as $key=>$value)echo '<input type="hidden" name="'.esc_attr($key).'" value="'.esc_attr($value).'">';}
    private static function end($label,$disabled=false){echo '<button type="submit" class="ge-staff-button"'.($disabled?' disabled':'').'>'.self::e($label).'</button></form>';}
    public static function render(){
        try{GE_WTP_Cost_Engine::permission();}catch(Throwable $e){echo '<p>'.self::e($e->getMessage()).'</p>';return;}
        wp_enqueue_style('ge-costs',GE_WTP_PLUGIN_URL.'assets/css/cost-engine.css',array(),GE_WTP_Cost_Engine::VERSION);
        wp_enqueue_script('ge-costs',GE_WTP_PLUGIN_URL.'assets/js/cost-engine.js',array(),GE_WTP_Cost_Engine::VERSION,true);
        wp_localize_script('ge-costs','geCostEngine',array('endpoint'=>rest_url('ge/v1/costs/'),'nonce'=>wp_create_nonce('wp_rest'),'calculatorUrl'=>self::url(),'catalog'=>GE_WTP_Cost_Engine::catalog(),'recipes'=>array_map(function($r){return array('id'=>(int)$r['id'],'name'=>$r['name'],'has_cost'=>!empty($r['cost']));},GE_WTP_Cost_Engine::recipes())));
        $tab=sanitize_key($_GET['cost_tab']??'calculator');$tabs=array('calculator'=>'Calculadora','products'=>'Productos','catalog'=>'Costos','lists'=>'Listas de proveedores','recipes'=>'Recetas','history'=>'Historial');if(!isset($tabs[$tab]))$tab='calculator';
        echo '<div class="ge-ce"><header class="ge-ce-header"><div><span class="ge-ce-eyebrow">GESTIÓN INTERNA</span><h1>Costos y Productos</h1><p>Del costo de fabricación al precio de venta, con origen y revisión.</p></div><a class="ge-ce-link" href="'.esc_url(self::url('lists')).'">Cargar lista de proveedor</a></header><nav class="ge-ce-tabs" aria-label="Costos y Productos">';foreach($tabs as $key=>$label)echo '<a '.($tab===$key?'aria-current="page"':'').' href="'.esc_url(self::url($key)).'">'.self::e($label).'</a>';echo '</nav>';
        $notice=get_transient('ge_cost_notice_'.get_current_user_id());if($notice){delete_transient('ge_cost_notice_'.get_current_user_id());echo '<p class="ge-ce-notice" role="status">'.self::e($notice).'</p>';}
        try{call_user_func(array(__CLASS__,$tab));}catch(Throwable $e){echo '<p class="ge-ce-notice" role="alert">'.self::e($e->getMessage()).'</p>';}
        echo '</div>';
    }
    private static function calculator(){
        echo '<div class="ge-ce-grid"><section class="ge-ce-card"><h2>Calcular un trabajo</h2><p>Elegí una receta o armá los componentes. Medidas en metros; costo privado.</p><form data-ge-calculator>';self::select('Receta','recipe_id',array(''=>'Cálculo personalizado')+self::recipe_options(),$_GET['recipe_id']??'');
        echo '<div class="ge-ce-fields">';self::field('Cantidad','quantity',$_GET['quantity']??1,'number','min="1" step="1" required');self::select('Moneda','currency',array('ARS'=>'ARS','USD'=>'USD','EUR'=>'EUR'));self::field('Ancho (m)','width_m','','number','min="0.0001" step="0.0001"');self::field('Largo (m)','length_m','','number','min="0.0001" step="0.0001"');self::select('Caras','faces',array('1'=>'Una cara','2'=>'Dos caras'));self::field('Horas de trabajo','hours','','number','min="0.0001" step="0.0001"');self::field('Merma (%)','waste_percent',0,'number','min="0" max="1000" step="0.01"');echo '</div><div class="ge-ce-checks"><label><input type="checkbox" name="lamination" value="1"> Laminado</label><label><input type="checkbox" name="installation" value="1"> Instalación</label></div>';
        self::line_builder();self::rule_fields();echo '<button type="submit" class="ge-staff-button">Calcular costo</button></form></section><section class="ge-ce-card ge-ce-result" aria-live="polite" data-ge-cost-result><span class="ge-ce-eyebrow">RESULTADO</span><h2>Listo para calcular</h2><p>El detalle mostrará costos, fuentes y componentes faltantes.</p></section></div>';
    }
    private static function recipe_options(){ $out=array();foreach(GE_WTP_Cost_Engine::recipes() as $r)$out[$r['id']]=$r['name'].' · v'.$r['id'];return $out; }
    private static function line_builder($lines=array()){
        echo '<fieldset class="ge-ce-builder"><legend>Componentes de costo</legend><div data-ge-cost-lines data-lines="'.esc_attr(wp_json_encode($lines)).'"></div><button type="button" data-ge-cost-add>Agregar componente</button></fieldset>';
    }
    private static function rule_fields($rule=array()){
        echo '<fieldset><legend>Precio sugerido</legend><div class="ge-ce-fields">';self::select('Regla','rule_mode',array('markup'=>'Markup sobre costo','margin'=>'Margen sobre venta'),$rule['mode']??'markup');self::field('Porcentaje','rule_value',$rule['value']??0,'number','min="0" max="1000" step="0.01"');self::field('Mínimo neto total','rule_minimum',$rule['minimum']??0,'number','min="0" step="0.01"');self::field('Redondear total a','rule_round',$rule['round_to']??0,'number','min="0" step="0.01"');self::field('Extras netos','rule_extras',$rule['extras']??0,'number','min="0" step="0.01"');self::field('Impuesto de venta (%)','rule_tax',$rule['tax_percent']??0,'number','min="0" max="100" step="0.01"');echo '</div><p class="ge-ce-help">Markup 30%: costo 100 → venta 130. Margen 30%: costo 100 → venta 142,86.</p></fieldset>';
    }
    private static function lists(){
        $key=sanitize_key($_GET['supplier_id']??'');$suppliers=GE_WTP_Supplier_Workspace::suppliers();$options=array(''=>'Todos los proveedores');foreach($suppliers as $k=>$r)$options[$k]=$r['name']??$k;
        echo '<section class="ge-ce-card"><h2>Listas de proveedores</h2><p>Cada archivo crea una versión. Revisá los ítems antes de activar sus costos.</p><form method="get"><input type="hidden" name="section" value="costs"><input type="hidden" name="cost_tab" value="lists">';self::select('Proveedor','supplier_id',$options,$key);echo '<button>Filtrar</button></form><details><summary>Cargar una nueva lista</summary><form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="ge_supplier_ws_entry"><input type="hidden" name="entry_type" value="price_list"><input type="hidden" name="cost_return" value="1">';
        // Workspace validates its supplier-scoped nonce; generate one when the supplier changes.
        self::select('Proveedor','supplier_id',array_filter($options,function($v,$k){return $k!=='';},ARRAY_FILTER_USE_BOTH),$key?:key($suppliers));echo '<input type="hidden" name="_wpnonce" data-ge-supplier-nonce value="'.esc_attr(wp_create_nonce('ge_supplier_ws_entry_'.($key?:key($suppliers)).'_price_list')).'"><script type="application/json" data-ge-supplier-nonces>'.wp_json_encode(array_map(function($k){return wp_create_nonce('ge_supplier_ws_entry_'.$k.'_price_list');},array_combine(array_keys($suppliers),array_keys($suppliers)))).'</script>';self::field('Título','title','','text','required maxlength="190"');self::field('Vigente desde','valid_from',wp_date('Y-m-d'),'date','required');self::select('Moneda','currency',array('ARS'=>'ARS','USD'=>'USD'));self::field('Rubro','category');echo '<label>Archivo<input type="file" name="supplier_file" accept=".csv,.xlsx,.xls,.pdf,.jpg,.jpeg,.png" required></label><label>Notas<textarea name="notes" rows="2"></textarea></label><button class="ge-staff-button">Guardar nueva versión</button></form></details>';
        echo '<div class="ge-ce-table-wrap"><table><thead><tr><th>Lista</th><th>Proveedor</th><th>Vigencia</th><th>Estado</th><th>Ítems</th><th></th></tr></thead><tbody>';foreach(GE_WTP_Cost_Engine::lists($key) as $r)echo '<tr><td>'.self::e($r['title']).'<small>'.self::e($r['file_name']).'</small></td><td><a href="'.esc_url(GE_WTP_Supplier_Workspace::detail_url($r['supplier_id'])).'">'.self::e($suppliers[$r['supplier_id']]['name']??$r['supplier_id']).'</a></td><td>'.self::e($r['effective_date']).'</td><td>'.self::e(self::status($r['status'])).'</td><td>'.self::e($r['count']).'</td><td><a href="'.esc_url(self::url('lists',array('list_id'=>$r['id'],'supplier_id'=>$r['supplier_id']))).'">Revisar</a></td></tr>';echo '</tbody></table></div></section>';
        if(!empty($_GET['list_id']))self::list_detail(absint($_GET['list_id']));
    }
    private static function status($s){return array('draft'=>'Sin parsear','parsed'=>'Pendiente de revisión','reviewed'=>'Revisada','active'=>'Vigente','archived'=>'Histórica','legacy_active'=>'Vigente · sin normalizar')[$s]??$s;}
    private static function list_detail($id){
        $r=GE_WTP_Cost_Engine::list_get($id);$n=$r['normalized'];echo '<section class="ge-ce-card"><h2>'.self::e($r['workspace']['title']).'</h2><p>'.self::e(self::status($n['status'])).' · '.self::e($r['workspace']['currency']??'ARS').'</p><a href="'.esc_url(wp_nonce_url(add_query_arg(array('action'=>'ge_supplier_ws_download','entry_id'=>$id),admin_url('admin-post.php')),'ge_supplier_ws_download_'.$id)).'">Descargar original privado</a><small>Checksum '.self::e($r['workspace']['file_hash']??'No registrado').'</small>';
        foreach(GE_WTP_Cost_Assist::requests($id) as $request){echo '<p class="ge-ce-notice">AI-GRUPO: '.self::e(array('queued'=>'En cola','completed'=>'Propuesta disponible · requiere revisión','failed'=>'No se completó')[$request['status']]??$request['status']).' · '.self::e($request['task_ref']??'').' '.self::e($request['error']??'').'</p>';}
        if(in_array($n['status'],array('draft','parsed'),true)){echo '<details><summary>Interpretar con AI-GRUPO</summary><p>Usá la asistencia si la estructura es ambigua. Devolverá una propuesta para revisar; no activa costos ni precios.</p>';$health=get_option('ge_cost_assist_runtime',array());$available=!empty($health['available'])&&($health['checked_at']??0)>time()-180;echo '<p class="ge-ce-notice">'.($available?'AI-GRUPO conectado.':'Conexión de inferencia pendiente o runtime desconectado. Podés continuar con el parser y revisión manual.').'</p>';self::start('graph.cost.assist.request','lists',array('list_id'=>$id));self::field('Instrucción (opcional)','instruction','Interpretar referencias, unidades, escalas e impuestos; señalar datos faltantes.');self::end('Pedir ayuda a AI-GRUPO',!$available);echo '</details>';}
        if(in_array($n['status'],array('draft','parsed'),true)&&empty($r['workspace']['active'])){self::start('graph.supplier.price_list.parse','lists',array('list_id'=>$id));if(count($n['extraction']['sheets']??array())>1)self::select('Hoja de la planilla','sheet',array_combine($n['extraction']['sheets'],$n['extraction']['sheets']),$n['extraction']['selected_sheet']??'');self::end('Extraer archivo');}
        foreach($n['extraction']['warnings']??array() as $warning)echo '<p class="ge-ce-notice">'.self::e($warning).'</p>';
        if(!empty($n['extraction']['text']))echo '<details><summary>Texto extraído</summary><pre class="ge-ce-extracted">'.self::e($n['extraction']['text']).'</pre></details>';
        if(in_array($n['status'],array('draft','parsed'),true)&&empty($r['workspace']['active'])){
            self::start('graph.supplier.price_list.review','lists',array('list_id'=>$id));echo '<div data-ge-list-editor data-extraction="'.esc_attr(wp_json_encode(array_merge($n['extraction']??array(),array('proposal'=>$n['proposal']['items']??array())))).'" data-currency="'.esc_attr(strtoupper($r['workspace']['currency']??'ARS')).'"></div><input type="hidden" name="items_json" data-ge-list-items><label><input type="checkbox" required> Verifiqué referencias, unidades, precios, escalas e impuestos contra el archivo.</label>';self::end('Guardar revisión');
        }else{
            echo '<div class="ge-ce-table-wrap"><table><thead><tr><th>Referencia</th><th>Descripción</th><th>Unidad</th><th>Costo</th><th>Impuestos</th></tr></thead><tbody>';foreach($n['items']??array() as $item)echo '<tr><td>'.self::e($item['supplier_sku']).'</td><td>'.self::e($item['description']).'</td><td>'.self::e($item['unit']).'</td><td>'.self::money($item['base_cost'],$item['currency']).'</td><td>'.self::e($item['tax_treatment']).'</td></tr>';echo '</tbody></table></div>';
        }
        if(!empty($n['items'])){$diff=GE_WTP_Cost_Engine::compare(array('list_id'=>$id));echo '<h3>Comparación con la lista vigente</h3><div class="ge-ce-stats">';$labels=array('unchanged'=>'Sin cambio','increased'=>'Aumentaron','decreased'=>'Bajaron','new'=>'Nuevos','removed'=>'Eliminados','ambiguous'=>'Dudosos','changed'=>'Cambió configuración');foreach($diff['counts'] as $key=>$value)echo '<div><strong>'.self::e($value).'</strong><span>'.self::e($labels[$key]).'</span></div>';echo '</div>';if($diff['legacy_unstructured'])echo '<p>La lista anterior no tiene ítems estructurados; no puede compararse automáticamente.</p>';echo '<div class="ge-ce-table-wrap"><table><thead><tr><th>Ítem</th><th>Cambio</th><th>Anterior</th><th>Nuevo</th><th>%</th></tr></thead><tbody>';foreach($diff['items'] as $item)if($item['status']!=='unchanged')echo '<tr><td>'.self::e($item['sku']).'</td><td>'.self::e($labels[$item['status']]).'</td><td>'.self::money($item['before']['base_cost']??null,$item['before']['currency']??'ARS').'</td><td>'.self::money($item['after']['base_cost']??null,$item['after']['currency']??'ARS').'</td><td>'.self::e($item['percent']===null?'—':$item['percent'].'%').'</td></tr>';echo '</tbody></table></div>';
        if($n['status']==='reviewed'){self::start('graph.supplier.price_list.activate','lists',array('list_id'=>$id,'review_hash'=>$n['review_hash']));echo '<label><input type="checkbox" required> Activar estos costos para cálculos internos.</label><p>La activación no modifica precios web.</p>';self::end('Activar lista revisada');}}
        echo '</section>';
    }
    private static function catalog(){
        echo '<section class="ge-ce-card"><h2>Catálogo de costos</h2><p>Listas vigentes, compras de Stock y tarifas internas, con su origen.</p><div class="ge-ce-table-wrap"><table><thead><tr><th>Descripción</th><th>Fuente</th><th>Unidad</th><th>Costo</th><th>Vigencia</th><th>Impuestos</th><th></th></tr></thead><tbody>';
        foreach(GE_WTP_Cost_Engine::catalog() as $r){
            echo '<tr><td>'.self::e($r['description']).'</td><td>'.self::e(self::source_label($r['source'])).'</td><td>'.self::e($r['unit']).'</td><td>'.self::money($r['base_cost']??null,$r['currency']).'</td><td>'.self::e($r['effective_from']??'').'</td><td>'.self::e(self::taxes()[$r['tax_treatment']]??$r['tax_treatment']).'</td><td>';
            if(strpos($r['ref'],'internal/')===0)echo '<a href="'.esc_url(self::url('catalog',array('rate_id'=>$r['id']??substr($r['ref'],9)))).'">Nueva versión</a>';
            if(isset($r['cost_key']))echo '<a href="'.esc_url(self::url('catalog',array('legacy_product_id'=>$r['product_id'],'cost_key'=>$r['cost_key']))).'">Revisar unidad e impuestos</a>';
            if(isset($r['stock_item_id']))echo '<a href="'.esc_url(self::url('catalog',array('stock_item_id'=>$r['stock_item_id']))).'">Definir impuestos</a>';
            echo '</td></tr>';
        }
        echo '</tbody></table></div>';
        if(!empty($_GET['legacy_product_id'])){echo '<h3>Revisar costo de proveedor existente</h3><p>El importe se lee de WooCommerce y conserva su archivo/fecha de origen. Sólo se guardará el significado de unidad, moneda, escala e impuestos.</p>';self::start('graph.cost.legacy_mapping.update','catalog',array('product_id'=>absint($_GET['legacy_product_id']),'cost_key'=>sanitize_text_field($_GET['cost_key']??'')));self::select('Unidad de costo','unit',self::units());self::select('Moneda del archivo original','currency',array('ARS'=>'ARS','USD'=>'USD','EUR'=>'EUR'));self::select('Cómo cobra el proveedor','pricing_mode',array('unit'=>'Por unidad de costo','lot'=>'Total de lote / tirada'));self::field('Cantidad mínima del lote / escala','min_qty',0,'number','min="0" step="0.01"');self::select('Impuestos','tax_treatment',self::taxes());self::field('IVA de origen (%)','tax_percent',0,'number','min="0" max="100" step="0.01"');echo '<label><input type="checkbox" required> Verifiqué estos datos contra la fuente del proveedor.</label>';self::end('Guardar revisión del costo existente');}
        if(!empty($_GET['stock_item_id'])){self::start('graph.cost.stock_tax.update','catalog',array('item_id'=>absint($_GET['stock_item_id'])));echo '<h3>Impuestos del costo de compra</h3><p>Usá el tratamiento documentado por el proveedor. Esta política afecta los cálculos de costo de este insumo.</p>';self::select('Tratamiento','tax_treatment',self::taxes());self::field('IVA de origen (%)','tax_percent',0,'number','min="0" max="100" step="0.01"');self::end('Guardar tratamiento de costo');}
        $id=absint($_GET['rate_id']??0);$rate=$id?get_post_meta($id,'_ge_cost_rate',true):array();if($id&&(!$rate||$rate['status']!=='active'))throw new RuntimeException('Elegí la versión vigente del costo.');
        echo '<details '.($id?'open':'').'><summary>'.($id?'Actualizar tarifa: nueva versión':'Agregar tarifa interna').'</summary>';self::start('graph.cost.rate.create','catalog',array('parent_id'=>$id));echo '<div class="ge-ce-fields">';
        self::field('Descripción','description',$rate['description']??'','text','required');self::select('Fuente','source',array('manual_internal'=>'Costo interno','equipment_process'=>'Equipo / proceso','labor'=>'Mano de obra','logistics'=>'Logística','outsourced_manual'=>'Tercerizado manual'),$rate['source']??'manual_internal');self::select('Unidad','unit',self::units(),$rate['unit']??'unit');self::field('Costo','base_cost',$rate['base_cost']??'','number','min="0" step="0.0001" required');self::select('Moneda','currency',array('ARS'=>'ARS','USD'=>'USD','EUR'=>'EUR'),$rate['currency']??'ARS');self::field('Fecha efectiva','effective_date',wp_date('Y-m-d'),'date','required');self::select('Tratamiento impositivo','tax_treatment',self::taxes(),$rate['tax_treatment']??'excluded');self::field('IVA de origen (%)','tax_percent',$rate['tax_percent']??0,'number','min="0" max="100" step="0.01"');echo '</div>';self::end('Guardar versión de tarifa');echo '</details></section>';
    }
    public static function units(){return array('unit'=>'Unidad','m2'=>'m²','m'=>'Metro lineal','roll'=>'Rollo','ream'=>'Resma','thousand'=>'Millar','sheet'=>'Hoja','lot'=>'Lote','hour'=>'Hora','click'=>'Impresión / click','kg'=>'kg','l'=>'Litro','box'=>'Caja','kit'=>'Kit','ml'=>'ml','cartridge'=>'Cartucho','ribbon'=>'Cinta');}
    public static function taxes(){return array('unknown'=>'Sin definir','excluded'=>'Costo neto (IVA excluido)','included_recoverable'=>'IVA incluido recuperable','included_nonrecoverable'=>'IVA incluido no recuperable','exempt'=>'Exento');}
    public static function source_label($s){return array('supplier_price_list'=>'Lista proveedor','stock_receipts'=>'Compras de stock','woo_supplier_catalog'=>'Costo existente Woo / proveedor','manual_internal'=>'Interno','equipment_process'=>'Equipo / proceso','labor'=>'Mano de obra','logistics'=>'Logística','outsourced_manual'=>'Tercerizado manual')[$s]??$s;}
    private static function recipes(){
        echo '<section class="ge-ce-card"><h2>Recetas reutilizables</h2><p>Cada guardado crea una versión auditable. Las recetas de consumo existentes se mantienen.</p><div class="ge-ce-recipe-list">';foreach(GE_WTP_Cost_Engine::recipes() as $r)echo '<a href="'.esc_url(self::url('recipes',array('recipe_id'=>$r['id']))).'">'.self::e($r['name']).' <small>Versión #'.self::e($r['id']).' · '.(!empty($r['cost'])?'Costo':'Consumo de stock').'</small></a>';echo '</div><h3>'.(!empty($_GET['recipe_id'])?'Crear nueva versión':'Nueva receta').'</h3>';$r=!empty($_GET['recipe_id'])?GE_WTP_Cost_Engine::recipe(absint($_GET['recipe_id'])):array();$cost=$r['cost']??array();self::start('graph.cost.recipe.create','recipes',array('id'=>$r['id']??0));self::field('Nombre','name',$r['name']??'','text','required');self::select('Moneda por defecto','currency',array('ARS'=>'ARS','USD'=>'USD','EUR'=>'EUR'),$cost['defaults']['currency']??'ARS');self::line_builder($cost['lines']??array());echo '<input type="hidden" name="lines_json" data-ge-lines-json>';self::rule_fields($cost['price_rule']??array());self::end('Guardar versión de receta');echo '</section>';
    }
    private static function products(){
        if(!empty($_GET['preview_id'])){self::render_preview(absint($_GET['preview_id']));return;}
        if(!empty($_GET['product_id'])){self::product_detail(absint($_GET['product_id']));return;}
        if(isset($_GET['new'])){self::product_form();return;}
        echo '<section class="ge-ce-card"><div class="ge-ce-card-head"><div><h2>Productos web</h2><p>Catálogo WooCommerce y configuración real de venta.</p></div><a class="ge-staff-button" href="'.esc_url(self::url('products',array('new'=>1))).'">Nuevo producto</a></div><form method="get"><input type="hidden" name="section" value="costs"><input type="hidden" name="cost_tab" value="products">';self::field('Buscar producto','query',sanitize_text_field($_GET['query']??''),'search');echo '<button>Buscar</button></form>';$data=GE_WTP_Cost_Products::find(array('query'=>$_GET['query']??'','page'=>$_GET['page']??1));echo '<div class="ge-ce-table-wrap"><table><thead><tr><th>Producto</th><th>Estado</th><th>Precio / cálculo</th><th>Costo asociado</th><th></th></tr></thead><tbody>';foreach($data['items'] as $r){$mode=$r['configuration']['mode']??'manual';echo '<tr><td>'.self::e($r['name']).'<small>'.self::e($r['sku']).'</small></td><td>'.self::e(array('publish'=>'Publicado','draft'=>'Borrador','private'=>'Privado','pending'=>'Pendiente')[$r['status']]).'</td><td>'.(isset($r['configuration']['options'])?count($r['configuration']['options']).' opciones':($mode==='digital'?'Fórmula digital':self::money($r['regular_price']===''?null:$r['regular_price']))).'</td><td>'.(!empty($r['cost_link'])?'Receta #'.self::e($r['cost_link']['recipe_id']):'Sin vincular').'</td><td><a href="'.esc_url(self::url('products',array('product_id'=>$r['id']))).'">Abrir</a></td></tr>';}echo '</tbody></table></div><nav class="ge-ce-pages">';for($i=max(1,$data['page']-2);$i<=min($data['pages'],$data['page']+2);$i++)echo '<a href="'.esc_url(self::url('products',array('page'=>$i,'query'=>$_GET['query']??''))).'">'.self::e($i).'</a>';echo '</nav></section>';
        echo '<section class="ge-ce-card"><h2>Analizar costos y márgenes</h2><p>Recalcular productos vinculados y elegir cuáles llevar a preview.</p><button type="button" data-ge-impact-load>Analizar productos vinculados</button><div data-ge-impact-result aria-live="polite"></div></section>';
    }
    private static function product_detail($id){
        $r=GE_WTP_Cost_Products::get($id);echo '<section class="ge-ce-card"><a href="'.esc_url(self::url('products')).'">Volver a productos</a><h2>'.self::e($r['name']).'</h2><p>'.self::e($r['status']).' · '.self::e($r['type']).' · Última edición '.self::e($r['modified_at']).'</p>';
        if($r['image_id'])echo wp_get_attachment_image($r['image_id'],'thumbnail');echo '<a href="'.esc_url($r['url']).'" target="_blank" rel="noopener">Ver producto web</a>';
        if(isset($r['impact'])){echo '<h3>Costo y margen</h3>';if(isset($r['impact']['error']))echo '<p>'.self::e($r['impact']['error']).'</p>';else{$i=$r['impact'];echo '<div class="ge-ce-stats"><div><span>Costo anterior / unidad</span><strong>'.self::money($i['old_unit_cost']).'</strong></div><div><span>Costo actual / unidad</span><strong>'.self::money($i['new_unit_cost']).'</strong></div><div><span>Cambio de costo</span><strong>'.self::e($i['change_percent']===null?'Sin base':$i['change_percent'].'%').'</strong></div><div><span>Margen actual</span><strong>'.self::e($i['margin_percent']===null?'Sin dato':$i['margin_percent'].'%').'</strong></div></div>';foreach($i['calculation']['missing'] as $missing)echo '<p class="ge-ce-notice">'.self::e($missing).'</p>';}}
        if(!empty($r['variations'])){echo '<h3>Variantes</h3>';foreach($r['variations'] as $v)echo '<p><a href="'.esc_url(self::url('products',array('product_id'=>$v['id']))).'">'.self::e($v['name']).' · '.self::money($v['regular_price']).'</a></p>';}
        if(!empty($r['configuration']['options'])){echo '<h3>Opciones de venta</h3><div class="ge-ce-table-wrap"><table><thead><tr><th>Opción</th><th>Precio</th><th>Cantidad fija</th></tr></thead><tbody>';foreach($r['configuration']['options'] as $k=>$v)echo '<tr><td>'.self::e($v['label']).'</td><td>'.self::money($v['price']).'</td><td>'.self::e($v['fixed_qty']??'—').'</td></tr>';echo '</tbody></table></div>';}
        self::start('graph.product.cost_link','products',array('product_id'=>$id));echo '<h3>Asociar costo interno</h3>';self::select('Receta','recipe_id',self::recipe_options(),$r['cost_link']['recipe_id']??'');self::field('Cantidad de referencia','quantity',$r['cost_link']['input']['quantity']??1,'number','min="1" step="1" required');self::field('Ancho (m)','width_m',$r['cost_link']['input']['width_m']??'','number','step="0.0001"');self::field('Largo (m)','length_m',$r['cost_link']['input']['length_m']??'','number','step="0.0001"');self::select('Moneda de costo','currency',array('ARS'=>'ARS','USD'=>'USD','EUR'=>'EUR'),$r['cost_link']['input']['currency']??'ARS');if(isset($r['configuration']['options']))self::select('Opción sostenida por la receta','option_key',array_map(function($v){return $v['label'];},$r['configuration']['options']),$r['cost_link']['option_key']??'');self::rule_fields($r['cost_link']['price_rule']??array());self::end('Guardar vínculo de costo');
        if($r['type']!=='variable'&&($r['configuration']['mode']??'')!=='digital'){self::start('graph.product.price_preview','products',array('product_id'=>$id));echo '<h3>Preview de precio</h3>';if(isset($r['configuration']['options']))self::select('Opción','option_key',array_map(function($v){return $v['label'];},$r['configuration']['options']),$r['cost_link']['option_key']??'');self::field('Precio unitario neto (vacío = sugerido por receta)','price','','number','min="0.01" step="0.01"');self::end('Preparar preview');}else echo '<p class="ge-ce-notice">'.($r['type']==='variable'?'Para cambiar precios, abrí cada variante.':'Este producto usa una fórmula digital. El cambio de precio requiere mapear su fórmula antes de aplicar.').'</p>';
        echo '</section>';self::product_form($r);
    }
    private static function gallery_field($selected){echo '<label>Imágenes de galería<select name="gallery_ids[]" multiple>'; $ids=get_posts(array('post_type'=>'attachment','post_status'=>'inherit','post_mime_type'=>'image','numberposts'=>100,'fields'=>'ids'));foreach(array_unique(array_merge($ids,$selected)) as $id)echo '<option value="'.esc_attr($id).'"'.(in_array($id,$selected)?' selected':'').'>'.self::e(get_the_title($id)?:wp_basename(get_attached_file($id))).'</option>';echo '</select><small>Podés elegir varias imágenes de la biblioteca.</small></label>';}
    private static function product_form($r=array()){
        $id=$r['id']??0;echo '<section class="ge-ce-card"><h2>'.($id?'Editar producto':'Nuevo producto en borrador').'</h2><p>Revisarás el preview antes de guardar en WooCommerce.</p>';self::start($id?'graph.product.update':'graph.product.create','products',array('product_id'=>$id));echo '<div class="ge-ce-fields">';self::field('Nombre','name',$r['name']??'','text','required maxlength="190"');self::field('Slug','slug',$r['slug']??'');self::field('SKU','sku',$r['sku']??'');if(!$id)self::select('Tipo de producto','product_type',array('simple'=>'Simple','variable'=>'Con variantes'));if($id)self::select('Estado','status',array('draft'=>'Borrador','publish'=>'Publicado','private'=>'Privado','pending'=>'Pendiente'),$r['status']);
        if(empty($r['configuration']['options'])&&($r['configuration']['mode']??'')!=='digital'&&($r['type']??'simple')!=='variable')self::field('Precio WooCommerce (según impuestos de la tienda)','regular_price',$r['regular_price']??'','number','min="0" step="0.01"');
        $cats=get_terms(array('taxonomy'=>'product_cat','hide_empty'=>false));$catoptions=array();if(!is_wp_error($cats))foreach($cats as $cat)$catoptions[$cat->term_id]=$cat->name;echo '<label>Categorías<select name="categories[]" multiple>';foreach($catoptions as $key=>$label)echo '<option value="'.esc_attr($key).'"'.(in_array($key,$r['categories']??array())?' selected':'').'>'.self::e($label).'</option>';echo '</select></label>';self::image_field($r['image_id']??0);self::gallery_field($r['gallery_ids']??array());self::field('Título SEO','seo_title',$r['seo_title']??'');self::field('Descripción SEO','seo_description',$r['seo_description']??'');echo '</div><label>Descripción corta<textarea name="short_description" rows="3">'.esc_textarea($r['short_description']??'').'</textarea></label><label>Descripción larga<textarea name="description" rows="5">'.esc_textarea($r['description']??'').'</textarea></label><details><summary>Stock de WooCommerce</summary><label><input type="checkbox" name="manage_stock" value="1"'.checked($r['manage_stock']??false,true,false).'> Gestionar stock en WooCommerce</label>';self::field('Unidades disponibles','stock_quantity',$r['stock_quantity']??'','number','min="0" step="1"');self::select('Disponibilidad','stock_status',array('instock'=>'En stock','outofstock'=>'Sin stock','onbackorder'=>'Bajo pedido'),$r['stock_status']??'instock');echo '</details>';
        $editable_attrs=true;foreach($r['attributes']??array() as $attr)if(!empty($attr['id']))$editable_attrs=false;if(($r['type']??'simple')==='simple'&&$editable_attrs){echo '<details><summary>Atributos visibles</summary><p>Un atributo por línea: Nombre: opción A | opción B</p><label>Atributos<textarea name="attribute_text" rows="3">';$lines=array();foreach($r['attributes']??array() as $a)$lines[]=($a['name']??'').': '.implode(' | ',$a['options']??array());echo esc_textarea(implode("\n",$lines)).'</textarea></label></details>';}
        if(!$id)echo '<details><summary>Variantes del nuevo producto</summary><p>Definí arriba los atributos. Una variante por línea: tamaño=A4 | color=Color ; precio ; SKU opcional. Se crearán en borrador.</p><label>Variantes<textarea name="variant_text" rows="4"></textarea></label></details>';self::end('Preparar cambios');echo '</section>';
    }
    private static function render_preview($id){
        $r=GE_WTP_Cost_Products::change($id);if($r['kind']==='bulk'){self::render_bulk($id,$r);return;}echo '<section class="ge-ce-card"><a href="'.esc_url(self::url('products')).'">Volver a productos</a><h2>Revisar cambios antes de aplicar</h2><p>Producto: '.self::e($r['before']['name']??$r['patch']['name']??'Nuevo producto').' · Preview #'.self::e($id).' · '.self::e($r['status']).'</p>';
        if($r['kind']==='price')echo '<div class="ge-ce-stats"><div><span>Precio neto actual</span><strong>'.self::money($r['extra']['current_selling']).'</strong></div><div><span>Precio neto propuesto</span><strong>'.self::money($r['extra']['price']).'</strong></div></div>';
        echo '<div class="ge-ce-table-wrap"><table><thead><tr><th>Campo</th><th>Actual</th><th>Propuesto</th></tr></thead><tbody>';foreach($r['patch'] as $k=>$v){if($k==='storefront_config')continue;if($k==='_variations'){echo '<tr><td>Variantes en borrador</td><td>—</td><td>';foreach($v as $variant)echo self::e(implode(' / ',$variant['attributes'])).' · '.self::money($variant['regular_price']).'<br>';echo '</td></tr>';continue;}$old=$r['before'][$k]??'—';echo '<tr><td>'.self::e(self::field_label($k)).'</td><td>'.self::e(self::value_label($old)).'</td><td>'.self::e(self::value_label($v)).'</td></tr>';}echo '</tbody></table></div>';
        if($r['status']==='preview'){self::start('graph.product.price_apply','products',array('preview_id'=>$id));echo '<label class="ge-ce-approval"><input type="checkbox" name="approved" value="1" required> Apruebo los cambios mostrados y su impacto en el catálogo web.</label><p>Se guardará un snapshot y el actor de la aprobación. Si el producto o costo cambió, este preview se bloqueará.</p>';self::end($r['kind']==='create'?'Crear borrador aprobado':'Aplicar cambios aprobados');}
        elseif($r['status']==='applied'){echo '<p>Aplicado por usuario #'.self::e($r['applied_by']).' · '.self::e($r['applied_at']).'</p><a href="'.esc_url(self::url('products',array('product_id'=>$r['product_id']))).'">Abrir producto</a>';if($r['kind']!=='create'){self::start('graph.product.rollback_preview','products',array('preview_id'=>$id));self::end('Preparar rollback del snapshot');}}
        echo '</section>';
    }
    private static function render_bulk($id,$r){echo '<section class="ge-ce-card"><h2>Revisar actualización seleccionada</h2><p>Se guardará un snapshot por producto. La aplicación verifica que precios y costos sigan vigentes.</p>';if($r['status']==='preview')self::start('graph.product.price_apply','products',array('preview_id'=>$id));echo '<div class="ge-ce-table-wrap"><table><thead><tr><th>Aplicar</th><th>Producto</th><th>Costo anterior</th><th>Costo nuevo</th><th>Precio actual neto</th><th>Precio propuesto neto</th></tr></thead><tbody>';foreach($r['extra']['preview_ids'] as $child){$p=GE_WTP_Cost_Products::change($child);echo '<tr><td>';if($r['status']==='preview')echo '<input type="checkbox" name="selected_previews[]" value="'.esc_attr($child).'" checked aria-label="Seleccionar '.esc_attr($p['before']['name']).'">';echo '</td><td><a href="'.esc_url(self::url('products',array('preview_id'=>$child))).'">'.self::e($p['before']['name']).'</a></td><td>'.self::money($p['before']['cost_link']['snapshot']['unit_cost']??null).'</td><td>'.self::money($p['extra']['calculation']['unit_cost']??null).'</td><td>'.self::money($p['extra']['current_selling']).'</td><td>'.self::money($p['extra']['price']).'</td></tr>';}echo '</tbody></table></div>';if($r['status']==='preview'){echo '<label><input type="checkbox" name="approved" value="1" required> Apruebo el impacto en los productos seleccionados.</label>';self::end('Aplicar seleccionados');}else echo '<p>Lote aplicado por usuario #'.self::e($r['applied_by']).' · '.self::e($r['applied_at']).'</p>';echo '</section>';}
    private static function field_label($k){return array('_product_type'=>'Tipo de producto','name'=>'Nombre','slug'=>'Slug','sku'=>'SKU','status'=>'Estado','regular_price'=>'Precio Woo','description'=>'Descripción larga','short_description'=>'Descripción corta','categories'=>'Categorías','image_id'=>'Imagen','gallery_ids'=>'Galería','attributes'=>'Atributos','manage_stock'=>'Gestionar stock','stock_quantity'=>'Stock','stock_status'=>'Disponibilidad','seo_title'=>'Título SEO','seo_description'=>'Descripción SEO')[$k]??$k;}
    private static function image_field($current){$images=get_posts(array('post_type'=>'attachment','post_mime_type'=>'image','post_status'=>'inherit','numberposts'=>50,'orderby'=>'ID','order'=>'DESC'));$options=array('0'=>'Sin imagen');foreach($images as $image)$options[$image->ID]=$image->post_title;if($current&&!isset($options[$current]))$options[$current]=get_the_title($current);self::select('Imagen de Biblioteca','image_id',$options,$current);echo '<label>O subir imagen nueva<input type="file" name="product_image" accept="image/png,image/jpeg,image/webp"></label>';}
    private static function value_label($v){if(is_bool($v))return $v?'Sí':'No';if(is_array($v)){return implode(' · ',array_map(function($x){return is_array($x)?(($x['name']??'').': '.implode(', ',array_map('strval',$x['options']??array()))):(string)$x;},$v));}return (string)$v;}
    private static function history(){global $wpdb;$rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.GE_WTP_Operations::table('audit').' WHERE event_type LIKE %s ORDER BY id DESC LIMIT 100','cost_%'),ARRAY_A);echo '<section class="ge-ce-card"><h2>Historial de cambios</h2><p>Registro de versiones, revisiones, costos y cambios aprobados. Últimos 100 eventos.</p><div class="ge-ce-table-wrap"><table><thead><tr><th>Fecha UTC</th><th>Evento</th><th>Referencia</th><th>Actor</th><th></th></tr></thead><tbody>';foreach($rows as $r){echo '<tr><td>'.self::e($r['occurred_at']).'</td><td>'.self::e($r['event_type']).'</td><td>'.self::e($r['object_ref']).'</td><td>#'.self::e($r['actor_id']).'</td><td>';if($r['event_type']==='cost_preview')echo '<a href="'.esc_url(self::url('products',array('preview_id'=>$r['object_ref']))).'">Ver snapshot</a>';echo '</td></tr>';}echo '</tbody></table></div></section>';}
    private static function rule($p){return array('mode'=>$p['rule_mode']??'markup','value'=>$p['rule_value']??0,'minimum'=>$p['rule_minimum']??0,'round_to'=>$p['rule_round']??0,'extras'=>$p['rule_extras']??0,'tax_percent'=>$p['rule_tax']??0);}
    public static function handle(){
        check_admin_referer('ge_costs');$p=wp_unslash($_POST);$op=sanitize_text_field($p['op']??'');$tab=sanitize_key($p['return_tab']??'calculator');$args=array();
        try{GE_WTP_Cost_Engine::permission(true);$a=$p;
            if($op==='graph.supplier.price_list.review'){$a['items']=json_decode($p['items_json']??'',true);}
            if(strpos($op,'graph.supplier.price_list.')===0)$args['list_id']=absint($p['list_id']??0);
            if(strpos($op,'graph.cost.recipe.')===0){$a['lines']=json_decode($p['lines_json']??'',true);$a['defaults']=array('currency'=>$p['currency']??'ARS','quantity'=>1,'waste_percent'=>0);$a['price_rule']=self::rule($p);}
            if($op==='graph.product.cost_link'){$a['input']=array_intersect_key($p,array_flip(array('quantity','currency','width_m','length_m')));foreach($a['input'] as $k=>$v)if($v==='')unset($a['input'][$k]);$a['price_rule']=self::rule($p);}
            if($op==='graph.product.create'||$op==='graph.product.update'){
                $patch=array_intersect_key($p,array_flip(array('name','slug','sku','status','regular_price','description','short_description','image_id','seo_title','seo_description','stock_quantity','stock_status','product_type')));if(($patch['stock_quantity']??null)==='')unset($patch['stock_quantity']);if(!empty($_FILES['product_image']['name'])){if(!current_user_can('upload_files'))throw new RuntimeException('Sin permiso de imágenes.');require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$media=media_handle_upload('product_image',0);if(is_wp_error($media))throw new RuntimeException($media->get_error_message());$patch['image_id']=$media;GE_WTP_Cost_Engine::audit('product_image_uploaded',$media,null,array('name'=>get_the_title($media)));}$patch['manage_stock']=!empty($p['manage_stock']);$patch['categories']=array_map('absint',(array)($p['categories']??array()));$patch['gallery_ids']=array_values(array_filter(array_map('absint',(array)($p['gallery_ids']??array()))));if(isset($p['attribute_text'])){$patch['attributes']=array();foreach(explode("\n",trim($p['attribute_text'])) as $line){if(!trim($line))continue;$bits=explode(':',$line,2);if(count($bits)!==2)throw new RuntimeException('Revisá formato de atributos.');$patch['attributes'][]=array('name'=>trim($bits[0]),'options'=>array_map('trim',explode('|',$bits[1])));}}$patch['variations']=array();if(!empty($p['variant_text']))foreach(explode("\n",trim($p['variant_text'])) as $line){if(!trim($line))continue;$parts=array_map('trim',explode(';',$line));if(count($parts)<2)throw new RuntimeException('Revisá el formato de variantes.');$attrs=array();foreach(explode('|',$parts[0]) as $pair){$kv=array_map('trim',explode('=',$pair,2));if(count($kv)!==2)throw new RuntimeException('Revisá atributos de variante.');$attrs[sanitize_title($kv[0])]=$kv[1];}$patch['variations'][]=array('attributes'=>$attrs,'regular_price'=>$parts[1],'sku'=>$parts[2]??'');}$a=$op==='graph.product.create'?$patch:array('product_id'=>absint($p['product_id']),'patch'=>$patch);
            }
            if($op==='graph.product.price_preview'&&($a['price']??'')==='')unset($a['price']);
            if($op==='graph.product.price_apply')GE_WTP_Cost_Products::human_context();
            $a['idempotency_key']=$p['idempotency_key']??'';$result=GE_WTP_Cost_Engine::execute($op,$a);if(isset($result['preview_id']))$args=array('preview_id'=>$result['preview_id']);elseif(isset($result['product_id']))$args=array('product_id'=>$result['product_id']);elseif($op==='graph.product.cost_link')$args=array('product_id'=>$p['product_id']);
            set_transient('ge_cost_notice_'.get_current_user_id(),'Operación guardada. Revisá el resultado.',60);
        }catch(Throwable $e){set_transient('ge_cost_notice_'.get_current_user_id(),$e->getMessage(),60);if(!empty($p['preview_id']))$args['preview_id']=absint($p['preview_id']);elseif(!empty($p['product_id']))$args['product_id']=absint($p['product_id']);}
        wp_safe_redirect(self::url($tab,$args));exit;
    }
}
