<?php
defined('ABSPATH') || exit;

/** Woo CRUD writes can only consume a saved, current preview in a human browser session. */
final class GE_WTP_Cost_Products {
    private static $human=false;
    const META='_ge_cost_product';
    private static function permission() { GE_WTP_Cost_Engine::permission(true);if(!current_user_can('manage_options')&&!current_user_can('ge_manage_products'))throw new RuntimeException('Sin permiso de productos.'); }
    public static function human_context() { if(PHP_SAPI==='cli'||!is_user_logged_in())throw new RuntimeException('La aprobación debe realizarse en Gestión.'); self::$human=true; }
    private static function require_human($id=0) {
        $qa=defined('GE_COST_QA_ALLOW_APPLY')&&GE_COST_QA_ALLOW_APPLY&&wp_get_environment_type()!=='production';
        if($qa && (!$id || (get_post_meta($id,'_ge_cost_qa',true)==='yes'&&get_post_status($id)==='draft')))return;
        if(get_option('ge_cost_product_writes_enabled')!=='yes')throw new RuntimeException('Las escrituras de catálogo aún no están habilitadas en este bloque.');
        if(!self::$human)throw new RuntimeException('Requiere aprobación humana explícita desde el preview de Gestión.');
    }
    public static function get($id,$detail=true) {
        GE_WTP_Cost_Engine::permission();$p=wc_get_product($id);if(!$p||!in_array($p->get_status(),array('publish','draft','pending','private'),true))throw new RuntimeException('Producto inexistente.');
        $config=GE_WTP_Commercial_Quote_Catalog::describe($p);$link=$p->get_meta(self::META,true)?:array();
        $attrs=array();foreach($p->get_attributes() as $key=>$attr)$attrs[$key]=is_object($attr)?$attr->get_data():$attr;
        $data=array('id'=>$p->get_id(),'type'=>$p->get_type(),'parent_id'=>$p->get_parent_id(),'name'=>$p->get_name(),'slug'=>$p->get_slug(),'sku'=>$p->get_sku(),'status'=>$p->get_status(),'regular_price'=>$p->get_regular_price('edit'),'sale_price'=>$p->get_sale_price('edit'),'sale_from'=>$p->get_date_on_sale_from()?$p->get_date_on_sale_from()->getTimestamp():null,'sale_to'=>$p->get_date_on_sale_to()?$p->get_date_on_sale_to()->getTimestamp():null,'tax_status'=>$p->get_tax_status(),'tax_class'=>$p->get_tax_class(),'description'=>$p->get_description(),'short_description'=>$p->get_short_description(),'categories'=>$p->get_category_ids(),'image_id'=>$p->get_image_id(),'gallery_ids'=>$p->get_gallery_image_ids(),'attributes'=>$attrs,'manage_stock'=>$p->get_manage_stock(),'stock_quantity'=>$p->get_stock_quantity(),'stock_status'=>$p->get_stock_status(),'configuration'=>$config,'cost_link'=>$link,'modified_at'=>$p->get_date_modified()?$p->get_date_modified()->date('c'):null,'url'=>$p->get_permalink(),'seo_title'=>$p->get_meta('_ge_seo_title',true),'seo_description'=>$p->get_meta('_ge_seo_description',true));
        $data['hash']=GE_WTP_Cost_Engine::hash($data);
        if($detail&&!empty($link['recipe_id'])){
            try{$calc=GE_WTP_Cost_Engine::calculate(array('recipe_id'=>$link['recipe_id'],'input'=>$link['input']??array(),'price_rule'=>$link['price_rule']??array('mode'=>'markup','value'=>0)));$old=$link['snapshot']['unit_cost']??null;$current=$calc['unit_cost'];$selling=self::selling($data,$link['option_key']??'');$data['impact']=array('calculation'=>$calc,'old_unit_cost'=>$old,'new_unit_cost'=>$current,'change_percent'=>$old>0?round(($current/$old-1)*100,2):null,'selling_price'=>$selling,'margin_percent'=>$selling>0&&$calc['complete']?round((1-$current/$selling)*100,2):null,'cost_changed'=>($link['snapshot']['fingerprint']??null)!==$calc['fingerprint']);}catch(Throwable $e){$data['impact']=array('error'=>$e->getMessage());}
        }
        if($detail&&$p->is_type('variable')){$data['variations']=array();foreach(get_posts(array('post_type'=>'product_variation','post_parent'=>$id,'post_status'=>array('draft','publish','private','pending'),'numberposts'=>100,'fields'=>'ids','orderby'=>'ID','order'=>'ASC')) as $child)$data['variations'][]=self::get($child,false);}
        return $data;
    }
    public static function selling($data,$option) {
        $c=$data['configuration'];if(isset($c['options']))return $option&&isset($c['options'][$option])?(float)$c['options'][$option]['price']:null;
        if(($c['mode']??'')==='digital'||$data['type']==='variable')return null;
        $p=wc_get_product($data['id']);return $p?(float)wc_get_price_excluding_tax($p):null;
    }
    public static function find($a=array()) {
        GE_WTP_Cost_Engine::permission();$page=max(1,absint($a['page']??1));$status=$a['status']??array('publish','draft','pending','private');if(is_string($status)&&!in_array($status,array('publish','draft','pending','private'),true))throw new RuntimeException('Estado inválido.');$q=new WP_Query(array('post_type'=>'product','post_status'=>$status,'s'=>sanitize_text_field($a['query']??''),'posts_per_page'=>30,'paged'=>$page,'fields'=>'ids','orderby'=>'title','order'=>'ASC'));$rows=array();foreach($q->posts as $id)$rows[]=self::get($id,false);return array('items'=>$rows,'page'=>$page,'pages'=>(int)$q->max_num_pages,'total'=>(int)$q->found_posts);
    }
    public static function link($a) {
        self::permission();$id=absint($a['product_id']??0);$before=self::get($id,false);$recipe=GE_WTP_Cost_Engine::recipe(absint($a['recipe_id']??0));$input=$a['input']??array('quantity'=>1,'currency'=>'ARS');$rule=$a['price_rule']??($recipe['cost']['price_rule']??array('mode'=>'markup','value'=>0));$calc=GE_WTP_Cost_Engine::calculate(array('recipe_id'=>$recipe['id'],'input'=>$input,'price_rule'=>$rule));$option=sanitize_text_field($a['option_key']??'');if(isset($before['configuration']['options'])&&!isset($before['configuration']['options'][$option]))throw new RuntimeException('Elegí la opción de venta que sostiene esta receta.');
        return GE_WTP_Cost_Engine::lock('product:'.$id,function()use($id,$before,$recipe,$input,$rule,$calc,$option){return GE_WTP_Operations::transaction(function()use($id,$before,$recipe,$input,$rule,$calc,$option){$p=wc_get_product($id);$link=array('recipe_id'=>(int)$recipe['id'],'input'=>$input,'price_rule'=>$rule,'option_key'=>$option,'linked_at'=>gmdate('c'),'snapshot'=>$calc);$p->update_meta_data(self::META,$link);$p->save();GE_WTP_Cost_Engine::audit('product_link',$id,$before['cost_link'],$link);return self::get($id);});});
    }
    private static function clean_patch($a,$before=null) {
        $patch=array();if(!$before&&isset($a['product_type'])){if(!in_array($a['product_type'],array('simple','variable'),true))throw new RuntimeException('Tipo de producto inválido.');$patch['_product_type']=$a['product_type'];}foreach(array('name','slug','sku') as $key)if(isset($a[$key]))$patch[$key]=$key==='slug'?sanitize_title($a[$key]):sanitize_text_field($a[$key]);
        if(isset($patch['name'])&&!$patch['name'])throw new RuntimeException('Nombre requerido.');
        foreach(array('description','short_description') as $key)if(isset($a[$key]))$patch[$key]=wp_kses_post($a[$key]);
        if(isset($a['status'])){if(!in_array($a['status'],array('draft','publish','private','pending'),true))throw new RuntimeException('Estado inválido.');$patch['status']=$a['status'];}
        foreach(array('categories','gallery_ids') as $key)if(isset($a[$key]))$patch[$key]=array_values(array_unique(array_map('absint',(array)$a[$key])));
        foreach($patch['categories']??array() as $id)if(!term_exists($id,'product_cat'))throw new RuntimeException('Categoría inexistente.');
        if(isset($a['image_id']))$patch['image_id']=absint($a['image_id']);
        foreach(array_merge($patch['gallery_ids']??array(),array($patch['image_id']??0)) as $id)if($id&&!wp_attachment_is_image($id))throw new RuntimeException('Imagen inexistente.');
        foreach(array('regular_price','sale_price') as $key)if(array_key_exists($key,$a))$patch[$key]=$a[$key]===''?'':number_format(GE_WTP_Cost_Math::number($a[$key],$key),2,'.','');
        if(isset($a['manage_stock']))$patch['manage_stock']=!empty($a['manage_stock']);
        if(isset($a['stock_quantity'])){$qty=(string)$a['stock_quantity'];if(!preg_match('/^\d{1,9}$/D',$qty))throw new RuntimeException('Stock requiere unidades enteras.');$patch['stock_quantity']=(int)$qty;}
        if(isset($a['stock_status'])){if(!in_array($a['stock_status'],array('instock','outofstock','onbackorder'),true))throw new RuntimeException('Estado de stock inválido.');$patch['stock_status']=$a['stock_status'];}
        foreach(array('seo_title','seo_description') as $key)if(isset($a[$key]))$patch[$key]=sanitize_text_field($a[$key]);
        if(isset($a['attributes'])){if($before&&$before['type']==='variable')throw new RuntimeException('La estructura de variantes existente necesita edición específica.');$patch['attributes']=array();foreach((array)$a['attributes'] as $r){$name=sanitize_text_field($r['name']??'');$options=array_values(array_filter(array_map('sanitize_text_field',(array)($r['options']??array()))));if(!$name||!$options)throw new RuntimeException('Atributo incompleto.');$patch['attributes'][]=array('id'=>0,'name'=>$name,'options'=>$options,'visible'=>true,'variation'=>($patch['_product_type']??'simple')==='variable');}}
        if(($patch['_product_type']??'')==='variable'){unset($patch['regular_price']);$variants=$a['variations']??array();if(!$variants||count($variants)>50||empty($patch['attributes']))throw new RuntimeException('Un producto variable necesita atributos y entre 1 y 50 variantes.');$seen=array();$patch['_variations']=array();foreach($variants as $variant){$attrs=array();foreach($patch['attributes'] as $attr){$key=sanitize_title($attr['name']);$value=sanitize_text_field($variant['attributes'][$key]??'');if(!in_array($value,$attr['options'],true))throw new RuntimeException('Cada variante debe elegir una opción por atributo.');$attrs[$key]=$value;}$hash=GE_WTP_Cost_Engine::hash($attrs);if(isset($seen[$hash]))throw new RuntimeException('Variante duplicada.');$seen[$hash]=true;$patch['_variations'][]=array('attributes'=>$attrs,'regular_price'=>number_format(GE_WTP_Cost_Math::number($variant['regular_price']??null,'precio de variante'),2,'.',''),'sku'=>sanitize_text_field($variant['sku']??''),'status'=>'draft');}}
        if($before&&isset($before['configuration']['options'])&&(isset($patch['regular_price'])||isset($patch['sale_price'])))throw new RuntimeException('Este producto usa opciones: cambiá el precio de la opción mediante el preview de precios.');
        if($before&&($before['configuration']['mode']??'')==='digital'&&(isset($patch['regular_price'])||isset($patch['sale_price'])))throw new RuntimeException('Fórmula digital: edición de precios requiere mapeo de la fórmula.');
        if($before&&$before['type']==='variable'&&(isset($patch['regular_price'])||isset($patch['sale_price'])))throw new RuntimeException('Editá el precio de cada variante.');
        return $patch;
    }
    private static function preview($kind,$id,$before,$patch,$extra=array()) {
        $data=array('kind'=>$kind,'product_id'=>$id,'before'=>$before,'patch'=>$patch,'extra'=>$extra,'created_by'=>get_current_user_id(),'created_at'=>gmdate('c'),'expires_at'=>time()+3600,'status'=>'preview');$preview=wp_insert_post(array('post_type'=>GE_WTP_Cost_Engine::CHANGE,'post_status'=>'private','post_title'=>'Preview '.$kind.' #'.$id),true);if(is_wp_error($preview)||!$preview)throw new RuntimeException('No se pudo guardar preview.');GE_WTP_Cost_Engine::put($preview,'_ge_cost_change',$data);GE_WTP_Cost_Engine::audit('preview',$preview,null,$data);return array('preview_id'=>(int)$preview,'approval_url'=>GE_WTP_Cost_UI::url('products',array('preview_id'=>$preview)),'data'=>$data,'approval_required'=>true);
    }
    public static function create($a) { self::permission();$patch=self::clean_patch($a);$patch+=array('name'=>'','status'=>'draft','regular_price'=>'0');if(!$patch['name'])throw new RuntimeException('Nombre requerido.');if($patch['status']!=='draft')throw new RuntimeException('Creá el producto en borrador; publicalo luego con otro preview.');return self::preview('create',0,null,$patch); }
    public static function update($a) { self::permission();$id=absint($a['product_id']??0);$before=self::get($id,false);return self::preview('update',$id,$before,self::clean_patch($a['patch']??array(),$before)); }
    public static function price_preview($a) {
        self::permission();$id=absint($a['product_id']??0);$before=self::get($id,false);$link=$before['cost_link'];$option=sanitize_text_field($a['option_key']??$link['option_key']??'');$config=$before['configuration'];$mode=$config['mode']??'manual';
        if($before['type']==='variable'||$mode==='digital')throw new RuntimeException('Seleccioná una variante o completá el mapeo de la fórmula digital.');
        if(isset($a['price']))$price=GE_WTP_Cost_Math::number($a['price'],'precio',0.01);
        else{if(empty($link['recipe_id']))throw new RuntimeException('Asociá una receta o ingresá un precio explícito.');$calc=GE_WTP_Cost_Engine::calculate(array('recipe_id'=>$link['recipe_id'],'input'=>$link['input'],'price_rule'=>$link['price_rule']));if(!$calc['complete'])throw new RuntimeException('El costo está incompleto.');if($calc['currency']!==get_woocommerce_currency())throw new RuntimeException('La moneda del costo difiere de la tienda.');$price=$calc['pricing']['suggested_net']/(float)$calc['input']['quantity'];if($price<=0)throw new RuntimeException('Precio sugerido inválido.');}
        $patch=array();$extra=array('price'=>$price,'option_key'=>$option,'calculation'=>$calc??null,'current_selling'=>self::selling($before,$option));
        if(isset($config['options'])){if(!isset($config['options'][$option]))throw new RuntimeException('Elegí una opción válida.');$store=GE_WTP_Storefront::config($id);$store['options'][$option]['price']=round($price,2);$patch['storefront_config']=$store;}
        else {if($before['sale_price']!=='')throw new RuntimeException('Revisá la oferta activa antes de modificar precio.');$p=wc_get_product($id);$tax=wc_get_price_including_tax($p,array('price'=>$price));$patch['regular_price']=number_format(wc_prices_include_tax()?$tax:$price,2,'.','');}
        return self::preview('price',$id,$before,$patch,$extra);
    }
    public static function rollback_preview($a) { self::permission();$change=self::change(absint($a['preview_id']??0));if($change['status']!=='applied'||$change['kind']==='create')throw new RuntimeException('Snapshot no reversible desde esta acción.');$current=self::get($change['product_id'],false);if($current['hash']!==$change['after_hash'])throw new RuntimeException('El producto cambió después; reconciliá antes del rollback.');$patch=array();foreach(array_keys($change['patch']) as $key){if($key==='storefront_config')$patch[$key]=$change['extra']['before_storefront']??null;elseif($key==='attributes')$patch[$key]=array_values($change['before']['attributes']);else $patch[$key]=$change['before'][$key]??null;}return self::preview('rollback',$current['id'],$current,$patch,array('restore_link'=>$change['before']['cost_link'],'rollback_of'=>absint($a['preview_id']))); }
    public static function change($id) { GE_WTP_Cost_Engine::permission();$r=get_post_meta($id,'_ge_cost_change',true);if(get_post_type($id)!==GE_WTP_Cost_Engine::CHANGE||!is_array($r))throw new RuntimeException('Preview inexistente.');return $r; }
    public static function apply($a) {
        self::permission();$preview_id=absint($a['preview_id']??0);$change=self::change($preview_id);if(($change['kind']??'')==='bulk')return self::bulk_apply($a);self::require_human($change['product_id']);if(empty($a['approved']))throw new RuntimeException('Confirmá el impacto de este preview.');
        return GE_WTP_Cost_Engine::lock('product:'.($change['product_id']?:'create:'.$preview_id),function()use($preview_id,$a){return GE_WTP_Operations::transaction(function()use($preview_id,$a){global $wpdb;$wpdb->get_var($wpdb->prepare('SELECT ID FROM '.$wpdb->posts.' WHERE ID=%d FOR UPDATE',$preview_id));clean_post_cache($preview_id);$change=self::change($preview_id);if($change['status']==='applied')return array('product_id'=>$change['product_id'],'replayed'=>true);if($change['status']!=='preview'||$change['expires_at']<time())throw new RuntimeException('Preview vencido.');$id=$change['product_id'];if($id){$wpdb->get_var($wpdb->prepare('SELECT ID FROM '.$wpdb->posts.' WHERE ID=%d FOR UPDATE',$id));clean_post_cache($id);}$fresh=$id?self::get($id,false):null;if($id&&$fresh['hash']!==$change['before']['hash'])throw new RuntimeException('El producto cambió: generá otro preview.');
            if(!empty($change['extra']['calculation'])){$link=$fresh['cost_link'];$calc=GE_WTP_Cost_Engine::calculate(array('recipe_id'=>$link['recipe_id'],'input'=>$link['input'],'price_rule'=>$link['price_rule']));if(!$calc['complete']||$calc['fingerprint']!==$change['extra']['calculation']['fingerprint'])throw new RuntimeException('El costo cambió: recalculá el preview.');}
            $patch=$change['patch'];$extra=$change['extra'];$p=$id?wc_get_product($id):(($patch['_product_type']??'simple')==='variable'?new WC_Product_Variable():new WC_Product_Simple());$variants=$patch['_variations']??array();unset($patch['_product_type'],$patch['_variations']);
            if(isset($patch['storefront_config'])||array_key_exists('storefront_config',$patch)){$extra['before_storefront']=$id?$p->get_meta('_ge_storefront_config',true):null;if($patch['storefront_config'])$p->update_meta_data('_ge_storefront_config',$patch['storefront_config']);else $p->delete_meta_data('_ge_storefront_config');unset($patch['storefront_config']);}
            foreach($patch as $key=>$value){if(in_array($key,array('seo_title','seo_description'),true)){$p->update_meta_data('_ge_'.$key,$value);continue;}if($key==='attributes'){$attributes=array();foreach($value as $r){$attr=new WC_Product_Attribute();$attr->set_id($r['id']??0);$attr->set_name($r['name']);$attr->set_options($r['options']);$attr->set_visible($r['visible']??true);$attr->set_variation($r['variation']??false);$attributes[]=$attr;}$p->set_attributes($attributes);continue;}$setter='set_'.($key==='categories'?'category_ids':($key==='gallery_ids'?'gallery_image_ids':$key));if(!is_callable(array($p,$setter)))throw new RuntimeException('Campo de producto no soportado.');$p->$setter($value);}
            if(!empty($extra['calculation'])){$link=$fresh['cost_link'];$link['snapshot']=$extra['calculation'];$link['last_price_update']=gmdate('c');$p->update_meta_data(self::META,$link);}
            if(isset($extra['restore_link']))$p->update_meta_data(self::META,$extra['restore_link']);
            if(defined('GE_COST_QA_ALLOW_APPLY')&&GE_COST_QA_ALLOW_APPLY&&!$id)$p->update_meta_data('_ge_cost_qa','yes');
            $id=$p->save();if(!$id)throw new RuntimeException('WooCommerce no confirmó el guardado.');if($variants){$extra['created_variations']=array();foreach($variants as $data){$v=new WC_Product_Variation();$v->set_parent_id($id);$v->set_status('draft');$v->set_attributes($data['attributes']);$v->set_regular_price($data['regular_price']);if($data['sku'])$v->set_sku($data['sku']);if(defined('GE_COST_QA_ALLOW_APPLY')&&GE_COST_QA_ALLOW_APPLY)$v->update_meta_data('_ge_cost_qa','yes');$vid=$v->save();if(!$vid)throw new RuntimeException('No se pudo crear una variante.');$extra['created_variations'][]=$vid;}WC_Product_Variable::sync($id);}
            wc_delete_product_transients($id);clean_post_cache($id);$after=self::get($id,false);$change['status']='applied';$change['product_id']=$id;$change['extra']=$extra;$change['applied_by']=get_current_user_id();$change['applied_at']=gmdate('c');$change['after_hash']=$after['hash'];GE_WTP_Cost_Engine::put($preview_id,'_ge_cost_change',$change);GE_WTP_Cost_Engine::audit('product_'.$change['kind'],$id,$change['before'],$after);return array('product_id'=>$id,'snapshot_id'=>$preview_id,'after'=>$after);
        });});
    }
    public static function impact($a){GE_WTP_Cost_Engine::permission();$ids=get_posts(array('post_type'=>array('product','product_variation'),'post_status'=>array('draft','publish','private','pending'),'numberposts'=>301,'fields'=>'ids','meta_key'=>self::META,'orderby'=>'ID','order'=>'ASC'));$out=array();foreach(array_slice($ids,0,300) as $id){$r=self::get($id);$i=$r['impact']??array();$calc=$i['calculation']??array();$error=$i['error']??(!$calc?'Sin cálculo':(!$calc['complete']?implode('; ',$calc['missing']):null));$applicable=!$error&&$r['type']!=='variable'&&($r['configuration']['mode']??'')!=='digital'&&$calc['currency']===get_woocommerce_currency();$out[]=array('id'=>$id,'name'=>$r['name'],'old_cost'=>$i['old_unit_cost']??null,'new_cost'=>$i['new_unit_cost']??null,'margin'=>$i['margin_percent']??null,'suggested_price'=>!empty($calc['pricing'])?$calc['pricing']['suggested_net']/$calc['input']['quantity']:null,'changed'=>$i['cost_changed']??null,'applicable'=>$applicable,'error'=>$error);}return array('items'=>$out,'truncated'=>count($ids)>300);}
    public static function bulk_preview($a){self::permission();$ids=array_values(array_unique(array_map('absint',(array)($a['product_ids']??array()))));if(!$ids||count($ids)>30)throw new RuntimeException('Seleccioná entre 1 y 30 productos por lote.');sort($ids);$previews=array();$errors=array();foreach($ids as $id){try{$previews[]=self::price_preview(array('product_id'=>$id));}catch(Throwable $e){$errors[]=array('product_id'=>$id,'message'=>$e->getMessage());}}$batch=$previews?self::preview('bulk',0,null,array(),array('preview_ids'=>array_column($previews,'preview_id'))):null;return array('previews'=>$previews,'errors'=>$errors,'batch'=>$batch);}
    private static function bulk_apply($a){
        self::permission();self::require_human();if(empty($a['approved']))throw new RuntimeException('Aprobación explícita requerida.');$id=absint($a['preview_id']);
        return GE_WTP_Cost_Engine::lock('batch:'.$id,function()use($id,$a){
            $batch=self::change($id);$product_ids=array();foreach($batch['extra']['preview_ids'] as $child)$product_ids[]=self::change($child)['product_id'];
            try{return GE_WTP_Operations::transaction(function()use($id,$a){
                global $wpdb;$wpdb->get_var($wpdb->prepare('SELECT ID FROM '.$wpdb->posts.' WHERE ID=%d FOR UPDATE',$id));clean_post_cache($id);$batch=self::change($id);
                if($batch['status']==='applied')return array('preview_id'=>$id,'replayed'=>true);if($batch['status']!=='preview'||$batch['expires_at']<time())throw new RuntimeException('El lote venció.');
                $selected=array_values(array_unique(array_map('absint',$a['selected_previews']??array())));if(!$selected||array_diff($selected,$batch['extra']['preview_ids']))throw new RuntimeException('Selección de lote inválida.');
                $results=array();foreach($selected as $child)$results[]=self::apply(array('preview_id'=>$child,'approved'=>true));
                $batch['status']='applied';$batch['applied_by']=get_current_user_id();$batch['applied_at']=gmdate('c');$batch['selected_previews']=$selected;GE_WTP_Cost_Engine::put($id,'_ge_cost_change',$batch);GE_WTP_Cost_Engine::audit('bulk_applied',$id,null,array('selected'=>$selected,'results'=>$results));return array('preview_id'=>$id,'results'=>$results);
            });}catch(Throwable $e){clean_post_cache($id);foreach($batch['extra']['preview_ids'] as $child)clean_post_cache($child);foreach($product_ids as $pid){clean_post_cache($pid);wc_delete_product_transients($pid);}throw $e;}
        });
    }
    public static function execute($action,$a) { $map=array('graph.product.find'=>'find','graph.product.create'=>'create','graph.product.update'=>'update','graph.product.price_preview'=>'price_preview','graph.product.price_apply'=>'apply','graph.product.cost_link'=>'link','graph.product.rollback_preview'=>'rollback_preview','graph.product.impact'=>'impact','graph.product.bulk_preview'=>'bulk_preview');if($action==='graph.product.get')return self::get(absint($a['id']??0));if(!isset($map[$action]))throw new RuntimeException('Acción de costos desconocida.');return call_user_func(array(__CLASS__,$map[$action]),$a); }
}
