<?php
// Standalone, in-memory policy tests. Never loads WordPress or writes a database.
define('ABSPATH', __DIR__ . '/');
define('GE_WTP_PLUGIN_DIR', getenv('GE_CARDS_CORE_DIR') ?: dirname(__DIR__) . '/wp-content/plugins/ge-webtoprint-calculator/');
class WP_Post { public $ID,$post_author,$post_type,$post_status,$post_name,$post_title; }
class WP_Error { private $message; function __construct($code,$message){$this->message=$message;} function get_error_message(){return $this->message;} }
class Test_Response extends Exception {}
class GE_Organization { const PRIMARY='graphex'; }
class GE_WTP_Portal { static function is_staff_preview(){return !empty($GLOBALS['preview']);} static function is_customer_user($u){return $u->role==='customer';} static function is_staff_user($u){return $u->role==='staff';} }
class WC_Order {
    public $id=10,$customer=7,$status='processing',$paid=true,$tenant='graphex',$product=83,$quantity=100,$refunded=0,$refund_amount=0;
    function get_id(){return $this->id;} function get_customer_id(){return $this->customer;} function get_status(){return $this->status;} function is_paid(){return $this->paid;} function get_meta($k){return $this->tenant;}
    function get_items(){return array(1=>new Test_Item($this->product,$this->quantity));} function get_qty_refunded_for_item($id){return $this->refunded;}
    function get_total_refunded_for_item($id){return $this->refund_amount;}
}
class Test_Item { private $id,$qty; function __construct($id,$qty){$this->id=$id;$this->qty=$qty;} function get_product_id(){return $this->id;} function get_quantity(){return $this->qty;} function get_total(){return 1000;} }
$GLOBALS['posts']=array();$GLOBALS['meta']=array();$GLOBALS['user_meta']=array();$GLOBALS['options']=array('ge_cards_experience_enabled_v1'=>'yes');$GLOBALS['actor']=7;$GLOBALS['roles']=array(7=>'customer',8=>'customer');$GLOBALS['orders']=array();$GLOBALS['hooks']=array();$passed=0;
function add_action($hook,$fn){$GLOBALS['hooks'][$hook]=$fn;} function add_filter(){} function register_post_type(){}
function absint($x){return abs((int)$x);} function is_wp_error($x){return $x instanceof WP_Error;} function is_user_logged_in(){return $GLOBALS['actor']>0;} function get_current_user_id(){return $GLOBALS['actor'];}
function wp_get_current_user(){return (object)array('ID'=>$GLOBALS['actor'],'role'=>$GLOBALS['roles'][$GLOBALS['actor']]??'none');} function get_user_by($by,$id){return isset($GLOBALS['roles'][$id])?(object)array('ID'=>$id):false;}
function get_user_meta($id,$key,$single=true){return $GLOBALS['user_meta'][$id][$key]??'';} function get_post_meta($id,$key,$single=true){return $GLOBALS['meta'][$id][$key]??'';}
function update_post_meta($id,$key,$value){$GLOBALS['meta'][$id][$key]=$value;return true;} function get_post($id){return $GLOBALS['posts'][$id]??null;}
function get_posts($q){$out=array();foreach($GLOBALS['posts'] as $p){if($p->post_type!==$q['post_type'])continue;if(isset($q['author'])&&$p->post_author!==$q['author'])continue;if(isset($q['name'])&&$p->post_name!==$q['name'])continue;if(!in_array($p->post_status,(array)$q['post_status'],true))continue;if(isset($q['meta_key'])&&get_post_meta($p->ID,$q['meta_key'])!==$q['meta_value'])continue;$valid=true;foreach($q['meta_query']??array() as $m){if(get_post_meta($p->ID,$m['key'])!==$m['value'])$valid=false;}if($valid)$out[]=$p;}return $out;}
function wp_insert_post($data,$error=false){$id=$data['ID']??(count($GLOBALS['posts'])+1);$p=$GLOBALS['posts'][$id]??new WP_Post();$p->ID=$id;foreach($data as $k=>$v)$p->$k=$v;$GLOBALS['posts'][$id]=$p;return $id;} function wp_update_post($data,$error=false){return wp_insert_post($data,$error);}
function get_option($k,$default=false){return $GLOBALS['options'][$k]??$default;} function add_option($k,$v){if(isset($GLOBALS['options'][$k]))return false;$GLOBALS['options'][$k]=$v;return true;} function delete_option($k){unset($GLOBALS['options'][$k]);}
function wp_generate_uuid4(){return bin2hex(random_bytes(16));} function wp_die($msg,$title='', $args=array()){throw new Test_Response(strip_tags($msg),$args['response']??500);} function check_admin_referer($action){if(($_POST['_wpnonce']??'')!=='good')wp_die('nonce','',array('response'=>403));}
function wp_unslash($x){return $x;} function sanitize_key($x){return preg_replace('/[^a-z0-9_-]/','',strtolower((string)$x));} function sanitize_text_field($x){return trim(strip_tags((string)$x));} function is_email($x){return filter_var($x,FILTER_VALIDATE_EMAIL)!==false;} function esc_html($x){return htmlspecialchars($x,ENT_QUOTES,'UTF-8');}
function wp_parse_url($x,$component=-1){return parse_url($x,$component);} function esc_url_raw($x){return $x;} function home_url($x=''){return 'https://graphex.ar'.$x;} function add_query_arg($k,$v,$url){return $url.'?'.$k.'='.$v;} function wp_safe_redirect($url){throw new Test_Response($url,302);}
function wc_get_order($id){return $GLOBALS['orders'][$id]??false;} function wc_get_orders($q){return array_values(array_filter($GLOBALS['orders'],function($o)use($q){return $o->customer===$q['customer_id']&&in_array($o->status,$q['status'],true);}));}
require getenv('GE_CARDS_MODULE') ?: dirname(__DIR__).'/wp-content/mu-plugins/ge-cards-experience.php';
function ok($v,$msg){global $passed;if(!$v)throw new RuntimeException($msg);$passed++;}
function submit($extra=array()){$_SERVER['REQUEST_METHOD']='POST';$_POST=array_merge(array('_wpnonce'=>'good','first_name'=>'Alex','last_name'=>'Ejemplo','company'=>'Estudio Ejemplo','email'=>'alex@example.com','visibility'=>'draft','revision'=>0,'card_id'=>0),$extra);try{GE_Cards_Experience::save();throw new RuntimeException('Sin respuesta');}catch(Test_Response $r){return $r;}}
ok(isset($GLOBALS['hooks']['admin_post_nopriv_ge_customer_contact_card_save']),'Guard anónimo registrado');
ok(isset($GLOBALS['hooks']['admin_post_nopriv_ge_customer_contact_card_download_qr']),'QR de borrador exige autenticación');
$GLOBALS['actor']=0;ok(submit()->getCode()===403,'Creación anónima denegada');ok(!$GLOBALS['posts'],'Anónimo no crea registros');
$GLOBALS['actor']=7;$GLOBALS['preview']=true;ok(submit()->getCode()===403,'Preview staff no modifica contacto');$GLOBALS['preview']=false;
$GLOBALS['user_meta'][7]['_ge_organization_id']='otro';ok(submit()->getCode()===403,'Tenant ajeno denegado');unset($GLOBALS['user_meta'][7]);
ok(submit(array('_wpnonce'=>'bad'))->getCode()===403,'Nonce inválido');ok(!$GLOBALS['posts'],'Nonce inválido no crea');
ok(submit(array('email'=>"alex@example.com\r\nTEL:otro"))->getCode()===422,'Inyección de línea denegada');ok(!isset($GLOBALS['options']['ge_card_lock_7']),'Error libera lock');
ok(is_wp_error(GE_Cards_Experience::clean(array('first_name'=>'Alex','website'=>'javascript:alert(1)'))),'URL ejecutable denegada');ok(is_wp_error(GE_Cards_Experience::clean(array('first_name'=>array('x')))),'Campo array denegado');
ok(submit()->getCode()===302,'Cliente guarda borrador');$card=GE_Cards_Experience::mine(7);ok($card&&$card->post_status==='draft','Borrador privado');$token=$card->post_name;ok((bool)preg_match('/^[a-f0-9]{32}$/D',$token),'Token opaco');ok(GE_Cards_Experience::public_card($token)===null,'Borrador no público');
ok(!GE_Cards_Experience::owned($card,8),'Otro cliente no es dueño');$GLOBALS['actor']=8;ok(submit(array('card_id'=>$card->ID))->getCode()===403,'Otro cliente no puede actualizar ID ajeno');ok(count($GLOBALS['posts'])===1,'No crea al manipular ID');$GLOBALS['actor']=7;
$_GET=array('card_id'=>$card->ID,'format'=>'qr.svg');$_POST['_wpnonce']='good';$GLOBALS['actor']=8;try{GE_Cards_Experience::owner_qr();throw new RuntimeException('QR ajeno permitido');}catch(Test_Response $r){ok($r->getCode()===403,'QR de borrador ajeno denegado');}$GLOBALS['actor']=7;
ok(submit(array('card_id'=>$card->ID,'revision'=>0))->getCode()===409,'Revisión vieja denegada');ok(submit(array('card_id'=>$card->ID,'revision'=>1,'visibility'=>'publish'))->getCode()===422,'Publicación exige consentimiento');
ok(submit(array('card_id'=>$card->ID,'revision'=>1,'visibility'=>'publish','public_consent'=>1))->getCode()===302,'Sin compra guarda borrador');ok($card->post_status==='draft','Sin compra no publica');ok(GE_Cards_Experience::public_card($token)===null,'Sin compra no expone');
$o=new WC_Order();$GLOBALS['orders'][10]=$o;ok(GE_Cards_Experience::qualifying_order($o,7),'Compra física pagada válida');$o->customer=8;ok(!GE_Cards_Experience::qualifying_order($o,7),'Compra de otro dueño no habilita');$o->customer=7;$o->paid=false;ok(!GE_Cards_Experience::qualifying_order($o,7),'Compra impaga no habilita');$o->paid=true;$o->product=999;ok(!GE_Cards_Experience::qualifying_order($o,7),'Otro producto no habilita');$o->product=83;$o->refunded=-100;ok(!GE_Cards_Experience::qualifying_order($o,7),'Reembolso total no habilita');$o->refunded=0;$o->tenant='otro';ok(!GE_Cards_Experience::qualifying_order($o,7),'Compra tenant ajeno no habilita');$o->tenant='graphex';
$o->refund_amount=1000;ok(!GE_Cards_Experience::qualifying_order($o,7),'Reembolso monetario total sin cantidad no habilita');$o->refund_amount=0;ok(GE_Cards_Experience::entitlement(0)===0,'Invitado sin derecho de publicación');
ok(submit(array('card_id'=>$card->ID,'revision'=>2,'visibility'=>'publish','public_consent'=>1))->getCode()===302,'Compra y consentimiento publican');ok($card->post_status==='publish','Estado publicado');ok(GE_Cards_Experience::public_card($token)===$card,'Perfil publicado disponible');ok($card->post_name===$token,'URL estable');
$o->status='refunded';ok(GE_Cards_Experience::public_card($token)===null,'Reembolso desactiva destino');$o->status='processing';$GLOBALS['user_meta'][7]['_ge_organization_id']='otro';ok(GE_Cards_Experience::public_card($token)===null,'Cambio tenant propietario desactiva');unset($GLOBALS['user_meta'][7]);
ok(submit(array('card_id'=>$card->ID,'revision'=>3,'visibility'=>'draft'))->getCode()===302,'Retirar publicación');ok(GE_Cards_Experience::public_card($token)===null,'Publicación retirada no accesible');ok($card->post_name===$token,'Retirar mantiene URL');
$data=array('first_name'=>'Álex','last_name'=>'Ejemplo','company'=>'Estudio; Norte, Sur','role'=>str_repeat('Diseño ',20),'email'=>'alex@example.com','phone'=>'+541112345678','website'=>'https://example.com');$vcf=GE_Cards_Experience::vcf($data,'https://graphex.ar/tarjetas/demo/');
ok(strpos($vcf,'VERSION:3.0')!==false&&strpos($vcf,'FN:Álex Ejemplo')!==false,'VCF texto UTF8');ok(strpos($vcf,'ORG:Estudio\\; Norte\\, Sur')!==false,'VCF delimitadores escapados');foreach(explode("\r\n",$vcf)as$line)ok(strlen($line)<=75,'VCF líneas máximo75 octetos');ok(strpos($vcf,'billing')===false,'VCF sin datos fiscales');
$url='https://graphex.ar/tarjetas/demo/';$qr=GE_Cards_Experience::qr($url);ok(!is_wp_error($qr),'QR generado localmente');$svg=GE_Cards_Experience::svg($qr);ok(strpos($svg,'width="25mm"')!==false,'QR tamaño sugerido25mm');ok(strpos($svg,'viewBox="0 0 '.($qr->getModuleCount()+8))!==false,'Quiet zone cuatro módulos');file_put_contents(getenv('GE_CARDS_QR_OUTPUT')?:sys_get_temp_dir().'/ge-cards-demo.svg',$svg);file_put_contents(getenv('GE_CARDS_VCF_OUTPUT')?:sys_get_temp_dir().'/ge-cards-demo.vcf',$vcf);
echo json_encode(array('passed'=>$passed,'production_database_loaded'=>false,'real_orders_created'=>0,'real_profiles_published'=>0))."\n";
