<?php
define('ABSPATH',__DIR__);$GLOBALS['review']=array();$GLOBALS['actor']=7;$passed=0;
class WP_User{public $ID;function __construct($id){$this->ID=$id;}}
class WP_Error{public $code,$message,$data;function __construct($c='',$m='',$d=null){$this->code=$c;$this->message=$m;$this->data=$d;}}
class ReviewDenied extends RuntimeException{}
function add_action(){}function add_filter(){}function get_current_user_id(){return $GLOBALS['actor'];}function get_user_meta($id,$key,$single){return $GLOBALS['review'][$id]??'';}function wp_die($m,$t,$a){throw new ReviewDenied($m,$a['response']);}function wp_parse_url($u,$c){return parse_url($u,$c);}function wc_get_checkout_url(){return 'https://graphex.ar/checkout/';}
require dirname(__DIR__).'/wp-content/mu-plugins/ge-cards-canva/class-ge-cards-canva-review.php';
function ok($b,$s){global $passed;if(!$b)throw new RuntimeException($s);$passed++;}
function denied($cb){try{$cb();return false;}catch(ReviewDenied $e){return $e->getCode()===403;}}
$_SERVER=array('REQUEST_URI'=>'/privacidad-conexion-canva/','REQUEST_METHOD'=>'GET');GE_Cards_Canva_Review::front_guard();ok(!GE_Cards_Canva_Review::is_review(),'Missing WordPress meta must not restrict visitors');$u=new WP_User(7);ok(GE_Cards_Canva_Review::authenticate($u)===$u,'Normal users unchanged');$GLOBALS['review'][7]=array('expires_at'=>time()+3600);ok(GE_Cards_Canva_Review::authenticate($u)===$u,'Active dedicated account authenticates');$GLOBALS['review'][7]['expires_at']=time()-1;ok(GE_Cards_Canva_Review::authenticate($u) instanceof WP_Error,'Expired dedicated account cannot authenticate');$GLOBALS['review'][7]['expires_at']=time()+3600;
$_SERVER=array('REQUEST_URI'=>'/product/tarjetas-express/','REQUEST_METHOD'=>'GET');GE_Cards_Canva_Review::front_guard();ok(true,'Review product remains accessible');$_SERVER['REQUEST_URI']='/checkout/order-pay/10/';ok(denied(array('GE_Cards_Canva_Review','front_guard')),'Checkout and order payment blocked before processing');$_SERVER=array('REQUEST_URI'=>'/cliente-markcom/','REQUEST_METHOD'=>'POST');$_POST=array('action'=>'ge_customer_accept_quote');ok(denied(array('GE_Cards_Canva_Review','front_guard')),'Quote acceptance blocked');
$_REQUEST=array('action'=>'ge_customer_cards_design_export');GE_Cards_Canva_Review::write_guard();ok(true,'Own Canva export can be tested');$_REQUEST=array('action'=>'ge_vps_receive_upload');$_SERVER['REQUEST_METHOD']='PUT';GE_Cards_Canva_Review::write_guard();ok(true,'Private upload PUT can be tested');$_REQUEST=array('action'=>'ge_admin_update_customer');ok(denied(array('GE_Cards_Canva_Review','write_guard')),'Business mutation blocked');
class ReviewRequest{public $method;function get_method(){return $this->method;}}$req=new ReviewRequest;$req->method='POST';ok(GE_Cards_Canva_Review::rest_guard(null,null,$req) instanceof WP_Error,'REST writes blocked before order creation');$req->method='GET';ok(GE_Cards_Canva_Review::rest_guard('unchanged',null,$req)==='unchanged','Read REST result preserved');
class ReviewErrors{public $codes=array();function add($k,$m){$this->codes[]=$k;}}$errors=new ReviewErrors;GE_Cards_Canva_Review::checkout_guard(array(),$errors);ok($errors->codes===array('ge_canva_review_no_orders'),'Standard Woo checkout is also blocked');$GLOBALS['actor']=8;$req->method='POST';ok(GE_Cards_Canva_Review::rest_guard('unchanged',null,$req)==='unchanged','Regular customer REST writes unchanged');
echo json_encode(array('passed'=>$passed,'fixture_only'=>true,'network_calls'=>0,'orders_created'=>0)).PHP_EOL;