<?php
$load=getenv('GE_WP_LOAD');if(!$load||strpos($load,'/job-flow-qa-')===false)throw new Exception('Isolated QA required');define('FS_METHOD','direct');require $load;if(DB_NAME!=='graph_job_flow_20261007')throw new Exception('Wrong DB');
$ctx=json_decode(file_get_contents(dirname(dirname($load)).'/context.json'),true);wp_set_current_user(1);$checks=array();$mail=array();$transport='fail';
function cp_check($ok,$label){global $checks;if(!$ok)throw new Exception($label);$checks[]=$label;}
$filter=function($value,$atts)use(&$mail,&$transport){$attachments=$atts['attachments'];$mail[]=array('subject'=>$atts['subject'],'pdf'=>!empty($attachments)&&is_file(reset($attachments)));if($transport==='unknown')throw new RuntimeException('Synthetic uncertain transport');return $transport==='success';};add_filter('pre_wp_mail',$filter,PHP_INT_MAX,2);
$s=GE_WTP_Commercial_Quotes::get($ctx['quote'])['snapshot'];$s['fiscal_status']='pending';$s['fiscal_blockers']=array('billing_identity_changed_requires_reconciliation');$s['issuer_snapshot']['relationship_confirmed']=false;$s['issuer_snapshot']['verification_status']='pending';
function cp_quote($snapshot,$customer){$id=wp_insert_post(array('post_type'=>GE_WTP_Commercial_Quotes::POST_TYPE,'post_status'=>'private','post_title'=>'QA COMMERCIAL PUBLICATION'));update_post_meta($id,GE_WTP_Commercial_Quotes::CUSTOMER_META,$customer);update_post_meta($id,GE_WTP_Commercial_Quotes::STATUS_META,'draft');update_post_meta($id,GE_WTP_Commercial_Quotes::CURRENT_META,1);update_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,array(1=>$snapshot));return $id;}
$id=cp_quote($s,$ctx['customer']);$snapshots=get_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,true);
cp_check(is_wp_error(GE_WTP_Billing_Issuers::can_publish($s['issuer_snapshot'])),'Fixture has unconfirmed issuer relationship');
$result=GE_WTP_Commercial_Quotes::send($id,1,1,'publish-fixture');cp_check(is_wp_error($result)&&$result->get_error_code()==='ge_quote_notice_failed','Transport failure has a specific published notice result');
cp_check(get_post_meta($id,GE_WTP_Commercial_Quotes::STATUS_META,true)==='sent','Commercial approval publishes despite pending fiscal reconciliation');
cp_check(get_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,true)===$snapshots,'Publication preserves all original amounts issuer and fiscal blockers');
cp_check(strpos(GE_WTP_Commercial_Quotes::email_summary($s),'billing_identity_changed_requires_reconciliation')===false&&strpos(GE_WTP_Commercial_Quotes::email_summary($s),'pendiente de verificación')===false,'Client email excludes internal fiscal blockers and technical readiness labels');
cp_check(get_post_meta($id,'_ge_commercial_notice',true)['status']==='failed'&&count($mail)===1&&$mail[0]['pdf'],'Failed notice is recorded separately and uses actual commercial PDF');
$logs=get_posts(array('post_type'=>GE_WTP_Notifications::LOG_POST_TYPE,'post_status'=>'private','numberposts'=>-1,'meta_key'=>'_ge_email_object_id','meta_value'=>$id));cp_check(count($logs)===1&&get_post_meta($logs[0]->ID,'_ge_email_result',true)==='failed','Actual notification log records failed transport');
$events=get_post_meta($id,'_ge_commercial_events',true);cp_check(count(array_filter($events,function($e){return $e['event']==='published';}))===1&&count(array_filter($events,function($e){return in_array($e['event'],array('accepted','accepted_staff','converted'),true);}))===0,'Publishing records operator approval without customer acceptance or production approval');
GE_WTP_Commercial_Quotes::send($id,1,1,'publish-fixture');cp_check(count($mail)===1,'Repeated publication does not retry failed mail');
GE_WTP_Commercial_Quotes::send($id,1,1,'another-publish-click');cp_check(count($mail)===1,'Repeated publication with a new request never resends');
wp_set_current_user($ctx['customer']);$_GET=array();cp_check(in_array($id,array_column(GE_WTP_Portal_Quotes::customer_quotes(),'id'),true),'Customer can see published proposal even if notice failed');wp_set_current_user(1);
$_GET=array('quote_id'=>$id);ob_start();GE_WTP_Commercial_Quote_UI::render_staff();$html=ob_get_clean();cp_check(strpos($html,'Publicado; aviso no enviado')!==false&&strpos($html,'Reintentar aviso')!==false,'Staff detail explains partial success and offers explicit retry');
$transport='success';$result=GE_WTP_Commercial_Quotes::resend($id,1,1,'retry-fixture');cp_check(!is_wp_error($result)&&count($mail)===2,'Explicit retry succeeds without fiscal publication gate');
GE_WTP_Commercial_Quotes::resend($id,1,1,'retry-fixture');cp_check(count($mail)===2,'Repeated retry request is idempotent');
cp_check(get_post_meta($id,'_ge_commercial_notice',true)['status']==='sent'&&get_post_meta($id,GE_WTP_Commercial_Quotes::CURRENT_META,true)==1,'Retry only updates delivery result and preserves version');
cp_check(is_wp_error(GE_WTP_Billing_Issuers::validate_current($s['issuer_snapshot'])),'Fiscal issuer readiness still enforced for fiscal operations');
$stale=GE_WTP_Commercial_Quotes::resend($id,1,2,'stale-fixture');cp_check(is_wp_error($stale)&&$stale->get_error_code()==='ge_quote_version'&&count($mail)===2,'Stale version does not send');
add_option('ge_quote_publish_notice_'.$id,time(),'',false);$busy=GE_WTP_Commercial_Quotes::resend($id,1,1,'concurrent-fixture');delete_option('ge_quote_publish_notice_'.$id);cp_check(is_wp_error($busy)&&$busy->get_error_code()==='ge_quote_busy'&&count($mail)===2,'Concurrent action cannot send duplicate notice');
add_option('ge_quote_publish_notice_'.$id,time(),'',false);$edit=GE_WTP_Commercial_Quotes::revise($id,array(),array(),1);$billing=GE_WTP_Quote_Billing_Control::select($id,array(),1);delete_option('ge_quote_publish_notice_'.$id);cp_check(is_wp_error($edit)&&$edit->get_error_code()==='ge_quote_busy'&&is_wp_error($billing)&&$billing->get_error_code()==='ge_quote_busy','Revision and billing edits share publication lock to preserve exact PDF version');
$denied=GE_WTP_Commercial_Quotes::send($id,$ctx['customer'],1,'customer-fixture');cp_check(is_wp_error($denied)&&count($mail)===2,'Customer cannot publish or notify');
$foreign=cp_quote($s,$ctx['customer']);update_post_meta($foreign,'_ge_organization_id','other-organization');$denied=GE_WTP_Commercial_Quotes::send($foreign,1,1);cp_check(is_wp_error($denied)&&get_post_meta($foreign,GE_WTP_Commercial_Quotes::STATUS_META,true)==='draft'&&count($mail)===2,'Other organization cannot publish');
$incomplete=$s;$incomplete['draft_incomplete']=true;$unfinished=cp_quote($incomplete,$ctx['customer']);$denied=GE_WTP_Commercial_Quotes::send($unfinished,1,1);cp_check(is_wp_error($denied)&&$denied->get_error_code()==='ge_quote_incomplete'&&get_post_meta($unfinished,GE_WTP_Commercial_Quotes::STATUS_META,true)==='draft','Missing commercial data remains an actionable draft');
$transport='unknown';$uncertain=cp_quote($s,$ctx['customer']);$unknown=GE_WTP_Commercial_Quotes::send($uncertain,1,1,'uncertain-fixture');cp_check(is_wp_error($unknown)&&$unknown->get_error_code()==='ge_quote_notice_unknown'&&get_post_meta($uncertain,GE_WTP_Commercial_Quotes::STATUS_META,true)==='sent','Uncertain transport remains published with explicit unknown result');
GE_WTP_Commercial_Quotes::send($uncertain,1,1,'uncertain-fixture');cp_check(count($mail)===3,'Uncertain request never retries automatically');
remove_filter('pre_wp_mail',$filter,PHP_INT_MAX);echo 'PASS '.count($checks)." commercial publication checks\n";file_put_contents(dirname(dirname($load)).'/commercial-publication-results.json',wp_json_encode(array('checks'=>count($checks),'passed'=>$checks),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));
