<?php
$load=getenv('GE_WP_LOAD');if(!$load||strpos($load,'/job-flow-qa-')===false)throw new Exception('Isolated QA required');define('FS_METHOD','direct');require $load;if(DB_NAME!=='graph_job_flow_20261007')throw new Exception('Wrong DB');
$ctx=json_decode(file_get_contents(dirname(dirname($load)).'/context.json'),true);$checks=array();$emails=0;
function ca($ok,$label){global $checks;if(!$ok)throw new Exception($label);$checks[]=$label;}
function ca_fixture($s,$customer,$status='sent'){$id=wp_insert_post(array('post_type'=>GE_WTP_Commercial_Quotes::POST_TYPE,'post_status'=>'private','post_title'=>'QA CUSTOMER APPROVAL'));update_post_meta($id,GE_WTP_Commercial_Quotes::CUSTOMER_META,$customer);update_post_meta($id,GE_WTP_Commercial_Quotes::STATUS_META,$status);update_post_meta($id,GE_WTP_Commercial_Quotes::CURRENT_META,1);update_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,array(1=>$s));return $id;}
function ca_request($q,$ids=array()){$selected=GE_WTP_Quote_Selection::request_selection($q,array('selection_version'=>1,'quote_selection'=>$ids));if(is_wp_error($selected))throw new Exception($selected->get_error_message());return array_merge(GE_WTP_Quote_Selection::selection_args($selected),array('proposal_hash'=>GE_WTP_Quote_Billing_Control::hash($q['snapshot']),'selection_hash'=>GE_WTP_Quote_Billing_Control::hash($selected['snapshot']),'receiver_confirmed'=>1));}
function ca_alerts($id){return get_posts(array('post_type'=>GE_WTP_Internal_Alerts::TYPE,'post_status'=>'private','numberposts'=>-1,'meta_query'=>array(array('key'=>'_ge_quote_selection_notice','compare'=>'EXISTS'))));}
add_filter('pre_wp_mail',function($v,$a)use(&$emails){$emails++;return true;},PHP_INT_MAX,2);
$customer=$ctx['customer'];wp_set_current_user($customer);$s=GE_WTP_Commercial_Quotes::get($ctx['quote'])['snapshot'];$s['fiscal_status']='pending';$s['commercial_tax_policy']=true;$s['receiver_snapshot']=array('legal_name'=>'RECEPTOR QA','cuit'=>'23336924529');
$id=ca_fixture($s,$customer);$q=GE_WTP_Commercial_Quotes::get($id,$customer);$request=ca_request($q);$initial=get_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,true);$alerts=count(ca_alerts($id));
$saved=GE_WTP_Commercial_Quotes::save_selection($id,1,$request,$customer);ca(!is_wp_error($saved),'Save selection succeeds');ca(get_post_meta($id,GE_WTP_Commercial_Quotes::STATUS_META,true)==='sent','Save keeps published state');ca(get_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,true)===$initial,'Frozen proposal remains unchanged');ca(count(ca_alerts($id))===$alerts&&$emails===0,'Save sends no alerts or mail');ca(!get_post_meta($id,'_ge_commercial_accepted_at',true),'Save records no acceptance');
ca(!is_wp_error(GE_WTP_Commercial_Quote_PDF::build($saved))&&get_post_meta($id,GE_WTP_Commercial_Quotes::STATUS_META,true)==='sent','PDF export does not approve');
$_GET=array('presupuesto'=>$id,'approval_review'=>1);ob_start();GE_WTP_Commercial_Quote_UI::render_customer();$html=ob_get_clean();ca(strpos($html,'Guardar selección')!==false&&strpos($html,'Aprobar presupuesto')!==false,'Detail has separate controls');ca(strpos($html,'RECEPTOR QA')!==false&&strpos($html,'Confirmar aprobación')!==false&&strpos($html,'selection_hash')!==false,'Confirmation includes receiver and exact selection hash');
$_GET=array();ob_start();GE_WTP_Job_Flow::customer_list();$list=ob_get_clean();ca(strpos($list,'Ver detalle')!==false&&strpos($list,'Aprobar presupuesto')!==false,'List approval opens review');
$bad=$request;$bad['receiver_confirmed']=0;ca(is_wp_error(GE_WTP_Commercial_Quotes::approve_selection($id,1,$bad,$customer)),'Receiver confirmation required');$bad=$request;$bad['selection_hash']=str_repeat('0',64);ca(is_wp_error(GE_WTP_Commercial_Quotes::approve_selection($id,1,$bad,$customer)),'Changed total blocked');ca(is_wp_error(GE_WTP_Commercial_Quotes::approve_selection($id,2,$request,$customer)),'Stale version blocked');
$approved=GE_WTP_Commercial_Quotes::approve_selection($id,1,$request,$customer);ca(!is_wp_error($approved)&&$approved['status']==='accepted','Explicit approval accepts published quote');ca(count(ca_alerts($id))===$alerts+1,'Approval creates exactly one team alert');$fact=get_post_meta($id,'_ge_commercial_acceptance',true);ca($fact['version']===1&&$fact['actor_id']===$customer&&$fact['total_cents']===$approved['snapshot']['total_cents']&&$fact['snapshot_hash']===GE_WTP_Quote_Billing_Control::hash($approved['snapshot']),'Acceptance freezes actor version receiver items and final amounts');
ca(!get_post_meta($id,GE_WTP_Commercial_Quotes::ORDER_META,true)&&$emails===0,'Approval creates no order payment or customer mail');$axes=GE_WTP_Commercial_Quotes::state_axes($approved);ca($axes['artwork']!=='approved','Price acceptance does not approve artwork');
$again=GE_WTP_Commercial_Quotes::approve_selection($id,1,$request,$customer);ca(!is_wp_error($again)&&count(ca_alerts($id))===$alerts+1,'Repeated approval is idempotent');
$_GET=array('presupuesto'=>$id);ob_start();GE_WTP_Commercial_Quote_UI::render_customer();$html=ob_get_clean();ca(strpos($html,'<h3>Aprobado</h3>')!==false&&strpos($html,'>Confirmar aprobación</button>')===false,'Accepted view displays approval date instead of approve action');
$other=wp_insert_user(array('user_login'=>'approve-other-'.wp_generate_password(8,false),'user_pass'=>wp_generate_password(32),'user_email'=>'other-'.wp_generate_password(8,false).'@example.invalid','role'=>'customer'));wp_set_current_user($other);ca(is_wp_error(GE_WTP_Commercial_Quotes::approve_selection($id,1,$request,$other)),'Other customer cannot approve');wp_set_current_user($customer);$_GET=array();
$foreign=ca_fixture($s,$customer);update_post_meta($foreign,'_ge_organization_id','other');ca(is_wp_error(GE_WTP_Commercial_Quotes::approve_selection($foreign,1,$request,$customer)),'Cross tenant approval blocked');
$draft=ca_fixture($s,$customer,'draft');ca(is_wp_error(GE_WTP_Commercial_Quotes::get($draft,$customer)),'Draft remains inaccessible');
$variant=$s;$variant['items'][0]['selection_type']='alternative';$variant['items'][0]['selection_group']='model';$extra=$variant['items'][0];$extra['line_uuid']=wp_generate_uuid4();$extra['name']='Alternative QA';$variant['items'][]=$extra;$choice=ca_fixture($variant,$customer);$q=GE_WTP_Commercial_Quotes::get($choice,$customer);ca(is_wp_error(GE_WTP_Commercial_Quotes::save_selection($choice,1,array('selection_version'=>1),$customer)),'Missing variant cannot be saved or approved');$request=ca_request($q,array($extra['line_uuid']));$saved=GE_WTP_Commercial_Quotes::save_selection($choice,1,$request,$customer);ca(!is_wp_error($saved)&&count($saved['snapshot']['items'])===count($variant['items'])-1,'Selected variant persists privately with frozen prices');
add_option('ge_quote_publish_notice_'.$choice,time(),'',false);ca(is_wp_error(GE_WTP_Commercial_Quotes::approve_selection($choice,1,$request,$customer)),'Concurrent edit or approval lock blocks acceptance');delete_option('ge_quote_publish_notice_'.$choice);
$approved=GE_WTP_Commercial_Quotes::approve_selection($choice,1,$request,$customer);ca(!is_wp_error($approved)&&$approved['snapshot']['total_cents']===$saved['snapshot']['total_cents'],'Variant approval accepts exactly reviewed total');

$failed=ca_fixture($s,$customer);$q=GE_WTP_Commercial_Quotes::get($failed,$customer);$request=ca_request($q);$before=count(ca_alerts($failed));
$filter=function($empty,$post){return ($post['post_type']??'')===GE_WTP_Internal_Alerts::TYPE?true:$empty;};add_filter('wp_insert_post_empty_content',$filter,10,2);
$accepted=GE_WTP_Commercial_Quotes::approve_selection($failed,1,$request,$customer);remove_filter('wp_insert_post_empty_content',$filter,10);
ca(!is_wp_error($accepted)&&$accepted['status']==='accepted'&&get_post_meta($failed,'_ge_commercial_accept_notice_status',true)==='failed','Alert failure preserves acceptance with explicit failed notice');
ca((bool)get_post_meta($failed,'_ge_commercial_saved_selection',true),'Alert failure preserves private selection');
$_GET=array('presupuesto'=>$failed);ob_start();GE_WTP_Commercial_Quote_UI::render_customer();$html=ob_get_clean();ca(strpos($html,'Reintentar aviso al equipo')!==false,'Failed notice has explicit retry action');$_GET=array();
$retry=GE_WTP_Commercial_Quotes::approve_selection($failed,1,$request,$customer);ca(!is_wp_error($retry)&&get_post_meta($failed,'_ge_commercial_accept_notice_status',true)==='sent'&&count(ca_alerts($failed))===$before+1,'Explicit retry creates one alert without changing acceptance');GE_WTP_Commercial_Quotes::approve_selection($failed,1,$request,$customer);ca(count(ca_alerts($failed))===$before+1,'Repeated retry does not duplicate team alert');
$mutated=ca_fixture($s,$customer);$q=GE_WTP_Commercial_Quotes::get($mutated,$customer);$request=ca_request($q);$changed=$s;$changed['receiver_snapshot']['legal_name']='UPDATED QA';update_post_meta($mutated,GE_WTP_Commercial_Quotes::VERSIONS_META,array(1=>$changed));ca(is_wp_error(GE_WTP_Commercial_Quotes::approve_selection($mutated,1,$request,$customer)),'Same version snapshot drift blocks stale confirmation');
$_GET=array('ge_preview_customer'=>$customer,'ge_preview_token'=>wp_create_nonce('ge_preview_customer_'.$customer));wp_set_current_user(1);$_GET['ge_preview_token']=wp_create_nonce('ge_preview_customer_'.$customer);ca(is_wp_error(GE_WTP_Commercial_Quotes::approve_selection($choice,1,$request,1)),'Staff preview cannot approve for customer');$_GET=array();wp_set_current_user($customer);
ca(GE_Organization_Runtime::action_policy('ge_quote_approve')[0]==='quotes','Approval uses existing organization quote policy');ca(GE_Organization_Runtime::action_policy('ge_quote_retry_approval_notice')[0]==='quotes','Retry uses existing organization quote policy');
class ApprovalDie extends Exception {}
add_filter('wp_die_handler',function(){return function($message){throw new ApprovalDie(is_string($message)?$message:'Denied');};});
$_POST=array('quote_id'=>$choice,'selection_version'=>1,'_wpnonce'=>'invalid');$_REQUEST=$_POST;$denied=false;try{GE_WTP_Commercial_Quote_UI::handle_accept();}catch(ApprovalDie $e){$denied=true;}ca($denied,'Approval handler rejects invalid nonce');$_POST=$_REQUEST=array();
echo 'PASS '.count($checks)." customer approval checks\n";file_put_contents(dirname(dirname($load)).'/customer-approval-results.json',wp_json_encode(array('checks'=>count($checks),'passed'=>$checks),JSON_PRETTY_PRINT));file_put_contents(dirname(dirname($load)).'/customer-approval-context.json',wp_json_encode(array('plain'=>$id,'variant'=>$choice,'customer'=>$customer)));
