<?php
$site=getenv('GE_INVOICE_QA_SITE');if(!$site||!is_file($site.'/wp-load.php'))throw new Exception('QA_SITE');require $site.'/wp-load.php';if(DB_NAME!=='graphex_invoices_qa_20261003')throw new Exception('WRONG_DB');add_filter('pre_wp_mail','__return_true',999);
$admin=get_user_by('login','invoice_qa_admin')->ID;wp_set_current_user($admin);$checks=[];
function review_ok($name,$value){global $checks;if(!$value)throw new Exception('FAIL '.$name);$checks[]=$name;}
function review_user($role='customer'){$name='review_'.str_replace('-','',wp_generate_uuid4());return wp_insert_user(['user_login'=>$name,'user_pass'=>wp_generate_password(32),'user_email'=>$name.'@example.invalid','role'=>$role,'display_name'=>$name]);}
$customer=review_user();$other=review_user();$production=review_user('subscriber');$reader=review_user('subscriber');$registry=GE_Organization::all();$registry[GE_Organization::PRIMARY]['members'][(string)$production]='produccion';$registry[GE_Organization::PRIMARY]['members'][(string)$reader]='read-only';update_option(GE_Organization::ROOT,$registry,false);GE_WTP_Billing::save_profile($customer,['legal_name'=>'Synthetic review receiver','vat_status'=>'final_consumer','billing_mode'=>'common','cuit'=>'','fiscal_address'=>'Synthetic address'],$admin,false);
$row=GE_WTP_Customer_Invoices::normalize(['customer_id'=>$customer,'profile_id'=>'default','type'=>'factura','number'=>'REVIEW-'.wp_generate_uuid4(),'date'=>'2026-10-04','issuer_name'=>'Synthetic test issuer','currency'=>'ARS','amount'=>'1.00','confirmed'=>1,'public_note'=>'Synthetic public detail','internal_note'=>'ORIGINAL PRIVATE METADATA'],$admin);review_ok('Fixture metadata validated',!is_wp_error($row));$row['file']=['sha256'=>str_repeat('a',64),'mime'=>'application/pdf','name'=>'synthetic.pdf'];$id=wp_insert_post(['post_type'=>GE_WTP_Customer_Invoices::TYPE,'post_status'=>'private','post_title'=>$row['number']]);update_post_meta($id,'_ge_organization_id',GE_Organization::PRIMARY);update_post_meta($id,GE_WTP_Customer_Invoices::META,$row);update_post_meta($id,'_ge_invoice_customer',$customer);$ref='invoice:'.$id;
$token=wp_generate_uuid4();$case=GE_WTP_Customer_Invoices::comment($ref,'PRIVATE REVIEW NOTE sentinel',$token,$admin,true,'en_revision',true,false);review_ok('Internal note starts one case',!is_wp_error($case)&&$case['status']==='en_revision'&&count($case['events'])===1);$again=GE_WTP_Customer_Invoices::comment($ref,'PRIVATE REVIEW NOTE sentinel',$token,$admin,true,'en_revision',true,false);review_ok('Internal retry idempotent',!is_wp_error($again)&&count($again['events'])===1&&$again['id']===$case['id']);review_ok('No internal email log',count(get_posts(['post_type'=>'ge_email_log','post_status'=>'private','numberposts'=>-1,'meta_key'=>'_ge_email_object_id','meta_value'=>$case['id']]))===0);review_ok('Audit once on retry',count(get_post_meta($case['id'],'_ge_invoice_case_audit'))===1);
review_ok('Customer cannot private note',is_wp_error(GE_WTP_Customer_Invoices::comment($ref,'Forbidden private note',wp_generate_uuid4(),$customer,false,'recibido',true,false)));review_ok('Production cannot private note',is_wp_error(GE_WTP_Customer_Invoices::comment($ref,'Forbidden production note',wp_generate_uuid4(),$production,true,'recibido',true,false)));review_ok('Readonly cannot private note',is_wp_error(GE_WTP_Customer_Invoices::comment($ref,'Forbidden readonly note',wp_generate_uuid4(),$reader,true,'recibido',true,false)));review_ok('Cross customer denied',is_wp_error(GE_WTP_Customer_Invoices::comment($ref,'Wrong account comment',wp_generate_uuid4(),$other)));review_ok('Token cannot cross actor/visibility',is_wp_error(GE_WTP_Customer_Invoices::comment($ref,'Conflicting public request',$token,$customer)));review_ok('Required private message',is_wp_error(GE_WTP_Customer_Invoices::comment($ref,'',wp_generate_uuid4(),$admin,true,'recibido',true,false)));
wp_set_current_user($customer);$_GET=['seccion'=>'facturas','invoice'=>$ref];ob_start();GE_WTP_Customer_Invoices::render_portal();$html=ob_get_clean();review_ok('Customer private event hidden',strpos($html,'PRIVATE REVIEW NOTE')===false&&strpos($html,'ORIGINAL PRIVATE METADATA')===false);review_ok('Real customer form operational',strpos($html,'value="ge_invoice_review"')!==false&&strpos($html,'name="message"')!==false);
wp_set_current_user($admin);$_GET=['ge_preview_customer'=>$customer,'ge_preview_token'=>wp_create_nonce('ge_preview_customer_'.$customer),'invoice'=>$ref];ob_start();GE_WTP_Customer_Invoices::render_portal();$html=ob_get_clean();review_ok('Preview explains readonly',strpos($html,'Vista previa de solo lectura')!==false);review_ok('Preview disabled textarea visible',strpos($html,'fieldset disabled')!==false&&strpos($html,'textarea')!==false&&strpos($html,'value="ge_invoice_review"')===false);review_ok('Preview private history hidden',strpos($html,'PRIVATE REVIEW NOTE')===false);$_GET=[];
$public=GE_WTP_Customer_Invoices::comment($ref,'Public answer without notification',wp_generate_uuid4(),$admin,true,'respondido',false,false);review_ok('Public response persists state',!is_wp_error($public)&&$public['status']==='respondido');review_ok('Explicit no-mail honoured',count(get_posts(['post_type'=>'ge_email_log','post_status'=>'private','numberposts'=>-1,'meta_key'=>'_ge_email_object_id','meta_value'=>$case['id']]))===0);
wp_set_current_user($customer);$_GET=['invoice'=>$ref];ob_start();GE_WTP_Customer_Invoices::render_portal();$html=ob_get_clean();review_ok('Public answer visible customer',strpos($html,'Public answer without notification')!==false&&strpos($html,'PRIVATE REVIEW NOTE')===false);$_GET=[];$reply=GE_WTP_Customer_Invoices::comment($ref,'Customer followup reopens the case',wp_generate_uuid4(),$customer);review_ok('Customer reopens received',!is_wp_error($reply)&&$reply['status']==='recibido');
$logs=get_posts(['post_type'=>'ge_email_log','post_status'=>'private','numberposts'=>-1,'meta_key'=>'_ge_email_object_id','meta_value'=>$case['id']]);review_ok('Customer notice traced',count($logs)===2);foreach($logs as$log)review_ok('QA mail simulated '.$log->ID,get_post_meta($log->ID,'_ge_email_result',true)==='simulated');
wp_set_current_user($admin);$_GET=['invoice'=>$ref];ob_start();GE_WTP_Customer_Invoices::render_staff($customer);$html=ob_get_clean();review_ok('Staff sees private/public forms separately',strpos($html,'value="ge_invoice_internal_note"')!==false&&strpos($html,'value="ge_invoice_response"')!==false&&strpos($html,'PRIVATE REVIEW NOTE')!==false);review_ok('Public notice optional unchecked',strpos($html,'name="notify_customer" value="1">')!==false);$_GET=[];ob_start();GE_WTP_Customer_Invoices::render_reviews();$inbox=ob_get_clean();review_ok('Inbox shows exact customer/document',strpos($inbox,$row['number'])!==false&&strpos($inbox,'customer_id='.$customer)!==false);review_ok('Inbox does not echo private message',strpos($inbox,'PRIVATE REVIEW NOTE')===false);
update_post_meta($case['id'],'_ge_organization_id','foreign-organization');ob_start();GE_WTP_Customer_Invoices::render_reviews();$foreign=ob_get_clean();review_ok('Foreign case excluded inbox',strpos($foreign,$row['number'])===false);update_post_meta($case['id'],'_ge_organization_id',GE_Organization::PRIMARY);wp_set_current_user($production);ob_start();GE_WTP_Customer_Invoices::render_reviews();$denied=ob_get_clean();review_ok('Production denied inbox',strpos($denied,$row['number'])===false&&strpos($denied,'Sin permiso')!==false);wp_set_current_user($reader);ob_start();GE_WTP_Customer_Invoices::render_reviews();$read=ob_get_clean();review_ok('Readonly can consult without mutation',strpos($read,$row['number'])!==false);review_ok('Original metadata unchanged',get_post_meta($id,GE_WTP_Customer_Invoices::META,true)===$row);
$report=getenv('GE_REVIEW_QA_REPORT');if($report)file_put_contents($report,json_encode($checks,JSON_PRETTY_PRINT));echo count($checks)." review checks passed; synthetic only and simulated mail\n";
