<?php
$load=getenv('GE_WP_LOAD');if(!$load||strpos($load,'/job-flow-qa-')===false)throw new Exception('Isolated QA required');
define('FS_METHOD','direct');require $load;if(DB_NAME!=='graph_job_flow_20261007')throw new Exception('Wrong QA database');
$checks=0;function lc($v,$m){global $checks;if(!$v)throw new Exception($m);$checks++;}
lc(DISABLE_WP_CRON&&has_filter('pre_wp_mail','__return_true')!==false,'Mail/cron intercepted');lc(is_wp_error(wp_remote_get('https://example.invalid/')),'External HTTP blocked');
class LogisticRedirect extends Exception{}class LogisticDie extends Exception{}
add_filter('wp_redirect',function($url){throw new LogisticRedirect($url);});add_filter('wp_die_handler',function(){return function($message){throw new LogisticDie(strip_tags($message));};});
function logistics_act($id,$op,$data,$actor=1,$kind='order',$revision=null,$request=null){wp_set_current_user($actor);$s='order'===$kind?(array)wc_get_order($id)->get_meta(GE_Logistics::META):(array)get_post_meta($id,GE_Logistics::META,true);$_POST=array_merge(['action'=>'ge_'.$kind.'_logistics','record_id'=>$id,'op'=>$op,'revision'=>$revision??($s['revision']??0),'request_key'=>$request??wp_generate_uuid4()],$data);$_REQUEST=$_POST;$_REQUEST['_wpnonce']=$_POST['_wpnonce']=wp_create_nonce('ge_logistics_'.$kind.'_'.$id);try{GE_Logistics_UI::handle();}catch(LogisticRedirect $e){return true;}catch(LogisticDie $e){return $e->getMessage();}throw new Exception('Expected terminal response');}
$old=get_option(GE_Logistics::CONFIG);wp_set_current_user(1);
$org_original=get_option(GE_Organization::ROOT);
$config=['origin'=>GE_Logistics::address(['street'=>'QA private origin','city'=>'QA origin','province'=>'C','postal_code'=>'1234','hours'=>'QA only']),'origin_confirmed'=>true,'maps_enabled'=>false,'rates'=>[]];update_option(GE_Logistics::CONFIG,$config,false);
$customer=wp_insert_user(['user_login'=>'logistics-'.wp_generate_password(8,false),'user_email'=>'logistics-'.wp_generate_password(8,false).'@example.invalid','user_pass'=>wp_generate_password(30,false),'role'=>'customer']);
$other=wp_insert_user(['user_login'=>'other-logistics-'.wp_generate_password(8,false),'user_email'=>'other-logistics-'.wp_generate_password(8,false).'@example.invalid','user_pass'=>wp_generate_password(30,false),'role'=>'customer']);
$a=['street'=>'Calle QA 123','city'=>'Ciudad QA','province'=>'U','postal_code'=>'9100','recipient'=>'Receptor QA','phone'=>'1155550101','country'=>'AR'];
$order=wc_create_order(['customer_id'=>$customer]);$item=new WC_Order_Item_Product();$item->set_name('Impresión QA');$item->set_quantity(1000);$item->set_total(100);$item->update_meta_data('_ge_item_status','ready');$order->add_item($item);$order->set_total(100);$order->set_status('on-hold');$order->update_meta_data('_ge_lifecycle_stage','listo');$order->update_meta_data('_ge_payment_confirmed_by',1);$order->update_meta_data('_ge_payment_confirmed_at',gmdate('c'));$order->update_meta_data('_ge_payment_state','paid');$order->update_meta_data('_ge_payment_confirmed_total','100.00');$order->save();$id=$order->get_id();
$rows=[['count'=>2,'weight_kg'=>5,'length_cm'=>30,'width_cm'=>20,'height_cm'=>10]];
try{
 wp_set_current_user($other);lc(is_wp_error(GE_Logistics_UI::context('order',$id)),'Foreign customer denied');
 lc(logistics_act($id,'request',['address'=>$a,'method'=>'via_cargo'],$customer)===true,'Customer requests national quote, no price invented');
 wp_set_current_user($customer);$c=GE_Logistics_UI::context('order',$id);lc(!$c['state']['offers']&&$c['state']['status']==='quote_requested','National not operational from selector');lc(wc_get_order($id)->get_shipping_state()==='U','Province copied to order snapshot');
 lc(logistics_act($id,'plan',['address'=>$a,'packages'=>$rows,'measured'=>1,'address_reviewed'=>1],$other)!==true,'Other customer cannot plan');
 lc(logistics_act($id,'plan',['address'=>$a,'packages'=>$rows,'measured'=>1,'address_reviewed'=>1])===true,'Measured multibulto plan');
 $offer=['carrier'=>'via_cargo','price'=>'12345.67','scope'=>'Agencia QA 1 (destino confirmado)','eta'=>'3 a 5 días desde despacho · QA','basis'=>'Cotización sintética QA','expires'=>gmdate('Y-m-d',time()+86400),'coverage_verified'=>1];
 lc(logistics_act($id,'offer',$offer)===true,'Manual carrier option');wp_set_current_user(1);$c=GE_Logistics_UI::context('order',$id);$o=end($c['state']['offers']);lc($o['price_cents']===1234567,'ARS cents preserved');
 $revision=$c['state']['revision'];$key=wp_generate_uuid4();lc(logistics_act($id,'select',['offer_id'=>$o['id']],$customer,'order',$revision,$key)===true,'Customer accepts transport');
 $after=wc_get_order($id)->get_meta(GE_Logistics::META);lc(logistics_act($id,'select',['offer_id'=>$o['id']],$customer,'order',$revision,$key)===true,'Idempotent replay');lc(wc_get_order($id)->get_meta(GE_Logistics::META)['revision']===$after['revision'],'Replay no second revision');
 lc(logistics_act($id,'plan',['address'=>$a,'packages'=>$rows],1,'order',$revision)!==true,'Concurrent revision rejected');
 $before=wc_get_order($id);lc((float)$before->get_total()===100.0&&!$before->get_items('shipping'),'Transport quote does not alter accepted product accounting');
 $item=wc_get_order($id)->get_items('line_item');$item=reset($item);$item->set_quantity(1001);$item->save();wp_set_current_user(1);$c=GE_Logistics_UI::context('order',$id);lc(is_wp_error(GE_Logistics::offer_check(GE_Logistics_UI::chosen($c),$c['fingerprint'])),'Changed item quantity invalidates price');
 lc(logistics_act($id,'dispatch',['dispatch_confirmed'=>1,'tracking'=>'QA-GUIDE','payment_reference'=>'QA paid','transport_payment_checked'=>1])!==true,'Cannot dispatch stale option');
 lc(logistics_act($id,'offer',$offer)===true,'New quote after quantity change');wp_set_current_user(1);$c=GE_Logistics_UI::context('order',$id);$o=end($c['state']['offers']);lc(logistics_act($id,'select',['offer_id'=>$o['id']],$customer)===true,'Accept renewed quote');
 lc(logistics_act($id,'dispatch',['dispatch_confirmed'=>1,'tracking'=>'QA-GUIDE'])!==true,'Transport payment condition required');
 $dispatch=['dispatch_confirmed'=>1,'tracking'=>'QA-GUIDE','tracking_url'=>'https://viacargo.com.ar/','payment_reference'=>'Synthetic paid transport','transport_payment_checked'=>1];
 $fresh=wc_get_order($id);$fresh->update_meta_data('_ge_payment_state','pending');$fresh->save();lc(logistics_act($id,'dispatch',$dispatch)!==true,'Product payment gate');$fresh=wc_get_order($id);$fresh->update_meta_data('_ge_payment_state','paid');$fresh->update_meta_data('_ge_lifecycle_stage','produccion');$fresh->save();lc(logistics_act($id,'dispatch',$dispatch)!==true,'Product ready gate');$fresh=wc_get_order($id);$fresh->update_meta_data('_ge_lifecycle_stage','listo');$fresh->save();
 lc(logistics_act($id,'dispatch',$dispatch)===true,'Synthetic dispatch record');$fresh=wc_get_order($id);$s=$fresh->get_meta(GE_Logistics::META);lc($s['status']==='dispatched'&&!$fresh->get_meta('_ge_delivery_confirmed_at'),'Dispatch separate from delivered');
 lc(logistics_act($id,'request',['address'=>$a,'method'=>'pickup'],$customer)!==true,'Dispatched destination protected');lc(logistics_act($id,'incident',['incident'=>'Synthetic operational incident'])===true,'Staff incident');lc(logistics_act($id,'incident',['incident'=>'unsafe'],$customer)!==true,'Customer cannot write internal incidents');
 wp_set_current_user($customer);ob_start();GE_Logistics_UI::render_order(wc_get_order($id));$html=ob_get_clean();lc(strpos($html,'QA private origin')===false,'Origin never appears to customer');lc(strpos($html,'Synthetic operational incident')===false,'Internal incidents private');lc(strpos($html,'Seguimiento oficial')!==false,'Owner gets official tracking');
 $quote_id=wp_insert_post(['post_type'=>GE_WTP_Commercial_Quotes::POST_TYPE,'post_status'=>'private','post_title'=>'Logistics QA quote']);update_post_meta($quote_id,GE_WTP_Commercial_Quotes::CUSTOMER_META,$customer);update_post_meta($quote_id,GE_WTP_Commercial_Quotes::STATUS_META,'sent');update_post_meta($quote_id,GE_WTP_Commercial_Quotes::CURRENT_META,1);update_post_meta($quote_id,GE_WTP_Commercial_Quotes::VERSIONS_META,[1=>['items'=>[['title'=>'QA','quantity'=>1000]],'delivery'=>$a]]);
 lc(logistics_act($quote_id,'request',['address'=>$a,'method'=>'local'],$customer,'quote')===true,'Quote coordination saved independently');
 $new=wc_create_order(['customer_id'=>$customer]);GE_Logistics_UI::inherit(['id'=>$quote_id],$new);$new=wc_get_order($new->get_id());$s=$new->get_meta(GE_Logistics::META);lc($s['source_quote']===$quote_id&&$s['address']['postal_code']==='9100'&&!$s['offers'],'Quote preference inherited; order prices require review');
 wp_set_current_user(1);$c=GE_Logistics_UI::context('quote',$quote_id);$c['packages']=$rows;$c['state']['address_reviewed']=true;$c['config']['rates']=[['enabled'=>true,'province'=>'C','postcodes'=>['9100'],'price_cents'=>10000,'expires_at'=>time()+86400,'max_kg'=>50,'max_packages'=>10,'max_side_cm'=>100,'scope'=>'Local QA','eta'=>'QA','basis'=>'QA']];lc(!GE_Logistics_UI::fixed_offers($c),'CP in other province not treated as local');$c['config']['rates'][0]['province']='U';lc(count(GE_Logistics_UI::fixed_offers($c))===1,'Configured exact zone fits');$c['config']['rates'][0]['max_kg']=1;lc(!GE_Logistics_UI::fixed_offers($c),'Weight exceeds fixed tariff');$c['config']['rates'][0]['max_kg']=50;$c['config']['rates'][0]['expires_at']=time()-1;lc(!GE_Logistics_UI::fixed_offers($c),'Expired fixed tariff unavailable');
 lc(!get_option('ge_logistics_lock_order_'.$id),'Record lock released');
 lc(has_action('admin_post_nopriv_ge_order_logistics')===false,'No anonymous logistics writer');
 $org=get_option(GE_Organization::ROOT);$org[GE_Organization::PRIMARY]['members'][(string)$other]='read-only';update_option(GE_Organization::ROOT,$org,false);wp_set_current_user($other);lc(is_wp_error(GE_Logistics_UI::context('order',$id,true)),'Read-only organization actor cannot write');
 wp_set_current_user(1);lc(!is_wp_error(GE_Logistics_UI::context('order',$id,true)),'Authorized staff still has write access');
 echo 'PASS '.$checks." logistics WordPress checks\n";
}finally{wp_set_current_user(1);update_option(GE_Organization::ROOT,$org_original,false);if(false===$old)delete_option(GE_Logistics::CONFIG);else update_option(GE_Logistics::CONFIG,$old,false);}
