<?php
$wpLoad=getenv('GE_WP_LOAD');if(!$wpLoad||strpos($wpLoad,'/job-flow-qa-')===false)throw new Exception('Isolated QA required');require $wpLoad;
if(DB_NAME!=='graph_job_flow_20261007')throw new Exception('Wrong DB');
$context=json_decode(file_get_contents(dirname(dirname($wpLoad)).'/context.json'),true);wp_set_current_user(1);$checks=[];
function check_panel($ok,$name){global $checks;if(!$ok)throw new Exception($name);$checks[]=$name;}
$quote_before=get_post_meta($context['quote'],GE_WTP_Commercial_Quotes::VERSIONS_META,true);$request_before=get_post_meta($context['request'],GE_WTP_Quote_Requests::META,true);$order=wc_get_order($context['order']);$stage_before=GE_WTP_Order_Lifecycle::stage($order);
$legacy=wc_create_order(['customer_id'=>$context['customer']]);$legacy->update_meta_data(GE_WTP_Customer_Quotes::KEY_META,'qa-unified-legacy');$legacy->save();
$operational=wc_create_order(['customer_id'=>$context['customer']]);$operational->update_meta_data('_ge_lifecycle_stage','aprobado');$operational->update_meta_data('_ge_production_status','production');$operational->save();
$rows=GE_WTP_Work_Panel::rows();$chain=array_values(array_filter($rows,function($r)use($context){return $r['order_id']===$context['order']||$r['quote_id']===$context['quote']||$r['request_id']===$context['request'];}));
$legacy_rows=array_values(array_filter($rows,function($r)use($legacy){return $r['order_id']===$legacy->get_id();}));check_panel(count($legacy_rows)===1&&$legacy_rows[0]['kind']==='quotes','Legacy customer quote remains visible as a quote');
$op_rows=array_values(array_filter($rows,function($r)use($operational){return $r['order_id']===$operational->get_id();}));check_panel($op_rows[0]['kind']==='production'&&$op_rows[0]['status']==='En producción','Historical operational production marker displayed consistently');
check_panel(count($chain)===1,'Request quote and order collapse to one work');check_panel($chain[0]['kind']==='production'&&$chain[0]['closed'],'Delivered work categorized as closed production');check_panel($chain[0]['version']===1,'Preserved order version shown');
check_panel(!GE_WTP_Work_Panel::filter($chain,'','active',''),'Delivered work excluded from active filter');check_panel(count(GE_WTP_Work_Panel::filter($chain,'','closed',''))===1,'Closed filter retains delivered work');check_panel(count(GE_WTP_Work_Panel::filter($chain,'','all',(string)$context['request']))===1,'Search finds original request after conversion');
check_panel(!GE_WTP_Work_Panel::filter($chain,'requests','all',''),'Stage filters do not duplicate historical request');check_panel(count(GE_WTP_Work_Panel::filter($chain,'production','all',''))===1,'Production stage filter retains work');
$nav=GE_WTP_Gestion_V3::nav();check_panel(isset($nav['jobs'])&&!isset($nav['quotes'],$nav['requests'],$nav['orders'],$nav['production']),'One sidebar entry replaces four');check_panel(strpos(GE_WTP_Staff_Portal::portal_url('quotes'),'section=jobs')!==false,'Legacy list links enter shared panel');check_panel(strpos(GE_WTP_Staff_Portal::portal_url('quotes',['quote_id'=>$context['quote']]),'section=quotes')!==false,'Exact detail routes preserved');
$_GET=['section'=>'jobs','estado'=>'all','buscar'=>(string)$context['request']];ob_start();GE_WTP_Staff_Portal::render();$html=ob_get_clean();check_panel(substr_count($html,'class="ge-work-row"')===1,'Real renderer shows one matching work');check_panel(strpos($html,'Abrir trabajo')!==false&&strpos($html,'Próxima acción')!==false,'Panel exposes clear action and state');check_panel(strpos($html,'value="'.(string)$context['request'].'"')!==false,'Search persists across GET rendering');
$_GET=['section'=>'quotes','quote_id'=>$context['quote']];ob_start();GE_WTP_Staff_Portal::render();$detail=ob_get_clean();check_panel(strpos($detail,'ge-work-tabs')!==false&&strpos($detail,'Volver a todos los trabajos')!==false,'Existing detail stays in unified panel');
check_panel(get_post_meta($context['quote'],GE_WTP_Commercial_Quotes::VERSIONS_META,true)===$quote_before,'Navigation preserves quote snapshots');check_panel(get_post_meta($context['request'],GE_WTP_Quote_Requests::META,true)===$request_before,'Navigation preserves request');check_panel(GE_WTP_Order_Lifecycle::stage(wc_get_order($context['order']))===$stage_before,'Navigation never advances production');
$original=get_option(GE_Organization::ROOT);$limited=$original;$limited[GE_Organization::PRIMARY]['members']['1']='produccion';$role_filter=function()use(&$limited){return $limited;};add_filter('pre_option_'.GE_Organization::ROOT,$role_filter);
check_panel(GE_WTP_Work_Panel::accessible(),'Production role can enter unified panel');
$GLOBALS['wp_query']->is_page=true;$GLOBALS['wp_query']->queried_object=get_page_by_path('gestion');$_GET=['section'=>'jobs'];check_panel(is_page('gestion'),'Real page guard QA context');GE_Organization_Runtime::guard_page();check_panel(true,'Page guard accepts only accessible workspace');check_panel(!GE_WTP_Work_Panel::allowed('quotes'),'Production role cannot read quote module');$limited_rows=GE_WTP_Work_Panel::rows();check_panel(count(array_filter($limited_rows,function($r){return in_array($r['kind'],['quotes','requests'],true);}))===0,'Restricted panel omits commercial source contents');check_panel(count(array_filter($limited_rows,function($r)use($legacy){return $r['order_id']===$legacy->get_id();}))===0,'Legacy quote hidden from production role');
$_GET=['section'=>'jobs','tipo'=>'quotes'];ob_start();GE_WTP_Staff_Portal::render();$denied=ob_get_clean();check_panel(strpos($denied,'Tu rol no tiene acceso')!==false&&strpos($denied,'ge-work-row')===false,'Forged commercial filter denied');
foreach(['quotes','orders','production'] as $module)$limited[GE_Organization::PRIMARY]['settings']['modules'][$module]=false;check_panel(!GE_WTP_Work_Panel::accessible()&&!GE_WTP_Work_Panel::rows(),'Disabled modules close unified access');check_panel(!isset(GE_WTP_Gestion_V3::nav()['jobs']),'Unavailable workspace hidden from navigation');
$die_filter=function(){return function(){throw new RuntimeException('qa-access-denied');};};add_filter('wp_die_handler',$die_filter);$blocked=false;try{GE_Organization_Runtime::guard_page();}catch(RuntimeException $e){$blocked=$e->getMessage()==='qa-access-denied';}remove_filter('wp_die_handler',$die_filter);check_panel($blocked,'Real frontend guard rejects disabled workspace');remove_filter('pre_option_'.GE_Organization::ROOT,$role_filter);
$_GET=['section'=>'jobs','tipo'=>'production'];ob_start();GE_WTP_Staff_Portal::render();$tools=ob_get_clean();check_panel(strpos($tools,'Herramientas de producción')!==false&&strpos($tools,'view=events')!==false&&strpos($tools,'view=suppliers')!==false,'Existing production supplier and incident tools retained');
wp_set_current_user($context['customer']);check_panel(!GE_WTP_Work_Panel::accessible()&&!GE_WTP_Work_Panel::rows(),'Customer cannot read staff workspace');wp_set_current_user(1);
check_panel($original===get_option(GE_Organization::ROOT),'Role tests never persist permissions');
file_put_contents(dirname(dirname($wpLoad)).'/unified-results.json',json_encode(['checks'=>count($checks),'passed'=>$checks],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));echo 'PASS '.count($checks)." unified panel checks\n";
