<?php
define('ABSPATH',__DIR__);
function add_action(){} function add_filter(){} function get_page_by_path(){return (object)array('ID'=>81);} function get_post_meta($id=0,$key='', $single=true){return $key==='_ge_storefront_config'?GE_Volantes::config():array();} function wc_add_notice($message,$type){} define('OBJECT','OBJECT');
function wp_json_encode($value){return json_encode($value);}function apply_filters($tag,$value,...$args){return $tag==='ge_wtp_file_preflight_result'?GE_Volantes::preflight_result($value,...$args):$value;}
require __DIR__.'/../wp-content/mu-plugins/ge-volantes.php';
require __DIR__.'/../wp-content/plugins/ge-webtoprint-calculator/includes/class-ge-wtp-file-analysis.php';
require __DIR__.'/../wp-content/plugins/ge-webtoprint-calculator/includes/class-ge-wtp-storefront.php';
$count=0;function check($ok,$msg){global $count;if(!$ok)throw new Exception($msg);$count++;}
$config=GE_Volantes::config();$rows=GE_Volantes::matrix()['rows'];check(count($rows)===436,'436 verified configurations');
foreach($rows as $r){foreach(array('vertical','horizontal') as $orientation){$values=array($r['paper'],$r['size'],$orientation,$r['faces'],(string)$r['quantity']);$k=$config['option_map'][implode('|',$values)];$o=$config['options'][$k];$net=(int)ceil($r['supplier_net']*1.5);check($net===$o['total_net'],'exact authorized ceil');check(abs($o['price']*$r['quantity']-$net)<0.00001,'unit times quantity equals net');check(abs($o['price']*1.21*$r['quantity']-round($net*1.21,2))<0.005,'VAT final cents coherent');check($o['width_mm']*$o['height_mm']===array_product(array_map('intval',explode('x',$r['size'])))*100,'orientation preserves area');}}
check(GE_WTP_Storefront::minimum_price(81)>0,'manual quotes excluded from minimum');
$k=$config['option_map']['115|15x20|horizontal|double|1000'];$o=$config['options'][$k];check($o['total_net']===81000,'20x15 115g 1000 double =81000');check(round($o['price']*1000*1.21,2)===98010.0,'example 98010 with VAT');check($o['width_mm']===200&&$o['height_mm']===150,'20x15 horizontal dimensions');check(($o['width_mm']+10)===210&&($o['height_mm']+10)===160,'bleed210x160');check(($o['width_mm']-10)===190&&($o['height_mm']-10)===140,'safe190x140 with5mm each');
check(!isset($config['option_map']['150|15x20|horizontal|double|5000']),'150g only validated quantities');check(!isset($config['option_map']['115|20x45|vertical|double|30000']),'unavailable 30000 not sold');check(!isset($config['option_map']['115|50x70|vertical|single|30000']),'unavailable50x70 not sold');
check(GE_Volantes::validate_cart(true,81,1000,0,array(),array('ge_configuration_key'=>$k)),'valid lot');check(!GE_Volantes::validate_cart(true,81,999,0,array(),array('ge_configuration_key'=>$k)),'reject wrong quantity');check(!GE_Volantes::validate_cart(true,81,1000,0,array(),array('ge_configuration_key'=>'volantes-manual-otro-15x20-horizontal-double-1000')),'manual cannot buy');check(!GE_Volantes::validate_cart(true,81,1000,0,array(),array('ge_configuration_key'=>'forged')),'unknown key rejected');check(GE_Volantes::validate_cart(true,82,999),'other products preserved');
$c=GE_Volantes::defaults();foreach(array('2026-10-09T11:59:00-03:00'=>'2026-10-14','2026-10-09T12:00:00-03:00'=>'2026-10-16','2026-10-10T10:00:00-03:00'=>'2026-10-16','2026-10-11T10:00:00-03:00'=>'2026-10-16','2026-10-12T23:59:00-03:00'=>'2026-10-16','2026-10-13T00:00:00-03:00'=>'2026-10-21','2026-10-13T15:00:00-03:00'=>'2026-10-21','2026-10-14T00:00:00-03:00'=>'2026-10-21','2026-10-15T20:00:00-03:00'=>'2026-10-21','2026-10-16T11:59:00-03:00'=>'2026-10-21','2026-10-16T12:00:00-03:00'=>'2026-10-23') as $ready=>$date){check(GE_Volantes::dispatch($ready,'115',$c)['date']===$date,'cutoff '.$ready);}
$c['exceptions']=array('2026-10-21');check(GE_Volantes::dispatch('2026-10-13T15:00:00-03:00','115',$c)['date']===null,'holiday coordinates, not moved');check(GE_Volantes::dispatch('2026-10-13T15:00:00-03:00','80',$c)['date']===null,'80 no invented anchor');check(GE_Volantes::dispatch('2026-10-13T15:00:00-03:00','150',$c)['status']==='approximate','150 approximate15days');$c['weekly_confirmed']=false;check(GE_Volantes::dispatch('2026-10-13T15:00:00-03:00','115',$c)['date']===null,'unconfirmed calendar no date');
class PriceProduct{public $price;function set_price($price){$this->price=$price;}}class TestCart{public $items;function get_cart(){return $this->items;}}
$cart=new TestCart();$product=new PriceProduct();$cart->items=array(array('product_id'=>81,'ge_configuration_key'=>$k,'ge_base_price'=>81,'data'=>$product));GE_Volantes::cart_totals($cart);check(abs($product->price*1000-98010)<0.005,'cart exact final');$old=new PriceProduct();$old->price=94.0654;$cart->items=array(array('product_id'=>81,'ge_configuration_key'=>'offset-old','ge_base_price'=>77.74,'data'=>$old));GE_Volantes::cart_totals($cart);check($old->price===94.0654,'existing cart old keys unchanged');
class TestItem{public $meta=array();function add_meta_data($k,$v,$u){$this->meta[$k]=$v;}function get_meta($k,$single=true){return $this->meta[$k]??'';}}class TestProduct{function get_id(){return 81;}function get_slug(){return 'volantes-full-color';}}
$limitsItem=array('ge_configuration_key'=>$k,'quantity'=>1000);check(GE_Volantes::store_api_quantity(1,new TestProduct(),$limitsItem)===1000,'block cart fixed min max and multiple');check(GE_Volantes::store_api_editable(true,new TestProduct(),$limitsItem)===false,'block cart quantity not editable');check(GE_Volantes::store_api_quantity(1,new TestProduct(),array('ge_configuration_key'=>'offset-old'))===1,'historical quantity limits preserved');check(GE_Volantes::store_api_editable(true,new TestProduct(),array('ge_configuration_key'=>'offset-old'))===true,'historical editable unchanged');
class TestRouteException extends Exception{function __construct($code,$message,$status){parent::__construct($message);}}class_alias('TestRouteException','Automattic\\WooCommerce\\StoreApi\\Exceptions\\RouteException');GE_Volantes::store_api_validate(new TestProduct(),$limitsItem);check(true,'valid block cart lot');$limitsItem['quantity']=1001;try{GE_Volantes::store_api_validate(new TestProduct(),$limitsItem);check(false,'modified lot must fail');}catch(TestRouteException $e){check(true,'modified block lot rejected');}
$it=new TestItem();GE_Volantes::item_spec($it,'x',array('product_id'=>81,'ge_configuration_key'=>$k),null);$ctx=GE_Volantes::analysis_context(array(),$it,new TestProduct());check($ctx['target_dimensions_mm']===array(210,160),'snapshot full document210x160');check($ctx['cut_dimensions_mm']===array(200,150),'snapshot cut200x150');check($ctx['expected_pages']===2,'double2pages');check($ctx['paper']==='115','snapshot paper');
$assignment=GE_Volantes::production_assignment(null,$it,time());check($assignment['supplier']==='druck'&&$assignment['date']===''&&$assignment['requires_confirmation'],'new order no creation-based date');$historical=new TestItem();check(GE_Volantes::production_assignment(null,$historical,time())===null,'historical assignments not changed');check(GE_Volantes::analysis_context(array('x'=>1),$historical,new TestProduct())===array('x'=>1),'historical preflight unchanged');
$facts=array('page_count'=>2,'page_size_mm'=>array(210,160),'fonts_embedded'=>true,'colorspaces'=>array('DeviceCMYK'),'image_resolution_min_ppi'=>300,'explicit_boxes'=>array(array('page'=>1,'kind'=>'TrimBox','points'=>array(5*72/25.4,5*72/25.4,205*72/25.4,155*72/25.4)),array('page'=>1,'kind'=>'BleedBox','points'=>array(0,0,210*72/25.4,160*72/25.4))));$pf=GE_WTP_File_Analysis::preflight($facts,$ctx);$by=array_column($pf['checks'],'status','code');check($by['volantes_exact_file_dimensions']==='PASS','matching PDFfull dims');check($by['volantes_faces']==='PASS','matching faces');check($by['declared_bleed_page_1']==='PASS','declared5mm');check($by['actual_background_bleed']==='UNVERIFIED','background not falsely certified');check($by['font_size_6pt']==='UNVERIFIED','font6pt review pending');check($by['expected_color_mode']==='UNVERIFIED','CMYK presence not falsely certified');
$facts['page_size_mm']=array(220,170);$facts['page_count']=1;$facts['colorspaces']=array('DeviceRGB');$facts['image_resolution_min_ppi']=150;$pf=GE_WTP_File_Analysis::preflight($facts,$ctx);$by=array_column($pf['checks'],'status','code');check($by['volantes_exact_file_dimensions']==='WARNING','oversize PDF detected');check($by['volantes_faces']==='WARNING','double missing back detected');check($by['expected_color_mode']==='WARNING','RGB warns');check($by['placed_image_dpi']==='WARNING','150dpi warns');
$facts['mime_type']='image/png';$pf=GE_WTP_File_Analysis::preflight($facts,$ctx);check(array_column($pf['checks'],'status','code')['volantes_faces']==='UNVERIFIED','separate image faces need lot review');
echo json_encode(array('passed'=>$count,'rows'=>count($rows),'price_options'=>count($config['options']),'example_net'=>81000,'example_vat'=>17010,'example_final'=>98010,'historical_business_writes'=>0),JSON_PRETTY_PRINT)."\n";
