<?php defined( 'ABSPATH' ) || exit;
$data = self::data( $card ); $purchase = self::entitlement( get_current_user_id(), $card );
$published = $card && 'publish' === $card->post_status && 'yes' === get_post_meta( $card->ID, '_ge_card_consent', true ) && $purchase;
$labels = array( 'first_name' => 'Nombre', 'last_name' => 'Apellido', 'company' => 'Empresa o marca', 'role' => 'Actividad o cargo', 'email' => 'Email público', 'phone' => 'Teléfono público', 'website' => 'Web' );
$notice = sanitize_key( $_GET['saved'] ?? '' );
$messages = array( 'draft' => 'Borrador guardado. Tus datos siguen privados.', 'published' => 'Tu contacto ya está publicado y el QR conserva su enlace.', 'purchase' => 'Guardamos el borrador. Para publicarlo necesitás una compra válida de tarjetas físicas.' );
?>
<main class="gxc gxc-wrap gxc-editor"><a class="gxc-text-link" href="<?php echo esc_url( self::url() ); ?>">← Volver a Tarjetas</a><p class="gxc-kicker">Mi cuenta · Contacto digital</p><h1>Tu contacto.<br>Como querés compartirlo.</h1><p>Completá únicamente los datos que querés mostrar. No usamos automáticamente tus datos fiscales ni los de tu cuenta.</p>
    <?php if ( isset( $messages[$notice] ) ) : ?><p class="gxc-notice" role="status"><?php echo esc_html( $messages[$notice] ); ?></p><?php endif; ?>
    <?php $marketing_notice = sanitize_key( $_GET['marketing'] ?? '' ); if ( 'suppressed' === $marketing_notice ) : ?><p class="gxc-notice" role="status">Respetamos tu baja o restricción anterior. Guardar la tarjeta no te vuelve a suscribir.</p><?php elseif ( 'unavailable' === $marketing_notice ) : ?><p class="gxc-notice" role="status">Tu tarjeta se guardó. No pudimos actualizar las preferencias de email; podés revisarlas en Mi perfil.</p><?php elseif ( 'subscribed' === $marketing_notice ) : ?><p class="gxc-notice" role="status">Tu preferencia de recibir novedades por email quedó registrada.</p><?php endif; ?>
    <div class="gxc-editor-grid"><form class="gxc-contact-form" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" method="post"><input type="hidden" name="action" value="ge_customer_contact_card_save"><input type="hidden" name="card_id" value="<?php echo $card ? absint( $card->ID ) : 0; ?>"><input type="hidden" name="revision" value="<?php echo $card ? absint( get_post_meta( $card->ID, '_ge_card_revision', true ) ) : 0; ?>"><?php wp_nonce_field( 'ge_customer_contact_card_save' ); ?>
    <div class="gxc-form-fields"><?php foreach ( $labels as $key => $label ) : $type = 'email' === $key ? 'email' : ( 'website' === $key ? 'url' : ( 'phone' === $key ? 'tel' : 'text' ) ); ?><label for="gxc-<?php echo esc_attr( $key ); ?>"><span><?php echo esc_html( $label ); ?><?php if ( 'first_name' === $key ) { echo ' *'; } ?></span><input id="gxc-<?php echo esc_attr( $key ); ?>" name="<?php echo esc_attr( $key ); ?>" type="<?php echo esc_attr( $type ); ?>" maxlength="<?php echo 'website' === $key ? '300' : ( 'email' === $key ? '254' : ( 'phone' === $key ? '32' : '120' ) ); ?>" value="<?php echo esc_attr( $data[$key] ); ?>" <?php if ( 'first_name' === $key ) { echo 'required'; } ?> <?php if ( 'website' === $key ) { echo 'placeholder="https://tu-web.com"'; } ?>></label><?php endforeach; ?></div>
    <fieldset><legend>Quién puede verlo</legend><label class="gxc-choice"><input type="radio" name="visibility" value="draft" <?php checked( ! $published ); ?>> Guardar como borrador privado o retirar la publicación</label><label class="gxc-choice"><input type="radio" name="visibility" value="publish" <?php checked( (bool) $published ); ?>> Publicar mi contacto</label><label class="gxc-choice"><input type="checkbox" name="public_consent" value="1"> Autorizo que estos datos se vean públicamente mediante mi enlace y QR. Revisé los campos que elegí compartir.</label></fieldset><fieldset><legend>Novedades por email · opcional</legend><label class="gxc-choice"><input type="checkbox" name="card_email_marketing" value="1"> <?php echo esc_html( self::MARKETING_TEXT ); ?></label><p class="gxc-note">Usamos el email de tu cuenta. Crear y publicar tu tarjeta no depende de esta opción. Los mensajes necesarios para tu cuenta y pedidos se gestionan por separado. Guardar sin marcar conserva tus preferencias actuales.</p><a class="gxc-text-link" href="<?php echo esc_url( GE_WTP_Portal::portal_url( 'perfil' ) ); ?>">Administrar mis preferencias y bajas</a></fieldset><button class="gxc-button gxc-primary" type="submit">Guardar cambios →</button></form>
    <aside class="gxc-editor-aside"><span class="gxc-label"><?php echo $published ? 'Perfil publicado' : 'Borrador privado'; ?></span><h2>Vista previa</h2>
    <article class="gxc-mini-contact" data-contact-preview aria-label="Vista previa privada del contacto"><strong data-preview-name><?php echo esc_html( trim( $data['first_name'] . ' ' . $data['last_name'] ) ?: 'Tu nombre' ); ?></strong><?php foreach ( array( 'company', 'role', 'email', 'phone', 'website' ) as $key ) : ?><p data-preview="<?php echo esc_attr( $key ); ?>" <?php if ( ! $data[$key] ) { echo 'hidden'; } ?>><?php echo esc_html( $data[$key] ); ?></p><?php endforeach; ?></article>
    <p class="gxc-note">Los cambios de esta vista previa siguen privados hasta que guardes y autorices la publicación.</p>
    <p>Tu tarjeta digital está incluida con una compra válida de tarjetas físicas. Podés preparar el borrador antes de comprar.</p>
    <?php if ( $published ) : $public_url = self::public_url( $card ); ?>
    <img src="<?php echo esc_url( self::qr_download_url( $card, 'qr.svg' ) ); ?>" width="180" height="180" alt="QR de tu contacto publicado"><p class="gxc-destination">Destino: <a href="<?php echo esc_url( $public_url ); ?>" target="_blank" rel="noopener"><?php echo esc_html( $public_url ); ?></a></p>
    <div class="gxc-actions"><a href="<?php echo esc_url( self::qr_download_url( $card, 'qr.svg' ) ); ?>">Descargar QR vectorial</a><a href="<?php echo esc_url( self::qr_download_url( $card, 'qr.png' ) ); ?>">Descargar QR en PNG</a><a href="<?php echo esc_url( $public_url . 'contacto.vcf' ); ?>">Contacto .vcf</a></div><p class="gxc-note">Descargá el QR y subilo a tu diseño en Canva. Al actualizar tus datos conservás el enlace. Retirar la publicación desactiva el destino.</p>
    <?php else : ?><p>El QR final se habilita después de confirmar la compra y publicar el perfil. Así nunca imprimís un QR con un destino sin activar.</p><a class="gxc-button gxc-outline" href="<?php echo esc_url( get_permalink( 83 ) ); ?>">Volver a Tarjetas Express →</a><?php endif; ?>
    <hr><p class="gxc-note">Para imprimir el QR, usá negro sobre blanco, conservá cuatro módulos de margen blanco y probalo a tamaño final. Preparalo idealmente a 25 × 25 mm; revisamos su lectura junto al archivo exacto antes de producir.</p></aside></div>
</main>