<?php defined( 'ABSPATH' ) || exit;
$asset = content_url( '/mu-plugins/ge-business-cards/' );
$express = get_permalink( 83 ); $offset = get_permalink( 78 );
?>
<main id="ge-cards-main" class="gxc">
    <section class="gxc-hero gxc-wrap">
        <div class="gxc-hero-copy"><p class="gxc-kicker">Tu próxima buena impresión</p><h1>Una tarjeta.<br>Muchas <span>conexiones.</span></h1><p class="gxc-lead">Presentate con tarjetas que se sienten bien en la mano. Sumá un QR para que tu contacto siga disponible, incluso después de guardarlas.</p><div class="gxc-actions"><a class="gxc-button gxc-primary" href="#elegi-tus-tarjetas">Elegir mis tarjetas <span aria-hidden="true">↗</span></a><a class="gxc-text-link" href="<?php echo esc_url( self::url( 'demo/' ) ); ?>">Ver la tarjeta digital →</a></div><p class="gxc-note">Impresión física + contacto digital incluido con tu compra.</p></div>
        <figure class="gxc-hero-image"><img src="<?php echo esc_url( $asset . 'tarjetas-personales.webp' ); ?>" width="1200" height="1200" alt="Tarjetas Graphex, frente blanco y dorso oscuro, sobre una superficie cálida" fetchpriority="high"><figcaption>Tu marca, por los dos lados.</figcaption></figure>
    </section>
    <div class="gxc-strip"><div class="gxc-wrap"><span>Full color</span><span>Frente o doble faz</span><span>Papeles y laminados</span><span>Contacto digital + QR</span></div></div>
    <section class="gxc-wrap gxc-section" id="elegi-tus-tarjetas"><div class="gxc-section-heading"><p class="gxc-kicker">Elegí cómo empezar</p><h2>Para tu primer encuentro.<br>Y para los próximos mil.</h2><p>Configurá el formato, la impresión y la cantidad. El precio se calcula en la ficha del producto.</p></div><div class="gxc-product-grid">
        <article class="gxc-product"><span class="gxc-label">Tiradas cortas</span><h3>Tarjetas Express</h3><p class="gxc-big">100–500 <small>unidades</small></p><p>Formato 90 × 50 mm. Papel ilustración de 300 o 350 g, impresión al frente o doble faz y opciones de laminado mate o brillante.</p><a class="gxc-button gxc-primary" href="<?php echo esc_url( $express ); ?>">Configurar Express →</a><p class="gxc-note">Consultá el plazo confirmado para tu combinación.</p></article>
        <article class="gxc-product gxc-product-dark"><span class="gxc-label">Para llegar a más personas</span><h3>Tarjetas personales</h3><p class="gxc-big">Desde 1.000 <small>unidades</small></p><p>Impresión full color sobre ilustración mate de 350 g, con laminado brillante al frente. Elegí la medida y la impresión en el configurador.</p><a class="gxc-button gxc-yellow" href="<?php echo esc_url( $offset ); ?>">Configurar personales →</a><p class="gxc-note">Para una medida especial, pedinos una cotización.</p></article>
    </div></section>
    <section class="gxc-digital"><div class="gxc-wrap gxc-digital-grid"><div><p class="gxc-kicker">El contacto sigue, aunque cambien tus datos</p><h2>La tarjeta se entrega.<br>La conexión <span>queda.</span></h2><p class="gxc-lead">Tu QR abre una página de contacto alojada en Graphex. Tus clientes pueden guardar el contacto en su teléfono. Vos podés actualizar los datos conservando el mismo enlace.</p><ul class="gxc-benefits"><li>Incluida con la compra de tarjetas físicas.</li><li>Se prepara y administra desde tu cuenta.</li><li>Sólo se hacen públicos los datos que elegís y autorizás.</li></ul><div class="gxc-actions"><a class="gxc-button gxc-yellow" href="<?php echo esc_url( self::url( 'mi-vcard/' ) ); ?>">Preparar mi tarjeta digital →</a><a class="gxc-text-link" href="<?php echo esc_url( self::url( 'demo/' ) ); ?>">Probar un ejemplo</a></div><p class="gxc-note">La publicación se activa con una compra válida. El QR se incorpora al diseño y se revisa antes de imprimir.</p></div><a class="gxc-contact-preview" href="<?php echo esc_url( self::url( 'demo/' ) ); ?>" aria-label="Ver ejemplo de tarjeta digital"><span class="gxc-preview-status">Ejemplo de contacto digital</span><div class="gxc-avatar">AE</div><h3>Alex Ejemplo</h3><p>Diseño y comunicación<br>Estudio Ejemplo</p><span class="gxc-preview-save">Guardar contacto <span aria-hidden="true">↓</span></span><div class="gxc-preview-qr"><img src="<?php echo esc_url( self::url( 'demo/qr.svg' ) ); ?>" width="140" height="140" alt="QR hacia la muestra de contacto"><span>Escaneá.<br>Conectá.<br>Guardá.</span></div></a></div></section>
    <section class="gxc-wrap gxc-section"><div class="gxc-section-heading"><p class="gxc-kicker">Del diseño a tu bolsillo</p><h2>Tu idea, lista para imprimir.</h2></div><ol class="gxc-steps"><li><span>01</span><h3>Elegí tu tarjeta</h3><p>Definí cantidad, papel e impresión en el configurador.</p></li><li><span>02</span><h3>Subí o diseñá</h3><p>Cargá tu archivo o abrí el catálogo de Canva. Descargá el PDF para impresión y adjuntalo al producto.</p></li><li><span>03</span><h3>Revisá y comprá</h3><p>Tu archivo queda vinculado al pedido. Revisamos la versión exacta y la aprobación antes de producir.</p></li></ol><div class="gxc-file-panel"><div><h3>¿Diseñás una tarjeta de 5 × 9 cm?</h3><p>Lienzo 95 × 65 mm · corte 90 × 50 mm · área segura 80 × 40 mm.<br>Para doble faz, frente y dorso en dos páginas.</p></div><div class="gxc-actions"><a class="gxc-button gxc-outline" href="<?php echo esc_url( $asset . 'plantilla-tarjetas-95x65.pdf' ); ?>" download>Descargar plantilla</a><a class="gxc-text-link" href="<?php echo esc_url( $asset . 'guia-tarjetas-graphex.pdf' ); ?>">Ver guía →</a></div></div></section>
    <section class="gxc-wrap gxc-section gxc-last"><p class="gxc-kicker">Hagamos la próxima conexión</p><h2>Tu marca merece<br>una buena presentación.</h2><div class="gxc-actions"><a class="gxc-button gxc-primary" href="<?php echo esc_url( $express ); ?>">Configurar y subir mi archivo →</a><a class="gxc-button gxc-outline" href="https://www.canva.com/s/templates?query=&amp;adj=eyJFIjp7IkEiOiJ0QUNaQ3NIdzBwQSJ9fQ" target="_blank" rel="noopener noreferrer">Elegir diseño en Canva ↗</a></div></section>
</main>
