<?php
/** Run via wp eval-file in an isolated QA WordPress as an authorized administrator. */
$checks=0;
$assert=function($ok,$message) use(&$checks) { if(!$ok) throw new RuntimeException('FAIL: '.$message); $checks++; };
$reject=function($fn,$message) use($assert) { $caught=false; try { $fn(); } catch(Throwable $e) { $caught=true; } $assert($caught,$message); };
$rollback='finance-qa-rollback-'.wp_generate_uuid4();
try {
    GE_WTP_Operations::transaction(function() use($assert,$reject,$rollback) {
        global $wpdb;
        $day=current_time('Y-m-d'); $key='finance-qa-'.wp_generate_uuid4();
        $income=array('amount_minor'=>5000,'currency'=>'USD','received_on'=>$day,'idempotency_key'=>$key.'-income','reference'=>'QA income');
        $in=GE_WTP_Operations_Finance::income_record($income); $in2=GE_WTP_Operations_Finance::income_record($income);
        $assert($in['id']===$in2['id'] && $in2['replayed'],'income replay');
        $income['type']='refund';$income['amount_minor']=2000;$income['idempotency_key']=$key.'-refund';
        $refund=GE_WTP_Operations_Finance::income_record($income);
        $assert((int)$wpdb->get_var($wpdb->prepare('SELECT amount_minor FROM '.GE_WTP_Operations::table('finance_entries').' WHERE entry_type=%s AND source_id=%d','refund',$refund['id']))===-2000,'refund is negative ledger cash');
        $payload=array('amount_minor'=>12345,'currency'=>'ARS','incurred_on'=>$day,'description'=>'QA expense','idempotency_key'=>$key,'category'=>'qa');
        $first=GE_WTP_Operations_Finance::expense_create($payload);
        $second=GE_WTP_Operations_Finance::expense_create($payload);
        $assert($first['id']===$second['id'] && $second['replayed'],'expense replay');
        $assert($first['payable_id']>0 && $first['payable_id']===$second['payable_id'],'expense payable replay');
        $assert((int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.GE_WTP_Operations::table('finance_entries').' WHERE entry_type=%s AND source_id=%d','payable',$first['payable_id']))===0,'expense obligation never recognizes costs twice');
        $reject(function() use($payload) { $payload['amount_minor']=99; GE_WTP_Operations_Finance::expense_create($payload); },'expense conflict');
        $reject(function() use($payload) { $payload['amount_minor']=1.5; GE_WTP_Operations_Finance::expense_create($payload); },'reject fractional cents');
        $entry=$wpdb->get_var($wpdb->prepare('SELECT id FROM '.GE_WTP_Operations::table('finance_entries').' WHERE entry_type=%s AND source_id=%d','expense',$first['id']));
        GE_WTP_Operations_Finance::reverse(array('entry_id'=>$entry,'date'=>$day,'reason'=>'QA reversal'));
        $assert((int)$wpdb->get_var($wpdb->prepare('SELECT SUM(amount_minor) FROM '.GE_WTP_Operations::table('finance_entries').' WHERE id=%d OR reverses_id=%d',$entry,$entry))===0,'immutable reversal nets to zero');
        $reject(function() use($entry,$day) { GE_WTP_Operations_Finance::reverse(array('entry_id'=>$entry,'date'=>$day,'reason'=>'duplicate')); },'duplicate reversal rejected');
        // Reuse an existing mapping when available; this never edits supplier fiches.
        $supplier_ids=array_keys(GE_WTP_Operations::suppliers()); $supplier_id=(int)($supplier_ids[0]??0);
        $ok=$wpdb->insert(GE_WTP_Operations::table('payables'),array('supplier_id'=>$supplier_id?:1,'source_type'=>'qa','source_ref'=>$key,'order_id'=>0,'amount_minor'=>10000,'currency'=>'ARS','incurred_on'=>$day,'description'=>'QA payable','created_at'=>current_time('mysql',true)));
        $assert($ok!==false,'payable fixture'); $pid=(int)$wpdb->insert_id;
        $wpdb->insert(GE_WTP_Operations::table('finance_entries'),array('entry_type'=>'payable','source_id'=>$pid,'amount_minor'=>10000,'currency'=>'ARS','entry_date'=>$day,'created_at'=>current_time('mysql',true)));
        $pay=array('payable_id'=>$pid,'amount_minor'=>4000,'currency'=>'ARS','paid_on'=>$day,'idempotency_key'=>$key.'-payment','method'=>'transfer');
        $p=GE_WTP_Operations_Finance::payment_record($pay); $p2=GE_WTP_Operations_Finance::payment_record($pay); $assert($p['id']===$p2['id'],'payment replay');
        $reject(function() use($pay) { $pay['amount_minor']=7000; $pay['idempotency_key'].='-other'; GE_WTP_Operations_Finance::payment_record($pay); },'overpayment rejected');
        $reject(function() use($pay) { $pay['amount_minor']=3000; GE_WTP_Operations_Finance::payment_record($pay); },'payment conflict');
        $rows=GE_WTP_Operations_Finance::payables(array('status'=>'partial','category'=>'')); $fixture=null; foreach($rows as $row) if((int)$row['id']===$pid) $fixture=$row;
        $assert($fixture && $fixture['outstanding_minor']===6000,'partial balance');
        // Actual WooCommerce order and direct stock fixtures remain inside rollback.
        // The parent QA runner disables all outbound email and integrations.
        $order=new WC_Order(); $order->set_currency('ARS'); $order->set_total('100.00'); $order->set_status('pending'); $order->save();
        $oid=$order->get_id();
        $labor=GE_WTP_Operations_Finance::order_cost_save(array('order_id'=>$oid,'amount_minor'=>1000,'currency'=>'ARS','incurred_on'=>$day,'category'=>'labor','description'=>'QA labor','idempotency_key'=>$key.'-labor'));
        GE_WTP_Operations_Finance::order_cost_save(array('order_id'=>$oid,'amount_minor'=>5000,'currency'=>'ARS','incurred_on'=>$day,'category'=>'materials','description'=>'QA material estimate','idempotency_key'=>$key.'-materials'));
        $assert(GE_WTP_Operations_Finance::order_margin($oid)['margin_minor']===null,'unverified costs stay incomplete');
        $ok=$wpdb->insert(GE_WTP_Operations::table('stock_moves'),array('item_id'=>0,'order_id'=>$oid,'movement_type'=>'consumption','quantity'=>'2.5000','unit_cost'=>'10.1250','currency'=>'ARS','idempotency_key'=>$key.'-move','fingerprint'=>hash('sha256',$key),'actor_id'=>get_current_user_id(),'created_at'=>current_time('mysql',true)));
        $assert($ok!==false,'material fixture'); $move=(int)$wpdb->insert_id;
        GE_WTP_Operations_Finance::costs_complete(array('order_id'=>$oid,'complete'=>true,'reason'=>'QA verified complete costs'));
        $margin=GE_WTP_Operations_Finance::order_margin($oid);
        $assert($margin['margin_minor']===6469 && $margin['stock_material_costs']['known_minor']===2531,'margin uses rounded stock cost and excludes duplicate manual materials');
        $wpdb->update(GE_WTP_Operations::table('stock_moves'),array('unit_cost'=>null),array('id'=>$move));
        $assert(GE_WTP_Operations_Finance::order_margin($oid)['margin_minor']===null,'missing material cost defeats verified completeness');
        $wpdb->update(GE_WTP_Operations::table('stock_moves'),array('unit_cost'=>'10.1250','currency'=>'USD'),array('id'=>$move));
        $assert(GE_WTP_Operations_Finance::order_margin($oid)['margin_minor']===null,'USD material cannot combine with ARS sale');
        $wpdb->update(GE_WTP_Operations::table('stock_moves'),array('currency'=>'ARS'),array('id'=>$move));
        GE_WTP_Operations_Finance::payment_record(array('payable_id'=>$labor['payable_id'],'amount_minor'=>400,'currency'=>'ARS','paid_on'=>$day,'idempotency_key'=>$key.'-labor-partial'));
        $rows=GE_WTP_Operations_Finance::expense_list(array('from'=>$day,'to'=>$day,'order_id'=>$oid,'status'=>'partial'));
        $assert(count($rows)===1 && (int)$rows[0]['id']===$labor['id'] && $rows[0]['outstanding_minor']===600,'expense partial payment linked status');
        GE_WTP_Operations_Finance::payment_record(array('payable_id'=>$labor['payable_id'],'amount_minor'=>600,'currency'=>'ARS','paid_on'=>$day,'idempotency_key'=>$key.'-labor-full'));
        $rows=GE_WTP_Operations_Finance::expense_list(array('from'=>$day,'to'=>$day,'order_id'=>$oid,'status'=>'paid'));
        $assert(count($rows)===1 && $rows[0]['outstanding_minor']===0 && $rows[0]['paid_minor']===1000,'expense fully paid status');
        $order=wc_get_order($oid);$order->set_status('processing');$order->set_customer_id(get_current_user_id());$order->save();
        $report=GE_WTP_Operations_Finance::report(array('from'=>$day,'to'=>$day,'order_id'=>$oid,'category'=>'labor','supplier_id'=>0,'customer_id'=>get_current_user_id()));
        $assert(count($report['expense_groups']['category'])===1 && $report['expense_groups']['category'][0]['amount_minor']===1000 && $report['expense_groups']['supplier'][0]['group']==='0','report groups net expense by category and unassigned supplier');
        $assert($report['margins']['order_count']===1 && $report['margins']['currencies'][0]['complete_count']===1 && $report['margins']['currencies'][0]['complete_margin_minor']===6469,'report cohort keeps complete full-order margin');
        $assert($report['accounts_receivable']['status']==='unknown' && $report['accounts_receivable']['outstanding_minor']===null && $report['operating_estimate']['status']==='partial_cost_coverage','receivable unknown and operating estimate labelled partial');
        $wpdb->update(GE_WTP_Operations::table('stock_moves'),array('unit_cost'=>null),array('id'=>$move));
        $report=GE_WTP_Operations_Finance::report(array('from'=>$day,'to'=>$day,'order_id'=>$oid));
        $assert($report['margins']['currencies'][0]['incomplete_count']===1 && $report['margins']['currencies'][0]['complete_margin_minor']===null,'report never invents complete margin for missing costs');
        $assert($report['margins']['currencies'][0]['operating_estimate_minor']===null && $report['margins']['currencies'][0]['known_order_costs_minor']===1000,'incomplete cohort with known costs keeps operating estimate unavailable');
        $wpdb->update(GE_WTP_Operations::table('stock_moves'),array('unit_cost'=>'10.1250'),array('id'=>$move));
        $report=GE_WTP_Operations_Finance::report(array('from'=>$day,'to'=>$day,'order_id'=>$oid,'category'=>'not_this_order'));
        $assert($report['margins']['order_count']===0 && !$report['expense_groups']['category'],'report category filter does not widen scope');
        GE_WTP_Operations_Finance::expense_create(array('amount_minor'=>800,'currency'=>'USD','incurred_on'=>$day,'description'=>'QA supplier operating expense','category'=>'qa_spend','idempotency_key'=>$key.'-supplier-expense'));
        $wpdb->insert(GE_WTP_Operations::table('payables'),array('supplier_id'=>0,'source_type'=>'receipt','source_ref'=>$key.'-supplier-purchase','amount_minor'=>2500,'currency'=>'USD','incurred_on'=>$day,'description'=>'QA acquisition','category'=>'qa_spend','created_at'=>current_time('mysql',true)));$purchase_id=(int)$wpdb->insert_id;
        $wpdb->insert(GE_WTP_Operations::table('finance_entries'),array('entry_type'=>'payable','source_id'=>$purchase_id,'amount_minor'=>2500,'currency'=>'USD','entry_date'=>$day,'created_at'=>current_time('mysql',true)));$purchase_entry=(int)$wpdb->insert_id;
        $spend=GE_WTP_Operations_Finance::report(array('from'=>$day,'to'=>$day,'supplier_id'=>0,'category'=>'qa_spend'))['supplier_spend'];
        $assert(count($spend)===1 && $spend[0]['currency']==='USD' && $spend[0]['purchases_minor']===2500 && $spend[0]['expenses_minor']===800 && $spend[0]['total_minor']===3300,'supplier spend combines separate acquisition and operating recognition');
        GE_WTP_Operations_Finance::reverse(array('entry_id'=>$purchase_entry,'date'=>$day,'reason'=>'QA acquisition reversal'));
        $spend=GE_WTP_Operations_Finance::report(array('from'=>$day,'to'=>$day,'supplier_id'=>0,'category'=>'qa_spend'))['supplier_spend'];
        $assert(count($spend)===1 && $spend[0]['purchases_minor']===0 && $spend[0]['expenses_minor']===800 && $spend[0]['total_minor']===800,'supplier spend respects reversals without removing expenses');
        $base_move=array('item_id'=>0,'order_id'=>$oid,'quantity'=>'1.0000','unit_cost'=>'10.0000','currency'=>'ARS','fingerprint'=>hash('sha256',$key.'-return'),'actor_id'=>get_current_user_id(),'created_at'=>current_time('mysql',true));
        $wpdb->insert(GE_WTP_Operations::table('stock_moves'),array_merge($base_move,array('movement_type'=>'return_in','idempotency_key'=>$key.'-return-in')));$return_id=(int)$wpdb->insert_id;
        $m=GE_WTP_Operations_Finance::order_margin($oid);
        $assert($m['stock_material_costs']['known_minor']===1531 && $m['margin_minor']===7469,'unused material return subtracts exact job material cost');
        $wpdb->insert(GE_WTP_Operations::table('stock_moves'),array_merge($base_move,array('movement_type'=>'writeoff','quantity'=>'0.5000','idempotency_key'=>$key.'-writeoff')));
        $wpdb->insert(GE_WTP_Operations::table('stock_moves'),array_merge($base_move,array('movement_type'=>'return_supplier','quantity'=>'9.0000','idempotency_key'=>$key.'-return-supplier')));
        $m=GE_WTP_Operations_Finance::order_margin($oid);
        $assert($m['stock_material_costs']['known_minor']===2031 && $m['margin_minor']===6969,'writeoff adds job cost while supplier return has no automatic job credit');
        $wpdb->update(GE_WTP_Operations::table('stock_moves'),array('unit_cost'=>null),array('id'=>$return_id));
        $m=GE_WTP_Operations_Finance::order_margin($oid);
        $assert($m['margin_minor']===null && in_array($return_id,$m['stock_material_costs']['unknown_movement_ids'],true),'unknown unused-return valuation keeps margin incomplete');
        $legacy_order=new WC_Order();$legacy_order->set_currency('ARS');$legacy_order->set_total('100.00');$legacy_order->set_status('processing');
        $supplier_key=$wpdb->get_var($wpdb->prepare('SELECT supplier_key FROM '.GE_WTP_Operations::table('supplier_refs').' WHERE id=%d',$supplier_id));
        $assert($supplier_id>0 && $supplier_key && GE_WTP_Operations::supplier_exists($supplier_id),'existing supplier fixture mapping');
        $legacy_order->update_meta_data('_ge_supplier_payables',array($supplier_key=>array('amount'=>'50.00','currency'=>'ARS','due_date'=>$day)));$legacy_order->save();$legacy_oid=$legacy_order->get_id();
        GE_WTP_Operations_Finance::costs_complete(array('order_id'=>$legacy_oid,'complete'=>true,'reason'=>'QA legacy-only source verified'));
        $legacy_margin=GE_WTP_Operations_Finance::order_margin($legacy_oid);
        $assert($legacy_margin['margin_minor']===5000 && $legacy_margin['legacy_supplier_costs']['status']==='known_readonly','legacy-only known cost supports verified margin without ledger import');
        $supplier_cost=array('order_id'=>$legacy_oid,'supplier_id'=>$supplier_id,'amount_minor'=>2500,'currency'=>'ARS','incurred_on'=>$day,'due_on'=>$day,'description'=>'QA supplier work','idempotency_key'=>$key.'-supplier-work');
        $work=GE_WTP_Operations_Finance::supplier_work_cost_create($supplier_cost);$work2=GE_WTP_Operations_Finance::supplier_work_cost_create($supplier_cost);
        $assert($work['id']===$work2['id'] && $work2['replayed'],'supplier work payable replay');
        $reject(function() use($supplier_cost){$supplier_cost['amount_minor']=2600;GE_WTP_Operations_Finance::supplier_work_cost_create($supplier_cost);},'supplier work idempotency conflict');
        GE_WTP_Operations_Finance::payment_record(array('payable_id'=>$work['id'],'amount_minor'=>1000,'currency'=>'ARS','paid_on'=>$day,'idempotency_key'=>$key.'-supplier-work-pay'));
        $work_rows=GE_WTP_Operations_Finance::payables(array('order_id'=>$legacy_oid,'supplier_id'=>$supplier_id,'status'=>'partial'));
        $assert(count($work_rows)===1 && $work_rows[0]['outstanding_minor']===1500,'supplier work partial payment');
        GE_WTP_Operations_Finance::costs_complete(array('order_id'=>$legacy_oid,'complete'=>true,'reason'=>'QA ambiguity cannot be overridden'));
        $legacy_margin=GE_WTP_Operations_Finance::order_margin($legacy_oid);
        $assert($legacy_margin['margin_minor']===null && $legacy_margin['legacy_supplier_costs']['status']==='ambiguous_overlap','legacy and new supplier cost overlap remains incomplete');
        $year=GE_WTP_Operations_Finance::summary(array('year'=>2024));
        $assert($year['from']==='2024-01-01' && $year['to']==='2024-12-31' && $year['previous']['from']==='2023-01-01' && $year['previous']['to']==='2023-12-31','full year and exact previous year including leap year');
        $month=GE_WTP_Operations_Finance::summary(array('year'=>2024,'month'=>3));
        $assert($month['from']==='2024-03-01' && $month['to']==='2024-03-31' && $month['previous']['from']==='2024-02-01' && $month['previous']['to']==='2024-02-29','month comparative preserves complete leap February');
        throw new RuntimeException($rollback);
    });
} catch(Throwable $e) { if($e->getMessage()!==$rollback) throw $e; }
echo 'Finance QA: '.$checks." checks passed; fixture transaction rolled back.\n";
