(()=>{'use strict';
let mapsPromise;
function loadMaps(){if(window.google?.maps?.importLibrary)return Promise.resolve();if(mapsPromise)return mapsPromise;mapsPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(window.geLogisticsMaps.key)+'&loading=async&libraries=places&v=weekly&language=es&region=AR';script.onload=resolve;script.onerror=reject;document.head.append(script);});return mapsPromise;}
function field(root,key){return root.querySelector('[data-address-field="'+key+'"]');}
document.addEventListener('click',async e=>{const add=e.target.closest('[data-ge-add-package]');if(add){const form=add.closest('form'),list=form.querySelector('[data-ge-packages]');if(list.children.length>=20)return;const next=Date.now();list.insertAdjacentHTML('beforeend',form.querySelector('template').innerHTML.replaceAll('__INDEX__',String(next)));return;}
const remove=e.target.closest('[data-ge-remove-package]');if(remove){remove.closest('fieldset').remove();return;}
const search=e.target.closest('[data-ge-maps-search]');if(!search||!window.geLogisticsMaps)return;search.disabled=true;const root=search.closest('[data-ge-logistics-address]');try{await loadMaps();const {PlaceAutocompleteElement}=await google.maps.importLibrary('places');const widget=new PlaceAutocompleteElement({includedRegionCodes:['ar']});widget.setAttribute('aria-label','Buscar dirección en Google Maps');root.querySelector('[data-ge-maps-slot]').append(widget);widget.addEventListener('gmp-select',async({placePrediction})=>{try{const place=placePrediction.toPlace();await place.fetchFields({fields:['addressComponents','id']});const components=place.addressComponents||[];const value=(type,short=false)=>{const c=components.find(c=>c.types.includes(type));return c?(short?c.shortText:c.longText):'';};if(value('country',true)!=='AR')return;field(root,'street').value=[value('route'),value('street_number')].filter(Boolean).join(' ');field(root,'city').value=value('locality')||value('administrative_area_level_2');field(root,'postal_code').value=value('postal_code');const province=value('administrative_area_level_1',true);const select=field(root,'province');const option=[...(select.options||[])].find(o=>o.value===province||o.textContent===value('administrative_area_level_1')||(province==='CABA'&&o.value==='C'));select.value=select.tagName==='SELECT'?(option?.value||''):value('administrative_area_level_1');field(root,'place_id').value=place.id||'';}catch{root.querySelector('[data-ge-maps-slot]').insertAdjacentHTML('beforeend','<p role="alert">No pudimos completar la dirección. Podés ingresarla manualmente.</p>');}});}catch{root.querySelector('[data-ge-maps-slot]').textContent='Maps no está disponible. Completá la dirección manualmente.';search.disabled=false;}});
document.addEventListener('input',e=>{const root=e.target.closest('[data-ge-logistics-address]');if(root&&e.target!==field(root,'place_id'))field(root,'place_id').value='';});
function enrichProfiles(){document.querySelectorAll('[data-ge-address-item],.ge-workspace-form').forEach(root=>{if(root.hasAttribute('data-ge-logistics-address'))return;const inputs=[...root.querySelectorAll('input,select,textarea')];const street=inputs.find(el=>el.name==='street'||/\[street\]$/.test(el.name));if(!street)return;root.setAttribute('data-ge-logistics-address','');inputs.forEach(el=>{const key=el.name.match(/\[([^\]]+)\]$/)?.[1]||el.name;if(['street','city','postal_code','phone','hours','notes','province','country','recipient','place_id'].includes(key))el.dataset.addressField=key;});if(!field(root,'place_id')){const hidden=document.createElement('input');hidden.type='hidden';hidden.name=street.name.replace('street','place_id');hidden.dataset.addressField='place_id';root.append(hidden);}if(window.geLogisticsMaps){const button=document.createElement('button');button.type='button';button.dataset.geMapsSearch='';button.textContent='Buscar dirección con Google Maps';const slot=document.createElement('div');slot.dataset.geMapsSlot='';root.append(button,slot);}});}
document.addEventListener('DOMContentLoaded',()=>{enrichProfiles();if(window.geLogisticsMaps)document.querySelectorAll('[data-ge-maps-search]').forEach(b=>b.hidden=false);const list=document.querySelector('[data-ge-address-list]');if(list)new MutationObserver(enrichProfiles).observe(list,{childList:true});});
document.addEventListener('submit',e=>{const form=e.target;if(!form.matches('.ge-logistics-form')||!form.checkValidity())return;form.querySelectorAll('button[type=submit]').forEach(b=>{b.disabled=true;b.textContent='Guardando…';});});
})();
