const {chromium}=require('/mnt/c/Users/Leo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path');
const pixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6KCIAAAAASUVORK5CYII=','base64');
const base='http://127.0.0.1:18765';
function check(ok,name){console.log((ok?'PASS ':'FAIL ')+name);if(!ok)throw new Error(name);}
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/home/leo/.cache/ms-playwright/chromium-1247/chrome-linux64/chrome',args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/new');await page.locator('[name=customer_name]').fill('QA Artwork v2');await page.locator('[name=customer_email]').fill('qa-artwork-v2@example.invalid');
 await page.locator('[data-ge-add-line=custom]').click();await page.locator('[data-ge-line]').first().locator('input[type=search]').fill('QA browser item A');
 await page.locator('[name="lines[0][unit_price]"]').fill('100');
 await page.locator('[data-ge-add-line=custom]').click();let lines=page.locator('[data-ge-line]');await lines.nth(1).locator('input[type=search]').fill('QA browser item B');await lines.nth(1).locator('[name$="[unit_price]"]').fill('200');
 await page.locator('[data-ge-add-line=custom]').click();await lines.nth(2).locator('input[type=search]').fill('QA browser item C');await lines.nth(2).locator('[name$="[unit_price]"]').fill('300');
 await lines.nth(0).locator('[data-ge-artwork-select]').setInputFiles([{name:'browser-a1.png',mimeType:'image/png',buffer:pixel},{name:'browser-a2.png',mimeType:'image/png',buffer:pixel}]);
 await lines.nth(1).locator('[data-ge-artwork-select]').setInputFiles({name:'browser-b.png',mimeType:'image/png',buffer:pixel});
 await lines.nth(2).locator('[data-ge-artwork-select]').setInputFiles({name:'browser-c.png',mimeType:'image/png',buffer:pixel});
 await page.waitForFunction(()=>document.querySelectorAll('[data-ge-artwork-list] [type=hidden]').length===4,{},{timeout:60000});
 check(await lines.nth(0).locator('[data-ge-artwork-list] li').count()===2,'multiple UI files for one item');
 check(await lines.nth(1).locator('[data-ge-artwork-list] li').count()===1,'separate UI file per item');
 await lines.nth(0).locator('[data-ge-artwork]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'../outputs/quotes-artwork-desktop.png')});
 await page.setViewportSize({width:390,height:844});await lines.nth(0).locator('[data-ge-artwork]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'../outputs/quotes-artwork-mobile.png')});
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile no horizontal overflow');
 await page.setViewportSize({width:1440,height:1000});
 const saveRequest=page.waitForRequest(r=>r.url().includes('/wp-admin/admin-post.php')&&r.method()==='POST');
 await Promise.all([page.waitForURL(/quote_id=/),page.locator('button[name=quote_intent][value=draft]').click()]);
 const originalRequest=await saveRequest;
 const id=new URL(page.url()).searchParams.get('quote_id');check(!!id,'new quote persisted via actual form');
 const repeated=await page.request.post(base+'/wp-admin/admin-post.php',{data:originalRequest.postDataBuffer(),headers:{'Content-Type':originalRequest.headers()['content-type']}});
 check(new URL(repeated.url()).searchParams.get('quote_id')===id,'retry same save returns same quote');
 let stored=await(await page.request.get(base+'/inspect?quote_id='+id)).json();check(stored.files.length===4,'reference-only form persisted four files');
 check(stored.quote.snapshot.items.length===3,'three custom quote items saved');
 await page.goto(base+'/edit?quote_id='+id);check(await page.locator('[data-ge-existing-file]').count()===4,'edit shows all existing per-item files');
 await page.locator('[data-ge-line]').first().locator('[data-ge-artwork-select]').setInputFiles({name:'browser-a3.png',mimeType:'image/png',buffer:pixel});
 await page.waitForFunction(()=>document.querySelectorAll('[data-ge-artwork-list] [type=hidden]').length===5,{},{timeout:30000});
 await Promise.all([page.waitForURL(u=>!u.pathname.includes('/edit')),page.locator('button[name=quote_intent][value=draft]').click()]);
 stored=await(await page.request.get(base+'/inspect?quote_id='+id)).json();check(stored.files.length===5,'edit adds file without replacing originals');
 await page.goto(base+'/edit?quote_id='+id);await page.locator('[data-ge-line]').first().locator('[data-ge-duplicate-line]').click();
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('[data-ge-line-uuid]')).every(n=>n.value));
 const uuids=await page.locator('[data-ge-line-uuid]').evaluateAll(nodes=>nodes.map(n=>n.value));check(new Set(uuids).size===uuids.length,'duplicate item gets new UUID');
 check(await page.locator('[data-ge-line]').nth(1).locator('[data-ge-artwork-list] li').count()===0,'duplicating item does not invent artwork association');
 await page.locator('[data-ge-line]').nth(1).locator('[data-ge-remove-line]').click();
 await page.locator('[data-ge-line]').first().locator('[data-ge-artwork-select]').setInputFiles({name:'remove-before-save.png',mimeType:'image/png',buffer:pixel});
 await page.locator('[data-ge-line]').first().locator('[data-ge-artwork-list] li').last().getByRole('button',{name:'Quitar',exact:true}).click();
 check(await page.locator('[data-ge-line]').first().locator('[data-ge-artwork-list] li').count()===3,'file can be removed before saving');
 console.log('BROWSER_ERRORS='+JSON.stringify(errors));
 await browser.close();
 check(errors.length===0,'no browser JS errors');
 // PHP warnings are checked separately in HTTP and server logs.
 fs.writeFileSync(path.join(__dirname,'qa-browser-context.json'),JSON.stringify({quote_id:Number(id),uuid:stored.quote.snapshot.items[0].line_uuid},null,2));
})().catch(e=>{console.error(e);process.exit(1);});
