<?php
// Authorized recovery of the commercial conversion for quote 1199. Never collect or issue an invoice.
define('DISABLE_WP_CRON',true);define('FS_METHOD','direct');$_SERVER['HTTP_HOST']='graphex.ar';$_SERVER['SERVER_NAME']='graphex.ar';$_SERVER['HTTPS']='on';$_SERVER['REQUEST_URI']='/';require '/home/graphexpress/public_html/wp-load.php';wp_set_current_user(1);
if(home_url()!=='https://graphex.ar')throw new Exception('Unexpected production site');
$q=GE_WTP_Commercial_Quotes::get(1199,1);if(is_wp_error($q))throw new Exception('Quote inaccessible');
$versions=get_post_meta(1199,GE_WTP_Commercial_Quotes::VERSIONS_META,true);$hash=hash('sha256',wp_json_encode($versions));
$protected=[];foreach([1121,1171] as $id){$protected[$id]=hash('sha256',wp_json_encode(get_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,true)));}
if($q['version']!==1||(int)$q['snapshot']['total_cents']!==8100000||(int)$q['snapshot']['tax_cents']!==0||($q['snapshot']['issuer_snapshot']['id']??'')!=='leonardo-c'||($q['snapshot']['billing_profile_id']??'')!=='default'||(int)$q['customer_id']!==37)throw new Exception('1199 changed; review required');
$backup='/home/graphexpress/job-flow-qa-20261007/quote-1199-conversion-backup-20261008.json';
$payload=['quote_id'=>1199,'at'=>gmdate('c'),'post'=>get_post(1199,ARRAY_A),'meta'=>get_post_meta(1199),'version_hash'=>$hash,'protected_version_hashes'=>$protected,'issuer_catalog_hash'=>hash('sha256',wp_json_encode(GE_WTP_Billing_Issuers::all())),'receiver_profiles_hash'=>hash('sha256',wp_json_encode(GE_WTP_Customer_Branches::profiles(37)))];
if(!file_exists($backup)){if(file_put_contents($backup,wp_json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX)===false)throw new Exception('Backup failed');chmod($backup,0600);}
$saved=json_decode(file_get_contents($backup),true);if(!$saved||$saved['quote_id']!==1199||$saved['version_hash']!==$hash||!isset($saved['meta'][GE_WTP_Commercial_Quotes::VERSIONS_META][0]))throw new Exception('Backup restore verification failed');
if(hash('sha256',wp_json_encode(maybe_unserialize($saved['meta'][GE_WTP_Commercial_Quotes::VERSIONS_META][0])))!==$hash)throw new Exception('Backup version reconstruction failed');
$orders=wc_get_orders(['limit'=>50,'meta_key'=>'_ge_commercial_quote_id','meta_value'=>1199]);$operational=[];foreach($orders as $o){if($o->get_meta('_ge_commercial_payment_order')!=='yes')$operational[]=$o->get_id();}if(count($operational)>1)throw new Exception('Multiple orders; reconcile before proceeding');
if(getenv('GE_CONVERT_1199')!=='yes'){echo wp_json_encode(['backup_verified'=>true,'version'=>1,'existing_orders'=>$operational,'conversion_ready'=>!is_wp_error(GE_WTP_Commercial_Quotes::prepare_for_conversion(1199,1))]);exit;}
add_filter('pre_wp_mail',function(){throw new Exception('Unexpected email: stopped before sending');},PHP_INT_MAX);
$o=GE_WTP_Commercial_Checkout::convert_staff(1199,['expected_version'=>1,'confirmation_method'=>'staff','payment_state'=>'unregistered','reason'=>'Pedido comercial solicitado por el personal; cobro, facturacion y arte pendientes de revision.'],1);if(is_wp_error($o))throw new Exception($o->get_error_code().': '.$o->get_error_message());
$repeat=GE_WTP_Commercial_Checkout::convert_staff(1199,['expected_version'=>1],1);if(is_wp_error($repeat)||$repeat->get_id()!==$o->get_id())throw new Exception('Retry mismatch');
if($hash!==hash('sha256',wp_json_encode(get_post_meta(1199,GE_WTP_Commercial_Quotes::VERSIONS_META,true))))throw new Exception('Saved version changed');
foreach($protected as $id=>$expected){if($expected!==hash('sha256',wp_json_encode(get_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,true))))throw new Exception('Protected quote changed');}
if($saved['issuer_catalog_hash']!==hash('sha256',wp_json_encode(GE_WTP_Billing_Issuers::all()))||$saved['receiver_profiles_hash']!==hash('sha256',wp_json_encode(GE_WTP_Customer_Branches::profiles(37))))throw new Exception('Fiscal profile changed');
if($o->get_total()!=='81000.00'||$o->get_meta('_ge_payment_state')!=='pending'||(int)$o->get_meta('_ge_amount_paid_cents')!==0||$o->get_meta('_ge_production_status')!=='pending'||$o->get_meta('_ge_commercial_fiscal_status')!=='pending')throw new Exception('Unexpected commercial order state');
echo wp_json_encode(['quote_id'=>1199,'quote_number'=>$q['number'],'version'=>1,'order_id'=>$o->get_id(),'order_number'=>$o->get_order_number(),'total_cents'=>8100000,'tax_cents'=>0,'issuer_id'=>'leonardo-c','receiver_profile_id'=>'default','payment'=>'pending','fiscal'=>'pending','artwork'=>'pending','production'=>$o->get_meta('_ge_production_status'),'order_stage'=>$o->get_meta(GE_WTP_Workflow::STAGE_META),'retry_same_order'=>true,'versions_unchanged'=>true,'protected_quotes_unchanged'=>true,'profiles_unchanged'=>true,'backup_verified'=>true],JSON_PRETTY_PRINT);
