<?php
define('DISABLE_WP_CRON',true);define('FS_METHOD','direct');$_SERVER['HTTP_HOST']='graphex.ar';$_SERVER['SERVER_NAME']='graphex.ar';$_SERVER['HTTPS']='on';$_SERVER['REQUEST_URI']='/';require '/home/graphexpress/public_html/wp-load.php';
if(GE_Organization::PRIMARY!=='graph-express')throw new Exception('Wrong organization');wp_set_current_user(1);$id=1121;$q=GE_WTP_Commercial_Quotes::get($id,1);if(is_wp_error($q)||!in_array($q['status'],['draft','sent','viewed'],true)||$q['converted_order_id']||get_post_meta($id,'_ge_commercial_initial_payment_order',true))throw new Exception('Historical or financial quote requires separate review');
$s=$q['snapshot'];if(count($s['items'])!==3||(int)$s['total_cents']!==185000000||(int)$s['tax_cents']!==0||($s['issuer_snapshot']['id']??'')!=='leonardo-c')throw new Exception('Commercial content changed');
$current=GE_Organization_Runtime::snapshot();if(($current['general']['brand_name']??'')!=='GRAPHEX')throw new Exception('Brand configuration not corrected');
if(($s['organization_snapshot']['general']['brand_name']??'')==='GRAPHEX'){echo wp_json_encode(['id'=>$id,'version'=>$q['version'],'status'=>$q['status'],'idempotent'=>true]);exit;}
$lock='ge_quote_publish_notice_'.$id;if(!add_option($lock,time(),'',false))throw new Exception('Quote busy');
try{
 $fresh=GE_WTP_Commercial_Quotes::get($id,1);if($fresh['version']!==$q['version']||GE_WTP_Quote_Billing_Control::hash($fresh['snapshot'])!==GE_WTP_Quote_Billing_Control::hash($s))throw new Exception('Concurrent revision');
 $versions=get_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,true);$backup='/home/graphexpress/job-flow-qa-20261007/quote-1121-brand-backup-20261008.json';if(file_exists($backup))throw new Exception('Inspect previous brand recovery before retry');$before=['quote'=>$q,'versions'=>$versions];file_put_contents($backup,wp_json_encode($before));chmod($backup,0600);if(json_decode(file_get_contents($backup),true)['quote']['version']!==$q['version'])throw new Exception('Invalid backup');
 $next=$s;$next['organization_snapshot']['general']['brand_name']='GRAPHEX';$next['organization_snapshot']['branding']=$current['branding'];$next['organization_snapshot']['documents']['footer']=str_ireplace('Graph Express','GRAPHEX',$next['organization_snapshot']['documents']['footer']??'');$next['organization_snapshot']['revision']=$current['revision'];$next['organization_snapshot']['captured_at']=gmdate('c');unset($next['organization_snapshot']['hash']);$next['organization_snapshot']['hash']=hash('sha256',wp_json_encode($next['organization_snapshot']));unset($next['snapshot_hash']);$next['snapshot_hash']=GE_WTP_Quote_Billing_Control::hash($next);
 $newVersion=$q['version']+1;$versions[$newVersion]=$next;update_post_meta($id,GE_WTP_Commercial_Quotes::VERSIONS_META,$versions);update_post_meta($id,GE_WTP_Commercial_Quotes::CURRENT_META,$newVersion);
 GE_WTP_Commercial_Quotes::record_event($id,'commercial_brand_updated',1,['before_version'=>$q['version'],'after_version'=>$newVersion,'before_hash'=>GE_WTP_Quote_Billing_Control::hash($s),'after_hash'=>GE_WTP_Quote_Billing_Control::hash($next),'reason'=>'Leo pidió GRAPHEX en el PDF comercial; importes, estado e identidad legal conservados','no_customer_notice'=>true]);
 $after=GE_WTP_Commercial_Quotes::get($id,1);if($after['status']!==$q['status']||$after['snapshot']['items']!==$s['items']||$after['snapshot']['receiver_snapshot']!==$s['receiver_snapshot']||$after['snapshot']['issuer_snapshot']!==$s['issuer_snapshot'])throw new Exception('Commercial preservation failed');
 $pdf=GE_WTP_Commercial_Quote_PDF::build($after);if(is_wp_error($pdf))throw new Exception($pdf->get_error_message());$path='/home/graphexpress/job-flow-qa-20261007/quote-1121-graphex.pdf';file_put_contents($path,$pdf);chmod($path,0600);echo wp_json_encode(['id'=>$id,'version'=>$newVersion,'previous_version_preserved'=>$q['version'],'status'=>$after['status'],'total_cents'=>$next['total_cents'],'tax_cents'=>$next['tax_cents'],'brand'=>'GRAPHEX','pdf_sha256'=>hash('sha256',$pdf),'backup'=>$backup],JSON_PRETTY_PRINT);
}finally{delete_option($lock);}
